<a href="https://colab.research.google.com/github/evanskips2727-del/Africa-Public-Health-Intelligence-/blob/main/Africa_Public_Health_Intelligence.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

from google.colab import files

uploaded = files.upload()

Saving Africa_Public_Health_Intelligence_Prototype.zip to Africa_Public_Health_Intelligence_Prototype.zip

In [ ]:

import os
import zipfile

zip_path = "/content/Africa_Public_Health_Intelligence_Prototype.zip"
extract_dir = "/content"

with zipfile.ZipFile(zip_path, "r") as z:
    z.extractall(extract_dir)

print("Project extracted successfully.")
print(os.listdir("/content"))

Project extracted successfully.
['.config', 'africa-public-health-intelligence', 'Africa_Public_Health_Intelligence_Prototype.zip', 'sample_data']

In [ ]:

%cd /content/africa-public-health-intelligence

!find . -maxdepth 2 -type f | sort

/content/africa-public-health-intelligence
./app.py
./config/countries.csv
./data/SOURCES.md
./docs/PORTFOLIO_CASE_STUDY.md
./.gitignore
./README.md
./requirements.txt
./scripts/download_data.py
./src/__init__.py
./src/pipeline.py
./src/risk_engine.py
./tests/test_risk.py

In [ ]:

%cd /content/africa-public-health-intelligence

!cat requirements.txt

/content/africa-public-health-intelligence
pandas>=2.2
numpy>=1.26
requests>=2.31
scikit-learn>=1.5
statsmodels>=0.14
plotly>=5.24
streamlit>=1.39
pyarrow>=17.0

In [ ]:
%pip install -r requirements.txt

Requirement already satisfied: pandas>=2.2 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 1)) (2.2.3)
Requirement already satisfied: numpy>=1.26 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 2)) (2.1.3)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 3)) (2.32.4)
Requirement already satisfied: scikit-learn>=1.5 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 4)) (1.6.1)
Requirement already satisfied: statsmodels>=0.14 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 5)) (0.15.0)
Requirement already satisfied: plotly>=5.24 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 6)) (5.24.1)
Collecting streamlit>=1.39 (from -r requirements.txt (line 7))
  Downloading streamlit-1.65.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pyarrow>=17.0 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 8)) (23.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.2->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.2->-r requirements.txt (line 1)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.2->-r requirements.txt (line 1)) (2026.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31->-r requirements.txt (line 3)) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31->-r requirements.txt (line 3)) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31->-r requirements.txt (line 3)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31->-r requirements.txt (line 3)) (2026.7.22)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.5->-r requirements.txt (line 4)) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.5->-r requirements.txt (line 4)) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.5->-r requirements.txt (line 4)) (3.7.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels>=0.14->-r requirements.txt (line 5)) (1.0.3)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.13/dist-packages (from statsmodels>=0.14->-r requirements.txt (line 5)) (26.3)
Requirement already satisfied: formulaic>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from statsmodels>=0.14->-r requirements.txt (line 5)) (1.2.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly>=5.24->-r requirements.txt (line 6)) (9.1.4)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=5.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit>=1.39->-r requirements.txt (line 7)) (5.5.0)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.13/dist-packages (from streamlit>=1.39->-r requirements.txt (line 7)) (8.5.0)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.13/dist-packages (from streamlit>=1.39->-r requirements.txt (line 7)) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit>=1.39->-r requirements.txt (line 7))
  Downloading pydeck-0.9.3-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=5.26.1 in /usr/local/lib/python3.13/dist-packages (from streamlit>=1.39->-r requirements.txt (line 7)) (6.33.6)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.13/dist-packages (from streamlit>=1.39->-r requirements.txt (line 7)) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from streamlit>=1.39->-r requirements.txt (line 7)) (4.16.0)
Requirement already satisfied: starlette<2,>=0.46.0 in /usr/local/lib/python3.13/dist-packages (from streamlit>=1.39->-r requirements.txt (line 7)) (1.7.0)
Requirement already satisfied: uvicorn<1,>=0.30.0 in /usr/local/lib/python3.13/dist-packages (from streamlit>=1.39->-r requirements.txt (line 7)) (0.54.0)
Requirement already satisfied: httptools<1,>=0.6.3 in /usr/local/lib/python3.13/dist-packages (from streamlit>=1.39->-r requirements.txt (line 7)) (0.8.0)
Requirement already satisfied: anyio<5,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit>=1.39->-r requirements.txt (line 7)) (4.15.1)
Requirement already satisfied: python-multipart<1,>=0.0.10 in /usr/local/lib/python3.13/dist-packages (from streamlit>=1.39->-r requirements.txt (line 7)) (0.0.32)
Requirement already satisfied: websockets<18,>=12.0.0 in /usr/local/lib/python3.13/dist-packages (from streamlit>=1.39->-r requirements.txt (line 7)) (15.0.1)
Requirement already satisfied: itsdangerous<3,>=2.1.2 in /usr/local/lib/python3.13/dist-packages (from streamlit>=1.39->-r requirements.txt (line 7)) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.13/dist-packages (from streamlit>=1.39->-r requirements.txt (line 7)) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit>=1.39->-r requirements.txt (line 7)) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit>=1.39->-r requirements.txt (line 7)) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.13/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit>=1.39->-r requirements.txt (line 7)) (2.26.0)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.14->-r requirements.txt (line 5)) (2.0.1)
Requirement already satisfied: wrapt>=1.17.0rc1 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.14->-r requirements.txt (line 5)) (2.5.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn>=1.5->-r requirements.txt (line 4)) (3.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2->-r requirements.txt (line 1)) (1.17.0)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.13/dist-packages (from uvicorn<1,>=0.30.0->streamlit>=1.39->-r requirements.txt (line 7)) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit>=1.39->-r requirements.txt (line 7)) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit>=1.39->-r requirements.txt (line 7)) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit>=1.39->-r requirements.txt (line 7)) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit>=1.39->-r requirements.txt (line 7)) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit>=1.39->-r requirements.txt (line 7)) (2026.6.3)
Downloading streamlit-1.65.0-py3-none-any.whl (10.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 70.7 MB/s eta 0:00:00
Downloading pydeck-0.9.3-py2.py3-none-any.whl (11.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 90.7 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit
Successfully installed pydeck-0.9.3 streamlit-1.65.0

In [ ]:
%pip install pytest

Requirement already satisfied: pytest in /usr/local/lib/python3.13/dist-packages (8.4.2)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.13/dist-packages (from pytest) (2.3.0)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.13/dist-packages (from pytest) (26.3)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.13/dist-packages (from pytest) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.13/dist-packages (from pytest) (2.21.0)

In [ ]:

%cd /content/africa-public-health-intelligence

!python -m pytest -q

/content/africa-public-health-intelligence
...                                                                      [100%]
3 passed in 0.51s

In [ ]:
!python scripts/download_data.py

Downloading malaria_incidence...
  saved /content/africa-public-health-intelligence/data/raw/malaria_incidence.csv (73,442 bytes)
Downloading measles_cases...
  saved /content/africa-public-health-intelligence/data/raw/measles_cases.csv (217,502 bytes)
Downloading cholera_cases...
  saved /content/africa-public-health-intelligence/data/raw/cholera_cases.csv (76,017 bytes)
Downloading measles_vax...
  saved /content/africa-public-health-intelligence/data/raw/measles_vax.csv (210,678 bytes)
Downloading population...
Downloading WHO Disease Outbreak News...
Downloading climate: Kenya
Downloading climate: Uganda
Downloading climate: Tanzania
Downloading climate: Rwanda
Downloading climate: Democratic Republic of Congo
Downloading climate: South Sudan
Downloading climate: Ethiopia
Downloading climate: Somalia
Downloading climate: Sudan
Downloading climate: Nigeria
Downloading climate: Ghana
Downloading climate: Cameroon
Downloading climate: Chad
Downloading climate: Niger
Downloading climate: Burkina Faso
Downloading climate: Mali
Downloading climate: Senegal
Downloading climate: Cote d'Ivoire
Downloading climate: Guinea
Downloading climate: Liberia
Downloading climate: Sierra Leone

All available downloads completed.

In [ ]:

import os

raw_dir = "data/raw"

if os.path.exists(raw_dir):
    for filename in sorted(os.listdir(raw_dir)):
        path = os.path.join(raw_dir, filename)

        if os.path.isfile(path):
            print(f"{filename}: {os.path.getsize(path):,} bytes")
else:
    print("The raw data directory does not exist.")

.gitkeep: 0 bytes
cholera_cases.csv: 76,017 bytes
malaria_incidence.csv: 73,442 bytes
measles_cases.csv: 217,502 bytes
measles_vax.csv: 210,678 bytes
nasa_climate_monthly.csv: 99,962 bytes
population_world_bank.json: 3,512,353 bytes
who_disease_outbreak_news.json: 271,773 bytes

In [ ]:

import glob
import pandas as pd
import os

for path in glob.glob("data/raw/*.csv"):
    print(f"\n{'=' * 60}")
    print(os.path.basename(path))

    df = pd.read_csv(path, nrows=5)
    display(df)

============================================================
measles_vax.csv

        Entity Code  Year  Measles, first dose (MCV1)
0  Afghanistan  AFG  1980                          11
1  Afghanistan  AFG  1982                           8
2  Afghanistan  AFG  1983                           9
3  Afghanistan  AFG  1984                          14
4  Afghanistan  AFG  1985                          14

============================================================
cholera_cases.csv

        Entity Code  Year  Reported cholera cases
0  Afghanistan  AFG  1960                     887
1  Afghanistan  AFG  1965                     218
2  Afghanistan  AFG  1993                   37046
3  Afghanistan  AFG  1994                   38735
4  Afghanistan  AFG  1995                   19903

============================================================
measles_cases.csv

        Entity Code  Year  Measles - number of reported cases
0  Afghanistan  AFG  1974                                   7
1  Afghanistan  AFG  1975                                 466
2  Afghanistan  AFG  1976                                  26
3  Afghanistan  AFG  1977                               28174
4  Afghanistan  AFG  1978                               43964

============================================================
nasa_climate_monthly.csv

  country iso3    date  temperature_c  precipitation_mm
0   Kenya  KEN  201501          21.52              0.23
1   Kenya  KEN  201502          21.99              1.86
2   Kenya  KEN  201503          21.65              0.81
3   Kenya  KEN  201504          21.24              2.84
4   Kenya  KEN  201505          19.88              1.20

============================================================
malaria_incidence.csv

        Entity Code  Year  Incidence of malaria (per 1,000 population at risk)
0  Afghanistan  AFG  2000                                              84.48
1  Afghanistan  AFG  2001                                              83.83
2  Afghanistan  AFG  2002                                              83.79
3  Afghanistan  AFG  2003                                              70.81
4  Afghanistan  AFG  2004                                              39.41

In [ ]:
!python -m src.pipeline

/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
Built 63 country-disease risk records.
                     country iso3 disease  latest_year  latest_value  anomaly_score  trend_component  forecast_value  forecast_component  measles_vax_pct  vax_gap_component  temp_anomaly  precip_anomaly_pct  climate_component  event_component  risk_score risk_tier                                                                                                                               explanation
                        Chad  TCD Measles         2024        6978.0       4.163301         1.000000     6999.333333                 0.0             66.0               0.58   -203.949545       -13025.863648                1.0              1.0        78.7  Critical       recent surveillance anomaly; rising recent trend; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                       Sudan  SDN Cholera         2024       53001.0       2.653367         1.000000    20635.000000                 1.0              NaN               0.00   -204.043970       -30766.164958                1.0              1.0        74.9      High recent surveillance anomaly; rising recent trend; forecast points upward; unusual climate conditions; recent outbreak intelligence signal
                      Uganda  UGA Measles         2024        2180.0       2.168354         0.906522      877.000000                 1.0             90.0               0.10   -203.478182        -4991.996915                1.0              1.0        70.9      High recent surveillance anomaly; rising recent trend; forecast points upward; unusual climate conditions; recent outbreak intelligence signal
                    Ethiopia  ETH Malaria         2024         138.5       3.700050         1.000000      102.543333                 0.0              NaN               0.00   -201.858682        -5475.279960                1.0              1.0        67.8      High                         recent surveillance anomaly; rising recent trend; unusual climate conditions; recent outbreak intelligence signal
                Burkina Faso  BFA Measles         2024        4397.0       5.621260         0.000000     1776.333333                 1.0             88.0               0.14   -203.966667        -7775.804467                1.0              1.0        67.1      High                      recent surveillance anomaly; forecast points upward; unusual climate conditions; recent outbreak intelligence signal

In [ ]:

import os
import pandas as pd

risk_path = "data/processed/risk_register.csv"

if os.path.exists(risk_path):
    risk_df = pd.read_csv(risk_path)

    print("Records:", len(risk_df))
    print("Columns:", risk_df.columns.tolist())

    display(risk_df.head(20))
else:
    print("Risk register not found. Check the pipeline output.")

Records: 63
Columns: ['country', 'iso3', 'disease', 'latest_year', 'latest_value', 'anomaly_score', 'trend_component', 'forecast_value', 'forecast_component', 'measles_vax_pct', 'vax_gap_component', 'temp_anomaly', 'precip_anomaly_pct', 'climate_component', 'event_component', 'risk_score', 'risk_tier', 'explanation']

,country,iso3,disease,latest_year,latest_value,anomaly_score,trend_component,forecast_value,forecast_component,measles_vax_pct,vax_gap_component,temp_anomaly,precip_anomaly_pct,climate_component,event_component,risk_score,risk_tier,explanation
0,Chad,TCD,Measles,2024,6978.00,4.163301,1.000000,6999.333333,0.0,66.0,0.58,-203.949545,-13025.863648,1.0,1.0,78.7,Critical,recent surveillance anomaly; rising recent tre...
1,Sudan,SDN,Cholera,2024,53001.00,2.653367,1.000000,20635.000000,1.0,NaN,0.00,-204.043970,-30766.164958,1.0,1.0,74.9,High,recent surveillance anomaly; rising recent tre...
2,Uganda,UGA,Measles,2024,2180.00,2.168354,0.906522,877.000000,1.0,90.0,0.10,-203.478182,-4991.996915,1.0,1.0,70.9,High,recent surveillance anomaly; rising recent tre...
3,Ethiopia,ETH,Malaria,2024,138.50,3.700050,1.000000,102.543333,0.0,NaN,0.00,-201.858682,-5475.279960,1.0,1.0,67.8,High,recent surveillance anomaly; rising recent tre...
4,Burkina Faso,BFA,Measles,2024,4397.00,5.621260,0.000000,1776.333333,1.0,88.0,0.14,-203.966667,-7775.804467,1.0,1.0,67.1,High,recent surveillance anomaly; forecast points u...
5,Ghana,GHA,Measles,2024,1944.00,3.403212,1.000000,1540.333333,0.0,90.0,0.10,-205.090606,-5181.300409,1.0,1.0,67.0,High,recent surveillance anomaly; rising recent tre...
6,Cote d'Ivoire,CIV,Measles,2024,1872.00,0.674491,1.000000,1609.666667,1.0,75.0,0.40,-204.632212,-5627.695627,1.0,1.0,66.1,High,rising recent trend; forecast points upward; u...
7,Democratic Republic of Congo,COD,Measles,2024,311500.00,2.367064,0.780642,209126.666667,0.0,55.0,0.80,-204.655591,-4194.733328,1.0,1.0,65.4,High,recent surveillance anomaly; rising recent tre...
8,Somalia,SOM,Measles,2024,1529.00,0.000000,1.000000,7352.333333,1.0,64.0,0.62,-204.926045,-14266.302861,1.0,1.0,64.3,High,rising recent trend; forecast points upward; i...
9,South Sudan,SSD,Cholera,2024,20132.00,2.759470,0.322883,7342.333333,1.0,NaN,0.00,-203.478682,-6401.463767,1.0,1.0,62.2,High,recent surveillance anomaly; forecast points u...
10,Ethiopia,ETH,Measles,2024,31044.00,1.999117,1.000000,21458.000000,0.0,72.0,0.46,-201.858682,-5475.279960,1.0,1.0,61.9,High,rising recent trend; unusual climate condition...
11,Cameroon,CMR,Cholera,2024,199.00,0.674491,1.000000,7033.333333,1.0,NaN,0.00,-203.483621,-5487.838056,1.0,1.0,60.1,High,rising recent trend; forecast points upward; u...
12,Chad,TCD,Cholera,2019,93.00,0.674491,1.000000,6208.666667,1.0,NaN,0.00,-203.949545,-13025.863648,1.0,1.0,60.1,High,rising recent trend; forecast points upward; u...
13,Kenya,KEN,Measles,2024,525.00,0.280713,1.000000,1065.000000,1.0,88.0,0.14,-203.977561,-13943.773066,1.0,1.0,59.2,High,rising recent trend; forecast points upward; u...
14,Guinea,GIN,Cholera,2014,1.00,0.054224,1.000000,2556.666667,1.0,NaN,0.00,-204.785667,-1862.529024,1.0,1.0,55.4,High,rising recent trend; forecast points upward; u...
15,Burkina Faso,BFA,Cholera,2022,4.00,0.000000,1.000000,50.000000,1.0,NaN,0.00,-203.966667,-7775.804467,1.0,1.0,55.0,High,rising recent trend; forecast points upward; u...
16,Sudan,SDN,Malaria,2024,98.25,2.457207,0.792051,89.280000,0.0,NaN,0.00,-204.043970,-30766.164958,1.0,1.0,54.3,High,recent surveillance anomaly; rising recent tre...
17,Ghana,GHA,Malaria,2024,195.77,3.618161,0.238818,200.493333,0.0,NaN,0.00,-205.090606,-5181.300409,1.0,1.0,51.9,High,recent surveillance anomaly; unusual climate c...
18,Cameroon,CMR,Measles,2024,863.00,0.626937,1.000000,3395.000000,0.0,71.0,0.48,-203.483621,-5487.838056,1.0,1.0,51.9,High,rising recent trend; unusual climate condition...
19,Guinea,GIN,Measles,2024,577.00,0.674491,0.000000,362.666667,1.0,60.0,0.70,-204.785667,-1862.529024,1.0,1.0,50.6,High,forecast points upward; immunization gap; unus...

In [ ]:

%cd /content/africa-public-health-intelligence

with open("src/risk_engine.py", "r") as f:
    print(f.read())

/content/africa-public-health-intelligence
import numpy as np
import pandas as pd

RISK_BANDS = [
    (0, 25, "Low"),
    (25, 50, "Moderate"),
    (50, 75, "High"),
    (75, 101, "Critical"),
]

def robust_anomaly(series, window=5):
    """Robust rolling anomaly using median absolute deviation."""
    s = pd.Series(series, dtype="float64")
    med = s.rolling(window, min_periods=3).median()
    mad = (s - med).abs().rolling(window, min_periods=3).median()
    score = (s - med).abs() / (1.4826 * mad.replace(0, np.nan))
    return score.replace([np.inf, -np.inf], np.nan).fillna(0)

def trend_score(series, periods=3):
    """Score recent upward movement relative to a recent baseline."""
    s = pd.Series(series, dtype="float64").dropna()
    if len(s) < periods + 2:
        return 0.0
    recent = s.tail(periods).mean()
    baseline = s.iloc[-periods-3:-periods].mean() if len(s) >= periods + 3 else s.iloc[:-periods].mean()
    if baseline <= 0 or pd.isna(baseline):
        return 0.0
    pct = (recent - baseline) / baseline
    return float(np.clip((pct + 0.25) / 0.75, 0, 1))

def vaccination_gap(vax_percent):
    if pd.isna(vax_percent):
        return 0.0
    return float(np.clip((95 - vax_percent) / 50, 0, 1))

def climate_signal(temp_anomaly=None, precip_anomaly=None):
    vals = []
    if pd.notna(temp_anomaly):
        vals.append(np.clip(abs(temp_anomaly) / 3, 0, 1))
    if pd.notna(precip_anomaly):
        vals.append(np.clip(abs(precip_anomaly) / 100, 0, 1))
    return float(np.mean(vals)) if vals else 0.0

def risk_score(anomaly, trend, forecast_up, vax_gap, climate, event_signal):
    """
    Explainable heuristic. Weights are portfolio-demo weights, not WHO weights.
    """
    score = (
        0.30 * np.clip(anomaly / 4, 0, 1)
        + 0.20 * trend
        + 0.15 * forecast_up
        + 0.15 * vax_gap
        + 0.10 * climate
        + 0.10 * event_signal
    ) * 100
    return round(float(np.clip(score, 0, 100)), 1)

def risk_tier(score):
    for lo, hi, label in RISK_BANDS:
        if lo <= score < hi:
            return label
    return "Critical"

def explain(row):
    reasons = []
    if row.get("anomaly_score", 0) >= 2:
        reasons.append("recent surveillance anomaly")
    if row.get("trend_component", 0) >= 0.6:
        reasons.append("rising recent trend")
    if row.get("forecast_component", 0) >= 0.6:
        reasons.append("forecast points upward")
    if row.get("vax_gap_component", 0) >= 0.5:
        reasons.append("immunization gap")
    if row.get("climate_component", 0) >= 0.5:
        reasons.append("unusual climate conditions")
    if row.get("event_component", 0) >= 0.5:
        reasons.append("recent outbreak intelligence signal")
    return "; ".join(reasons) if reasons else "no strong converging signal"

In [ ]:

with open("src/pipeline.py", "r") as f:
    print(f.read())

from pathlib import Path
import json
import re
import numpy as np
import pandas as pd
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from .risk_engine import robust_anomaly, trend_score, vaccination_gap, climate_signal, risk_score, risk_tier, explain

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw"
OUT = ROOT / "data" / "processed"
OUT.mkdir(parents=True, exist_ok=True)

AFRO_COUNTRIES = set(pd.read_csv(ROOT / "config" / "countries.csv")["country"])

def read_owid(name):
    p = RAW / f"{name}.csv"
    if not p.exists():
        raise FileNotFoundError(f"{p} missing. Run: python scripts/download_data.py")
    df = pd.read_csv(p)
    # OWID standard columns are Entity, Code, Year, plus one value column.
    value = [c for c in df.columns if c not in {"Entity", "Code", "Year"}][0]
    return df.rename(columns={"Entity":"country", "Code":"iso3", "Year":"year", value:"value"})[
        ["country","iso3","year","value"]
    ]

def prepare_disease(name, disease):
    df = read_owid(name)
    df["disease"] = disease
    return df[df["country"].isin(AFRO_COUNTRIES)].copy()

def outbreak_signals():
    p = RAW / "who_disease_outbreak_news.json"
    if not p.exists():
        return pd.DataFrame(columns=["title","publication_date","text","event_signal"])
    payload = json.loads(p.read_text())
    if isinstance(payload, dict):
        items = payload.get("value") or payload.get("items") or []
    else:
        items = payload
    rows = []
    diseases = r"cholera|measles|malaria|mpox|monkeypox|ebola|marburg|yellow fever|meningitis|polio|lassa|dengue|rift valley"
    for x in items:
        title = str(x.get("Title") or x.get("title") or "")
        summary = str(x.get("Summary") or x.get("summary") or x.get("Overview") or "")
        text = f"{title} {summary}"
        if not re.search(diseases, text, flags=re.I):
            continue
        rows.append({
            "title": title,
            "publication_date": x.get("PublicationDate") or x.get("publicationDate"),
            "text": text,
            "event_signal": 1.0
        })
    return pd.DataFrame(rows)

def latest_climate():
    p = RAW / "nasa_climate_monthly.csv"
    if not p.exists():
        return pd.DataFrame()
    df = pd.read_csv(p)
    df["date"] = pd.to_datetime(df["date"], format="%Y%m", errors="coerce")
    df["year"] = df["date"].dt.year
    df["month"] = df["date"].dt.month
    # Compare latest year with the historical mean for each country/month.
    baseline = (
        df[df["year"] < df["year"].max()]
        .groupby(["iso3","month"])[["temperature_c","precipitation_mm"]]
        .mean()
        .reset_index()
        .rename(columns={"temperature_c":"temp_baseline","precipitation_mm":"precip_baseline"})
    )
    latest_year = df["year"].max()
    recent = df[df["year"] == latest_year].groupby(["iso3"])[["temperature_c","precipitation_mm"]].mean().reset_index()
    base = baseline.groupby("iso3")[["temp_baseline","precip_baseline"]].mean().reset_index()
    out = recent.merge(base, on="iso3", how="left")
    out["temp_anomaly"] = out["temperature_c"] - out["temp_baseline"]
    out["precip_anomaly_pct"] = 100 * (out["precipitation_mm"] - out["precip_baseline"]) / out["precip_baseline"].replace(0, np.nan)
    return out

def forecast(series):
    s = pd.Series(series, dtype="float64").dropna()
    if len(s) < 6:
        return np.nan
    try:
        model = ExponentialSmoothing(s, trend="add", damped_trend=True, initialization_method="estimated").fit(optimized=True)
        return float(model.forecast(1).iloc[0])
    except Exception:
        return float(s.tail(3).mean())

def build():
    diseases = {
        "malaria_incidence": ("malaria_incidence", "Malaria"),
        "measles_cases": ("measles_cases", "Measles"),
        "cholera_cases": ("cholera_cases", "Cholera"),
    }
    all_disease = []
    for source, (file_name, disease) in diseases.items():
        all_disease.append(prepare_disease(file_name, disease))
    disease_df = pd.concat(all_disease, ignore_index=True)

    # Add vaccination coverage as context.
    vax = read_owid("measles_vax").rename(columns={"value":"measles_vax_pct"})
    disease_df = disease_df.merge(vax[["country","year","measles_vax_pct"]], on=["country","year"], how="left")

    results = []
    for (country, disease), g in disease_df.groupby(["country","disease"]):
        g = g.sort_values("year").copy()
        g["anomaly_score"] = robust_anomaly(g["value"])
        latest = g.iloc[-1]
        fc = forecast(g["value"])
        prev = float(g["value"].iloc[-2]) if len(g) >= 2 else np.nan
        forecast_up = 1.0 if pd.notna(fc) and pd.notna(prev) and fc > prev * 1.05 else 0.0
        tr = trend_score(g["value"])
        vax = float(latest["measles_vax_pct"]) if disease == "Measles" and pd.notna(latest["measles_vax_pct"]) else np.nan

        results.append({
            "country": country,
            "iso3": latest["iso3"],
            "disease": disease,
            "latest_year": int(latest["year"]),
            "latest_value": float(latest["value"]),
            "anomaly_score": float(latest["anomaly_score"]),
            "trend_component": tr,
            "forecast_value": fc,
            "forecast_component": forecast_up,
            "measles_vax_pct": vax,
            "vax_gap_component": vaccination_gap(vax),
        })

    risk = pd.DataFrame(results)
    climate = latest_climate()
    if not climate.empty:
        risk = risk.merge(climate[["iso3","temp_anomaly","precip_anomaly_pct"]], on="iso3", how="left")
    else:
        risk["temp_anomaly"] = np.nan
        risk["precip_anomaly_pct"] = np.nan

    risk["climate_component"] = risk.apply(
        lambda r: climate_signal(r["temp_anomaly"], r["precip_anomaly_pct"]), axis=1
    )

    events = outbreak_signals()
    event_count = len(events)
    # For MVP, event intelligence is a region-level signal. A future version should
    # extract country/disease entities using NER and join them at country-disease level.
    risk["event_component"] = 1.0 if event_count else 0.0

    risk["risk_score"] = risk.apply(lambda r: risk_score(
        r["anomaly_score"], r["trend_component"], r["forecast_component"],
        r["vax_gap_component"], r["climate_component"], r["event_component"]
    ), axis=1)
    risk["risk_tier"] = risk["risk_score"].map(risk_tier)
    risk["explanation"] = risk.apply(explain, axis=1)

    risk = risk.sort_values("risk_score", ascending=False)
    risk.to_csv(OUT / "risk_register.csv", index=False)
    disease_df.to_csv(OUT / "disease_surveillance.csv", index=False)
    events.to_csv(OUT / "event_signals.csv", index=False)

    # Forecast table
    forecasts = risk[["country","iso3","disease","latest_year","latest_value","forecast_value"]].copy()
    forecasts.to_csv(OUT / "forecasts.csv", index=False)

    print(f"Built {len(risk):,} country-disease risk records.")
    print(risk.head(15).to_string(index=False))
    return risk

if __name__ == "__main__":
    build()

In [ ]:

import pandas as pd

climate = pd.read_csv("data/raw/nasa_climate_monthly.csv")

print("Shape:", climate.shape)
print("\nColumns:")
print(climate.columns.tolist())

print("\nFirst 10 records:")
display(climate.head(10))

print("\nSummary statistics:")
display(climate.describe(include="all").T)

Shape: (3213, 5)

Columns:
['country', 'iso3', 'date', 'temperature_c', 'precipitation_mm']

First 10 records:

  country iso3    date  temperature_c  precipitation_mm
0   Kenya  KEN  201501          21.52              0.23
1   Kenya  KEN  201502          21.99              1.86
2   Kenya  KEN  201503          21.65              0.81
3   Kenya  KEN  201504          21.24              2.84
4   Kenya  KEN  201505          19.88              1.20
5   Kenya  KEN  201506          19.25              0.83
6   Kenya  KEN  201507          19.33              0.37
7   Kenya  KEN  201508          19.77              0.28
8   Kenya  KEN  201509          21.06              0.16
9   Kenya  KEN  201510          21.60              0.94

Summary statistics:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
country,3213,21,Kenya,153,NaN,NaN,NaN,NaN,NaN,NaN,NaN
iso3,3213,21,KEN,153,NaN,NaN,NaN,NaN,NaN,NaN,NaN
date,3213.0,NaN,NaN,NaN,202046.117647,339.698856,201501.0,201713.0,202012.0,202311.0,202610.0
temperature_c,3213.0,NaN,NaN,NaN,12.17385,116.454764,-999.0,23.56,26.12,27.7,37.1
precipitation_mm,3213.0,NaN,NaN,NaN,-9.422944,114.062992,-999.0,0.23,2.07,4.81,82.27

In [ ]:

import pandas as pd
import numpy as np
from pathlib import Path

# Locate the climate dataset
climate_path = Path("data/raw/nasa_climate_monthly.csv")

climate = pd.read_csv(climate_path)

print("Original shape:", climate.shape)
print("Columns:", climate.columns.tolist())

# Standardize column names
climate.columns = climate.columns.str.strip().str.lower()

# Verify required columns
required = [
    "country",
    "iso3",
    "date",
    "temperature_c",
    "precipitation_mm"
]

missing_columns = set(required) - set(climate.columns)

if missing_columns:
    raise ValueError(
        f"Missing required columns: {missing_columns}"
    )

# Keep the required fields
climate = climate[required].copy()

# Convert sentinel values to missing values
numeric_columns = [
    "temperature_c",
    "precipitation_mm"
]

for col in numeric_columns:
    climate[col] = pd.to_numeric(
        climate[col],
        errors="coerce"
    )

    climate.loc[
        climate[col] == -999,
        col
    ] = np.nan

# Parse YYYYMM dates
date_string = (
    climate["date"]
    .astype("string")
    .str.replace(r"\.0$", "", regex=True)
    .str.strip()
)

climate["date"] = pd.to_datetime(
    date_string,
    format="%Y%m",
    errors="coerce"
)

# Flag implausible measurements for review
# These are quality-control bounds, not universal climate limits.
climate.loc[
    ~climate["temperature_c"].between(-90, 65),
    "temperature_c"
] = np.nan

climate.loc[
    climate["precipitation_mm"] < 0,
    "precipitation_mm"
] = np.nan

# Remove records without valid identifiers or dates
climate = climate.dropna(
    subset=["country", "iso3", "date"]
)

# Check duplicate country-month observations
duplicates = climate.duplicated(
    subset=["iso3", "date"],
    keep=False
)

print("\nDuplicate country-month rows:", duplicates.sum())

if duplicates.any():
    display(
        climate.loc[duplicates]
        .sort_values(["iso3", "date"])
        .head(20)
    )

# Do not silently aggregate duplicates.
# Investigate their source before deciding how to handle them.

# Sort records
climate = climate.sort_values(
    ["iso3", "date"]
).reset_index(drop=True)

print("\nCleaned shape:", climate.shape)

print("\nMissing values:")
print(climate.isna().sum())

print("\nCleaned summary statistics:")
display(climate[numeric_columns].describe())

# Save the cleaned dataset
output_path = Path("data/processed")
output_path.mkdir(parents=True, exist_ok=True)

cleaned_file = output_path / "climate_monthly_clean.csv"

climate.to_csv(cleaned_file, index=False)

print("\nSaved:", cleaned_file)

Original shape: (3213, 5)
Columns: ['country', 'iso3', 'date', 'temperature_c', 'precipitation_mm']

Duplicate country-month rows: 0

Cleaned shape: (2982, 5)

Missing values:
country              0
iso3                 0
date                 0
temperature_c       42
precipitation_mm    42
dtype: int64

Cleaned summary statistics:

       temperature_c  precipitation_mm
count    2940.000000       2940.000000
mean       25.571374          3.677786
std         3.918005          6.214456
min        12.650000          0.000000
25%        23.630000          0.200000
50%        26.110000          1.965000
75%        27.730000          4.930000
max        37.100000         82.270000

Saved: data/processed/climate_monthly_clean.csv

In [ ]:

def climate_signal(temp_anomaly=None, precip_anomaly=None):
    vals = []

    if pd.notna(temp_anomaly):
        vals.append(np.clip(abs(temp_anomaly) / 3, 0, 1))

    if pd.notna(precip_anomaly):
        vals.append(np.clip(abs(precip_anomaly) / 100, 0, 1))

    return float(np.mean(vals)) if vals else 0.0

In [ ]:

import pandas as pd
import numpy as np

climate = pd.read_csv(
    "data/processed/climate_monthly_clean.csv",
    parse_dates=["date"]
)

# Derive calendar month
climate["month"] = climate["date"].dt.month

# Choose a reference period with sufficient historical coverage.
# This example uses 2015–2024 because the dataset begins in 2015.
baseline = climate[
    climate["date"].dt.year.between(2015, 2024)
].copy()

# Calculate each country's typical value for each calendar month
monthly_baseline = (
    baseline
    .groupby(["iso3", "month"], as_index=False)
    .agg(
        temp_baseline_c=("temperature_c", "mean"),
        precip_baseline_mm=("precipitation_mm", "mean"),
        temp_baseline_n=("temperature_c", "count"),
        precip_baseline_n=("precipitation_mm", "count")
    )
)

# Join the historical baselines to the observations
climate = climate.merge(
    monthly_baseline,
    on=["iso3", "month"],
    how="left",
    validate="many_to_one"
)

# Absolute temperature anomaly, in degrees Celsius
climate["temp_anomaly_c"] = (
    climate["temperature_c"]
    - climate["temp_baseline_c"]
)

# Percentage precipitation anomaly
# Suppress percentages when the baseline is zero or unavailable.
climate["precip_anomaly_pct"] = np.where(
    climate["precip_baseline_mm"] > 0,
    (
        (
            climate["precipitation_mm"]
            - climate["precip_baseline_mm"]
        )
        / climate["precip_baseline_mm"]
    ) * 100,
    np.nan
)

# Do not claim an anomaly where the historical reference
# has insufficient observations.
climate.loc[
    climate["temp_baseline_n"] < 5,
    "temp_anomaly_c"
] = np.nan

climate.loc[
    climate["precip_baseline_n"] < 5,
    "precip_anomaly_pct"
] = np.nan

print("Temperature anomaly summary:")
display(climate["temp_anomaly_c"].describe())

print("\nPrecipitation anomaly summary:")
display(climate["precip_anomaly_pct"].describe())

print("\nSample records:")
display(
    climate[
        [
            "country",
            "date",
            "temperature_c",
            "temp_baseline_c",
            "temp_anomaly_c",
            "precipitation_mm",
            "precip_baseline_mm",
            "precip_anomaly_pct"
        ]
    ].tail(15)
)

climate.to_csv(
    "data/processed/climate_anomalies.csv",
    index=False
)

print("\nSaved climate anomaly dataset.")

Temperature anomaly summary:

count    2940.000000
mean        0.095262
std         0.851148
min        -3.620000
25%        -0.362000
50%         0.020000
75%         0.520500
max         4.222000
Name: temp_anomaly_c, dtype: float64

Precipitation anomaly summary:

count    2836.000000
mean        2.662558
std       161.682570
min      -100.000000
25%       -60.423322
50%       -18.014797
75%        20.951214
max      4900.000000
Name: precip_anomaly_pct, dtype: float64

Sample records:

,country,date,temperature_c,temp_baseline_c,temp_anomaly_c,precipitation_mm,precip_baseline_mm,precip_anomaly_pct
2967,Uganda,2025-08-01,22.13,22.346,-0.216,2.61,2.135,22.248244
2968,Uganda,2025-09-01,23.76,22.510,1.250,2.05,4.434,-53.766351
2969,Uganda,2025-10-01,22.63,22.059,0.571,4.34,6.291,-31.012558
2970,Uganda,2025-11-01,22.70,21.746,0.954,4.95,7.363,-32.771968
2971,Uganda,2025-12-01,23.51,22.448,1.062,2.03,3.910,-48.081841
2972,Uganda,2026-01-01,24.69,23.096,1.594,1.97,1.943,1.389604
2973,Uganda,2026-02-01,23.39,24.075,-0.685,4.82,2.401,100.749688
2974,Uganda,2026-03-01,22.94,23.484,-0.544,5.62,5.283,6.378951
2975,Uganda,2026-04-01,23.04,22.081,0.959,5.24,6.639,-21.072451
2976,Uganda,2026-05-01,22.62,21.613,1.007,4.96,4.910,1.018330
2977,Uganda,2026-06-01,23.02,21.332,1.688,1.53,2.322,-34.108527
2978,Uganda,2026-07-01,23.43,21.428,2.002,2.20,1.291,70.410534
2979,Uganda,2026-08-01,24.12,22.346,1.774,1.26,2.135,-40.983607
2980,Uganda,2026-09-01,NaN,22.510,NaN,NaN,4.434,NaN
2981,Uganda,2026-10-01,NaN,22.059,NaN,NaN,6.291,NaN

Saved climate anomaly dataset.

In [ ]:

from pathlib import Path
import pandas as pd

# Inspect the cleaned climate data and calculated anomalies
for file in [
    "data/processed/climate_monthly_clean.csv",
    "data/processed/climate_anomalies.csv"
]:
    path = Path(file)
    print(f"\n{'=' * 60}\nFile: {file}")
    print("Exists:", path.exists())

    if path.exists():
        df = pd.read_csv(path)
        print("Shape:", df.shape)
        print("Columns:", df.columns.tolist())
        display(df.head(3))

============================================================
File: data/processed/climate_monthly_clean.csv
Exists: True
Shape: (2982, 5)
Columns: ['country', 'iso3', 'date', 'temperature_c', 'precipitation_mm']

        country iso3        date  temperature_c  precipitation_mm
0  Burkina Faso  BFA  2015-01-01          21.99              0.00
1  Burkina Faso  BFA  2015-02-01          27.28              0.17
2  Burkina Faso  BFA  2015-03-01          28.93              0.41

============================================================
File: data/processed/climate_anomalies.csv
Exists: True
Shape: (2982, 12)
Columns: ['country', 'iso3', 'date', 'temperature_c', 'precipitation_mm', 'month', 'temp_baseline_c', 'precip_baseline_mm', 'temp_baseline_n', 'precip_baseline_n', 'temp_anomaly_c', 'precip_anomaly_pct']

,country,iso3,date,temperature_c,precipitation_mm,month,temp_baseline_c,precip_baseline_mm,temp_baseline_n,precip_baseline_n,temp_anomaly_c,precip_anomaly_pct
0,Burkina Faso,BFA,2015-01-01,21.99,0.00,1,22.467,0.000,10,10,-0.477,NaN
1,Burkina Faso,BFA,2015-02-01,27.28,0.17,2,25.861,0.050,10,10,1.419,240.000000
2,Burkina Faso,BFA,2015-03-01,28.93,0.41,3,30.434,0.156,10,10,-1.504,162.820513

In [ ]:

import numpy as np
import pandas as pd
from pathlib import Path

# Load the climate anomalies calculated in Step 3
climate = pd.read_csv("data/processed/climate_anomalies.csv")

def calculate_climate_component(row):
    """
    Calculate a bounded, exploratory climate signal from available
    temperature and precipitation anomalies.

    This is a portfolio screening heuristic, not a validated
    disease-outbreak prediction model.
    """
    signals = []

    # Temperature anomaly: absolute deviation in degrees Celsius
    temp = row["temp_anomaly_c"]

    if pd.notna(temp):
        signals.append(float(np.clip(abs(temp) / 3.0, 0, 1)))

    # Precipitation anomaly: percentage deviation from baseline
    precip = row["precip_anomaly_pct"]

    if pd.notna(precip):
        signals.append(float(np.clip(abs(precip) / 100.0, 0, 1)))

    # Do not interpret missing climate observations as zero risk
    if not signals:
        return np.nan

    return float(np.mean(signals))


# Calculate the climate component for each country-month
climate["climate_component"] = climate.apply(
    calculate_climate_component,
    axis=1
)

# Validate the calculation
print("Climate component calculated.")
print("Total records:", len(climate))
print("Missing climate components:", climate["climate_component"].isna().sum())

display(
    climate[
        [
            "country",
            "date",
            "temp_anomaly_c",
            "precip_anomaly_pct",
            "climate_component"
        ]
    ].head(15)
)

# Inspect the distribution
display(climate["climate_component"].describe())

# Save the validated intermediate output
output_path = Path("data/processed/climate_anomalies.csv")
climate.to_csv(output_path, index=False)

print(f"Updated file saved to: {output_path}")

Climate component calculated.
Total records: 2982
Missing climate components: 42

,country,date,temp_anomaly_c,precip_anomaly_pct,climate_component
0,Burkina Faso,2015-01-01,-0.477,NaN,0.159000
1,Burkina Faso,2015-02-01,1.419,240.000000,0.736500
2,Burkina Faso,2015-03-01,-1.504,162.820513,0.750667
3,Burkina Faso,2015-04-01,-1.464,-98.313659,0.735568
4,Burkina Faso,2015-05-01,1.364,-70.173317,0.578200
5,Burkina Faso,2015-06-01,0.581,15.107914,0.172373
6,Burkina Faso,2015-07-01,0.858,12.798584,0.206993
7,Burkina Faso,2015-08-01,-0.226,19.006479,0.132699
8,Burkina Faso,2015-09-01,0.016,0.367840,0.004506
9,Burkina Faso,2015-10-01,0.447,15.697674,0.152988
10,Burkina Faso,2015-11-01,-0.908,584.210526,0.651333
11,Burkina Faso,2015-12-01,-3.247,NaN,1.000000
12,Burkina Faso,2016-01-01,-1.727,NaN,0.575667
13,Burkina Faso,2016-02-01,-2.131,-100.000000,0.855167
14,Burkina Faso,2016-03-01,-0.014,2.564103,0.015154

count    2940.000000
mean        0.350022
std         0.214039
min         0.003885
25%         0.166658
50%         0.318981
75%         0.516498
max         1.000000
Name: climate_component, dtype: float64

Updated file saved to: data/processed/climate_anomalies.csv

In [ ]:

from pathlib import Path

files_to_inspect = [
    "src/pipeline.py",
    "src/risk_engine.py",
    "tests/test_risk.py",
]

for filename in files_to_inspect:
    path = Path(filename)

    print(f"\n{'=' * 70}")
    print(f"FILE: {filename}")
    print(f"{'=' * 70}")

    if path.exists():
        print(path.read_text())
    else:
        print("FILE NOT FOUND")

======================================================================
FILE: src/pipeline.py
======================================================================
from pathlib import Path
import json
import re
import numpy as np
import pandas as pd
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from .risk_engine import robust_anomaly, trend_score, vaccination_gap, climate_signal, risk_score, risk_tier, explain

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw"
OUT = ROOT / "data" / "processed"
OUT.mkdir(parents=True, exist_ok=True)

AFRO_COUNTRIES = set(pd.read_csv(ROOT / "config" / "countries.csv")["country"])

def read_owid(name):
    p = RAW / f"{name}.csv"
    if not p.exists():
        raise FileNotFoundError(f"{p} missing. Run: python scripts/download_data.py")
    df = pd.read_csv(p)
    # OWID standard columns are Entity, Code, Year, plus one value column.
    value = [c for c in df.columns if c not in {"Entity", "Code", "Year"}][0]
    return df.rename(columns={"Entity":"country", "Code":"iso3", "Year":"year", value:"value"})[
        ["country","iso3","year","value"]
    ]

def prepare_disease(name, disease):
    df = read_owid(name)
    df["disease"] = disease
    return df[df["country"].isin(AFRO_COUNTRIES)].copy()

def outbreak_signals():
    p = RAW / "who_disease_outbreak_news.json"
    if not p.exists():
        return pd.DataFrame(columns=["title","publication_date","text","event_signal"])
    payload = json.loads(p.read_text())
    if isinstance(payload, dict):
        items = payload.get("value") or payload.get("items") or []
    else:
        items = payload
    rows = []
    diseases = r"cholera|measles|malaria|mpox|monkeypox|ebola|marburg|yellow fever|meningitis|polio|lassa|dengue|rift valley"
    for x in items:
        title = str(x.get("Title") or x.get("title") or "")
        summary = str(x.get("Summary") or x.get("summary") or x.get("Overview") or "")
        text = f"{title} {summary}"
        if not re.search(diseases, text, flags=re.I):
            continue
        rows.append({
            "title": title,
            "publication_date": x.get("PublicationDate") or x.get("publicationDate"),
            "text": text,
            "event_signal": 1.0
        })
    return pd.DataFrame(rows)

def latest_climate():
    p = RAW / "nasa_climate_monthly.csv"
    if not p.exists():
        return pd.DataFrame()
    df = pd.read_csv(p)
    df["date"] = pd.to_datetime(df["date"], format="%Y%m", errors="coerce")
    df["year"] = df["date"].dt.year
    df["month"] = df["date"].dt.month
    # Compare latest year with the historical mean for each country/month.
    baseline = (
        df[df["year"] < df["year"].max()]
        .groupby(["iso3","month"])[["temperature_c","precipitation_mm"]]
        .mean()
        .reset_index()
        .rename(columns={"temperature_c":"temp_baseline","precipitation_mm":"precip_baseline"})
    )
    latest_year = df["year"].max()
    recent = df[df["year"] == latest_year].groupby(["iso3"])[["temperature_c","precipitation_mm"]].mean().reset_index()
    base = baseline.groupby("iso3")[["temp_baseline","precip_baseline"]].mean().reset_index()
    out = recent.merge(base, on="iso3", how="left")
    out["temp_anomaly"] = out["temperature_c"] - out["temp_baseline"]
    out["precip_anomaly_pct"] = 100 * (out["precipitation_mm"] - out["precip_baseline"]) / out["precip_baseline"].replace(0, np.nan)
    return out

def forecast(series):
    s = pd.Series(series, dtype="float64").dropna()
    if len(s) < 6:
        return np.nan
    try:
        model = ExponentialSmoothing(s, trend="add", damped_trend=True, initialization_method="estimated").fit(optimized=True)
        return float(model.forecast(1).iloc[0])
    except Exception:
        return float(s.tail(3).mean())

def build():
    diseases = {
        "malaria_incidence": ("malaria_incidence", "Malaria"),
        "measles_cases": ("measles_cases", "Measles"),
        "cholera_cases": ("cholera_cases", "Cholera"),
    }
    all_disease = []
    for source, (file_name, disease) in diseases.items():
        all_disease.append(prepare_disease(file_name, disease))
    disease_df = pd.concat(all_disease, ignore_index=True)

    # Add vaccination coverage as context.
    vax = read_owid("measles_vax").rename(columns={"value":"measles_vax_pct"})
    disease_df = disease_df.merge(vax[["country","year","measles_vax_pct"]], on=["country","year"], how="left")

    results = []
    for (country, disease), g in disease_df.groupby(["country","disease"]):
        g = g.sort_values("year").copy()
        g["anomaly_score"] = robust_anomaly(g["value"])
        latest = g.iloc[-1]
        fc = forecast(g["value"])
        prev = float(g["value"].iloc[-2]) if len(g) >= 2 else np.nan
        forecast_up = 1.0 if pd.notna(fc) and pd.notna(prev) and fc > prev * 1.05 else 0.0
        tr = trend_score(g["value"])
        vax = float(latest["measles_vax_pct"]) if disease == "Measles" and pd.notna(latest["measles_vax_pct"]) else np.nan

        results.append({
            "country": country,
            "iso3": latest["iso3"],
            "disease": disease,
            "latest_year": int(latest["year"]),
            "latest_value": float(latest["value"]),
            "anomaly_score": float(latest["anomaly_score"]),
            "trend_component": tr,
            "forecast_value": fc,
            "forecast_component": forecast_up,
            "measles_vax_pct": vax,
            "vax_gap_component": vaccination_gap(vax),
        })

    risk = pd.DataFrame(results)
    climate = latest_climate()
    if not climate.empty:
        risk = risk.merge(climate[["iso3","temp_anomaly","precip_anomaly_pct"]], on="iso3", how="left")
    else:
        risk["temp_anomaly"] = np.nan
        risk["precip_anomaly_pct"] = np.nan

    risk["climate_component"] = risk.apply(
        lambda r: climate_signal(r["temp_anomaly"], r["precip_anomaly_pct"]), axis=1
    )

    events = outbreak_signals()
    event_count = len(events)
    # For MVP, event intelligence is a region-level signal. A future version should
    # extract country/disease entities using NER and join them at country-disease level.
    risk["event_component"] = 1.0 if event_count else 0.0

    risk["risk_score"] = risk.apply(lambda r: risk_score(
        r["anomaly_score"], r["trend_component"], r["forecast_component"],
        r["vax_gap_component"], r["climate_component"], r["event_component"]
    ), axis=1)
    risk["risk_tier"] = risk["risk_score"].map(risk_tier)
    risk["explanation"] = risk.apply(explain, axis=1)

    risk = risk.sort_values("risk_score", ascending=False)
    risk.to_csv(OUT / "risk_register.csv", index=False)
    disease_df.to_csv(OUT / "disease_surveillance.csv", index=False)
    events.to_csv(OUT / "event_signals.csv", index=False)

    # Forecast table
    forecasts = risk[["country","iso3","disease","latest_year","latest_value","forecast_value"]].copy()
    forecasts.to_csv(OUT / "forecasts.csv", index=False)

    print(f"Built {len(risk):,} country-disease risk records.")
    print(risk.head(15).to_string(index=False))
    return risk

if __name__ == "__main__":
    build()


======================================================================
FILE: src/risk_engine.py
======================================================================
import numpy as np
import pandas as pd

RISK_BANDS = [
    (0, 25, "Low"),
    (25, 50, "Moderate"),
    (50, 75, "High"),
    (75, 101, "Critical"),
]

def robust_anomaly(series, window=5):
    """Robust rolling anomaly using median absolute deviation."""
    s = pd.Series(series, dtype="float64")
    med = s.rolling(window, min_periods=3).median()
    mad = (s - med).abs().rolling(window, min_periods=3).median()
    score = (s - med).abs() / (1.4826 * mad.replace(0, np.nan))
    return score.replace([np.inf, -np.inf], np.nan).fillna(0)

def trend_score(series, periods=3):
    """Score recent upward movement relative to a recent baseline."""
    s = pd.Series(series, dtype="float64").dropna()
    if len(s) < periods + 2:
        return 0.0
    recent = s.tail(periods).mean()
    baseline = s.iloc[-periods-3:-periods].mean() if len(s) >= periods + 3 else s.iloc[:-periods].mean()
    if baseline <= 0 or pd.isna(baseline):
        return 0.0
    pct = (recent - baseline) / baseline
    return float(np.clip((pct + 0.25) / 0.75, 0, 1))

def vaccination_gap(vax_percent):
    if pd.isna(vax_percent):
        return 0.0
    return float(np.clip((95 - vax_percent) / 50, 0, 1))

def climate_signal(temp_anomaly=None, precip_anomaly=None):
    vals = []
    if pd.notna(temp_anomaly):
        vals.append(np.clip(abs(temp_anomaly) / 3, 0, 1))
    if pd.notna(precip_anomaly):
        vals.append(np.clip(abs(precip_anomaly) / 100, 0, 1))
    return float(np.mean(vals)) if vals else 0.0

def risk_score(anomaly, trend, forecast_up, vax_gap, climate, event_signal):
    """
    Explainable heuristic. Weights are portfolio-demo weights, not WHO weights.
    """
    score = (
        0.30 * np.clip(anomaly / 4, 0, 1)
        + 0.20 * trend
        + 0.15 * forecast_up
        + 0.15 * vax_gap
        + 0.10 * climate
        + 0.10 * event_signal
    ) * 100
    return round(float(np.clip(score, 0, 100)), 1)

def risk_tier(score):
    for lo, hi, label in RISK_BANDS:
        if lo <= score < hi:
            return label
    return "Critical"

def explain(row):
    reasons = []
    if row.get("anomaly_score", 0) >= 2:
        reasons.append("recent surveillance anomaly")
    if row.get("trend_component", 0) >= 0.6:
        reasons.append("rising recent trend")
    if row.get("forecast_component", 0) >= 0.6:
        reasons.append("forecast points upward")
    if row.get("vax_gap_component", 0) >= 0.5:
        reasons.append("immunization gap")
    if row.get("climate_component", 0) >= 0.5:
        reasons.append("unusual climate conditions")
    if row.get("event_component", 0) >= 0.5:
        reasons.append("recent outbreak intelligence signal")
    return "; ".join(reasons) if reasons else "no strong converging signal"


======================================================================
FILE: tests/test_risk.py
======================================================================
import pandas as pd
from src.risk_engine import risk_score, risk_tier, vaccination_gap

def test_risk_score_bounds():
    assert 0 <= risk_score(10, 1, 1, 1, 1, 1) <= 100

def test_risk_tiers():
    assert risk_tier(10) == "Low"
    assert risk_tier(40) == "Moderate"
    assert risk_tier(60) == "High"
    assert risk_tier(90) == "Critical"

def test_vaccination_gap():
    assert vaccination_gap(95) == 0
    assert vaccination_gap(45) == 1

In [ ]:

from pathlib import Path

path = Path("src/pipeline.py")
source = path.read_text()

start = source.find("def latest_climate():")
end = source.find("def forecast(", start)

print("Found latest_climate():", start != -1)
print("Found forecast():", end != -1)

if start != -1:
    print("\n--- Existing climate function ---")
    print(source[start:end] if end != -1 else source[start:start + 4000])
else:
    print("\n--- Function names containing 'climate' ---")
    for line in source.splitlines():
        if "climate" in line.lower() or line.startswith("def "):
            print(line)

Found latest_climate(): True
Found forecast(): True

--- Existing climate function ---
def latest_climate():
    p = RAW / "nasa_climate_monthly.csv"
    if not p.exists():
        return pd.DataFrame()
    df = pd.read_csv(p)
    df["date"] = pd.to_datetime(df["date"], format="%Y%m", errors="coerce")
    df["year"] = df["date"].dt.year
    df["month"] = df["date"].dt.month
    # Compare latest year with the historical mean for each country/month.
    baseline = (
        df[df["year"] < df["year"].max()]
        .groupby(["iso3","month"])[["temperature_c","precipitation_mm"]]
        .mean()
        .reset_index()
        .rename(columns={"temperature_c":"temp_baseline","precipitation_mm":"precip_baseline"})
    )
    latest_year = df["year"].max()
    recent = df[df["year"] == latest_year].groupby(["iso3"])[["temperature_c","precipitation_mm"]].mean().reset_index()
    base = baseline.groupby("iso3")[["temp_baseline","precip_baseline"]].mean().reset_index()
    out = recent.merge(base, on="iso3", how="left")
    out["temp_anomaly"] = out["temperature_c"] - out["temp_baseline"]
    out["precip_anomaly_pct"] = 100 * (out["precipitation_mm"] - out["precip_baseline"]) / out["precip_baseline"].replace(0, np.nan)
    return out

In [ ]:

from pathlib import Path
import pandas as pd

pipeline_path = Path("src/pipeline.py")
source = pipeline_path.read_text()

start = source.find("def latest_climate():")
end = source.find("def forecast(", start)

if start == -1 or end == -1 or end <= start:
    raise RuntimeError(
        "Could not identify the climate function boundaries. "
        "No changes were made."
    )

new_function = '''def latest_climate():
    """
    Load the cleaned climate anomalies generated in the preprocessing step.
    Return the latest available monthly record for each country.
    """
    p = OUT / "climate_anomalies.csv"

    if not p.exists():
        return pd.DataFrame(columns=[
            "iso3", "date", "temp_anomaly",
            "precip_anomaly_pct", "climate_component"
        ])

    df = pd.read_csv(p)

    required = {
        "iso3",
        "date",
        "temp_anomaly_c",
        "precip_anomaly_pct",
        "climate_component",
    }

    missing = required.difference(df.columns)
    if missing:
        raise ValueError(
            f"Climate anomalies file is missing columns: {sorted(missing)}"
        )

    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    df = df.dropna(subset=["iso3", "date"]).copy()

    df["climate_component"] = pd.to_numeric(
        df["climate_component"], errors="coerce"
    )

    invalid = (
        df["climate_component"].notna()
        & ~df["climate_component"].between(0, 1)
    )

    if invalid.any():
        raise ValueError(
            "Climate component values must be between 0 and 1."
        )

    duplicates = df.duplicated(["iso3", "date"], keep=False)

    if duplicates.any():
        sample = df.loc[duplicates, ["iso3", "date"]].head(10)
        raise ValueError(
            "Duplicate country-month records found. Investigate them "
            "before continuing:\\\\n"
            + sample.to_string(index=False)
        )

    df = df.sort_values("date")
    latest = df.groupby("iso3", as_index=False).tail(1).copy()

    latest = latest.rename(columns={
        "temp_anomaly_c": "temp_anomaly"
    })

    return latest[
        [
            "iso3",
            "date",
            "temp_anomaly",
            "precip_anomaly_pct",
            "climate_component",
        ]
    ].copy()


'''

updated_source = source[:start] + new_function + source[end:]
pipeline_path.write_text(updated_source)

print("Successfully replaced latest_climate() in src/pipeline.py")

Successfully replaced latest_climate() in src/pipeline.py

In [ ]:

from pathlib import Path

source = Path("src/pipeline.py").read_text()

start = source.find("def latest_climate():")
end = source.find("def forecast(", start)

print(source[start:end])

def latest_climate():
    """
    Load the cleaned climate anomalies generated in the preprocessing step.
    Return the latest available monthly record for each country.
    """
    p = OUT / "climate_anomalies.csv"

    if not p.exists():
        return pd.DataFrame(columns=[
            "iso3", "date", "temp_anomaly",
            "precip_anomaly_pct", "climate_component"
        ])

    df = pd.read_csv(p)

    required = {
        "iso3",
        "date",
        "temp_anomaly_c",
        "precip_anomaly_pct",
        "climate_component",
    }

    missing = required.difference(df.columns)
    if missing:
        raise ValueError(
            f"Climate anomalies file is missing columns: {sorted(missing)}"
        )

    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    df = df.dropna(subset=["iso3", "date"]).copy()

    df["climate_component"] = pd.to_numeric(
        df["climate_component"], errors="coerce"
    )

    invalid = (
        df["climate_component"].notna()
        & ~df["climate_component"].between(0, 1)
    )

    if invalid.any():
        raise ValueError(
            "Climate component values must be between 0 and 1."
        )

    duplicates = df.duplicated(["iso3", "date"], keep=False)

    if duplicates.any():
        sample = df.loc[duplicates, ["iso3", "date"]].head(10)
        raise ValueError(
            "Duplicate country-month records found. Investigate them "
            "before continuing:\\n"
            + sample.to_string(index=False)
        )

    df = df.sort_values("date")
    latest = df.groupby("iso3", as_index=False).tail(1).copy()

    latest = latest.rename(columns={
        "temp_anomaly_c": "temp_anomaly"
    })

    return latest[
        [
            "iso3",
            "date",
            "temp_anomaly",
            "precip_anomaly_pct",
            "climate_component",
        ]
    ].copy()

In [ ]:

from pathlib import Path
import ast

path = Path("src/pipeline.py")
source = path.read_text()

# 1. Check that pipeline.py is valid Python
try:
    ast.parse(source)
    print("PASS: src/pipeline.py has valid Python syntax.")
except SyntaxError as e:
    print("FAIL: Syntax error:", e)
    raise

# 2. Display the complete latest_climate() function
start = source.find("def latest_climate():")
end = source.find("\ndef forecast(", start)

if start == -1 or end == -1:
    raise RuntimeError("Could not locate the climate function boundaries.")

print("\n--- COMPLETE latest_climate() ---")
print(source[start:end])

# 3. Inspect the section where climate data joins the risk register
merge_start = source.find("    risk = pd.DataFrame(results)")
merge_end = source.find("    events = outbreak_signals()", merge_start)

if merge_start == -1 or merge_end == -1:
    raise RuntimeError("Could not locate the climate merge section.")

print("\n--- CLIMATE MERGE SECTION (not modified) ---")
print(source[merge_start:merge_end])

PASS: src/pipeline.py has valid Python syntax.

--- COMPLETE latest_climate() ---
def latest_climate():
    """
    Load the cleaned climate anomalies generated in the preprocessing step.
    Return the latest available monthly record for each country.
    """
    p = OUT / "climate_anomalies.csv"

    if not p.exists():
        return pd.DataFrame(columns=[
            "iso3", "date", "temp_anomaly",
            "precip_anomaly_pct", "climate_component"
        ])

    df = pd.read_csv(p)

    required = {
        "iso3",
        "date",
        "temp_anomaly_c",
        "precip_anomaly_pct",
        "climate_component",
    }

    missing = required.difference(df.columns)
    if missing:
        raise ValueError(
            f"Climate anomalies file is missing columns: {sorted(missing)}"
        )

    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    df = df.dropna(subset=["iso3", "date"]).copy()

    df["climate_component"] = pd.to_numeric(
        df["climate_component"], errors="coerce"
    )

    invalid = (
        df["climate_component"].notna()
        & ~df["climate_component"].between(0, 1)
    )

    if invalid.any():
        raise ValueError(
            "Climate component values must be between 0 and 1."
        )

    duplicates = df.duplicated(["iso3", "date"], keep=False)

    if duplicates.any():
        sample = df.loc[duplicates, ["iso3", "date"]].head(10)
        raise ValueError(
            "Duplicate country-month records found. Investigate them "
            "before continuing:\\n"
            + sample.to_string(index=False)
        )

    df = df.sort_values("date")
    latest = df.groupby("iso3", as_index=False).tail(1).copy()

    latest = latest.rename(columns={
        "temp_anomaly_c": "temp_anomaly"
    })

    return latest[
        [
            "iso3",
            "date",
            "temp_anomaly",
            "precip_anomaly_pct",
            "climate_component",
        ]
    ].copy()



--- CLIMATE MERGE SECTION (not modified) ---
    risk = pd.DataFrame(results)
    climate = latest_climate()
    if not climate.empty:
        risk = risk.merge(climate[["iso3","temp_anomaly","precip_anomaly_pct"]], on="iso3", how="left")
    else:
        risk["temp_anomaly"] = np.nan
        risk["precip_anomaly_pct"] = np.nan

    risk["climate_component"] = risk.apply(
        lambda r: climate_signal(r["temp_anomaly"], r["precip_anomaly_pct"]), axis=1
    )

In [ ]:

from pathlib import Path

path = Path("src/pipeline.py")
source = path.read_text()

old_block = '''    risk = pd.DataFrame(results)
    climate = latest_climate()
    if not climate.empty:
        risk = risk.merge(climate[["iso3","temp_anomaly","precip_anomaly_pct"]], on="iso3", how="left")
    else:
        risk["temp_anomaly"] = np.nan
        risk["precip_anomaly_pct"] = np.nan

    risk["climate_component"] = risk.apply(
        lambda r: climate_signal(r["temp_anomaly"], r["precip_anomaly_pct"]), axis=1
    )
'''

new_block = '''    risk = pd.DataFrame(results)
    climate = latest_climate()

    if not climate.empty:
        risk = risk.merge(
            climate[
                [
                    "iso3",
                    "date",
                    "temp_anomaly",
                    "precip_anomaly_pct",
                    "climate_component",
                ]
            ],
            on="iso3",
            how="left",
            validate="many_to_one",
        )
        risk = risk.rename(columns={"date": "climate_observation_date"})
    else:
        risk["climate_observation_date"] = pd.NaT
        risk["temp_anomaly"] = np.nan
        risk["precip_anomaly_pct"] = np.nan
        risk["climate_component"] = np.nan
'''

if old_block not in source:
    raise RuntimeError(
        "The expected climate integration block was not found. "
        "No changes were made."
    )

path.write_text(source.replace(old_block, new_block, 1))

print("PASS: Climate integration section updated.")
print("The pipeline will now use the saved climate_component.")

PASS: Climate integration section updated.
The pipeline will now use the saved climate_component.

In [ ]:

from pathlib import Path
import ast

path = Path("src/pipeline.py")
source = path.read_text()

ast.parse(source)
print("PASS: pipeline.py syntax is valid.")

start = source.find("    risk = pd.DataFrame(results)")
end = source.find("    events = outbreak_signals()", start)

print("\n--- UPDATED CLIMATE INTEGRATION ---")
print(source[start:end])

PASS: pipeline.py syntax is valid.

--- UPDATED CLIMATE INTEGRATION ---
    risk = pd.DataFrame(results)
    climate = latest_climate()

    if not climate.empty:
        risk = risk.merge(
            climate[
                [
                    "iso3",
                    "date",
                    "temp_anomaly",
                    "precip_anomaly_pct",
                    "climate_component",
                ]
            ],
            on="iso3",
            how="left",
            validate="many_to_one",
        )
        risk = risk.rename(columns={"date": "climate_observation_date"})
    else:
        risk["climate_observation_date"] = pd.NaT
        risk["temp_anomaly"] = np.nan
        risk["precip_anomaly_pct"] = np.nan
        risk["climate_component"] = np.nan

In [ ]:

from pathlib import Path
import ast

source = Path("src/pipeline.py").read_text()
ast.parse(source)

start = source.find("    risk = pd.DataFrame(results)")
end = source.find("    events = outbreak_signals()", start)

assert start != -1 and end != -1 and end > start, (
    "Could not locate the complete climate integration block."
)

block = source[start:end]
print(block)

assert '"climate_component"' in block
assert 'lambda r: climate_signal' not in block

print("\nPASS: The pipeline merges the saved climate component.")
print("PASS: The old climate-component recalculation is absent.")

    risk = pd.DataFrame(results)
    climate = latest_climate()

    if not climate.empty:
        risk = risk.merge(
            climate[
                [
                    "iso3",
                    "date",
                    "temp_anomaly",
                    "precip_anomaly_pct",
                    "climate_component",
                ]
            ],
            on="iso3",
            how="left",
            validate="many_to_one",
        )
        risk = risk.rename(columns={"date": "climate_observation_date"})
    else:
        risk["climate_observation_date"] = pd.NaT
        risk["temp_anomaly"] = np.nan
        risk["precip_anomaly_pct"] = np.nan
        risk["climate_component"] = np.nan



PASS: The pipeline merges the saved climate component.
PASS: The old climate-component recalculation is absent.

In [ ]:

from pathlib import Path

source = Path("src/risk_engine.py").read_text()
print(source)

import numpy as np
import pandas as pd

RISK_BANDS = [
    (0, 25, "Low"),
    (25, 50, "Moderate"),
    (50, 75, "High"),
    (75, 101, "Critical"),
]

def robust_anomaly(series, window=5):
    """Robust rolling anomaly using median absolute deviation."""
    s = pd.Series(series, dtype="float64")
    med = s.rolling(window, min_periods=3).median()
    mad = (s - med).abs().rolling(window, min_periods=3).median()
    score = (s - med).abs() / (1.4826 * mad.replace(0, np.nan))
    return score.replace([np.inf, -np.inf], np.nan).fillna(0)

def trend_score(series, periods=3):
    """Score recent upward movement relative to a recent baseline."""
    s = pd.Series(series, dtype="float64").dropna()
    if len(s) < periods + 2:
        return 0.0
    recent = s.tail(periods).mean()
    baseline = s.iloc[-periods-3:-periods].mean() if len(s) >= periods + 3 else s.iloc[:-periods].mean()
    if baseline <= 0 or pd.isna(baseline):
        return 0.0
    pct = (recent - baseline) / baseline
    return float(np.clip((pct + 0.25) / 0.75, 0, 1))

def vaccination_gap(vax_percent):
    if pd.isna(vax_percent):
        return 0.0
    return float(np.clip((95 - vax_percent) / 50, 0, 1))

def climate_signal(temp_anomaly=None, precip_anomaly=None):
    vals = []
    if pd.notna(temp_anomaly):
        vals.append(np.clip(abs(temp_anomaly) / 3, 0, 1))
    if pd.notna(precip_anomaly):
        vals.append(np.clip(abs(precip_anomaly) / 100, 0, 1))
    return float(np.mean(vals)) if vals else 0.0

def risk_score(anomaly, trend, forecast_up, vax_gap, climate, event_signal):
    """
    Explainable heuristic. Weights are portfolio-demo weights, not WHO weights.
    """
    score = (
        0.30 * np.clip(anomaly / 4, 0, 1)
        + 0.20 * trend
        + 0.15 * forecast_up
        + 0.15 * vax_gap
        + 0.10 * climate
        + 0.10 * event_signal
    ) * 100
    return round(float(np.clip(score, 0, 100)), 1)

def risk_tier(score):
    for lo, hi, label in RISK_BANDS:
        if lo <= score < hi:
            return label
    return "Critical"

def explain(row):
    reasons = []
    if row.get("anomaly_score", 0) >= 2:
        reasons.append("recent surveillance anomaly")
    if row.get("trend_component", 0) >= 0.6:
        reasons.append("rising recent trend")
    if row.get("forecast_component", 0) >= 0.6:
        reasons.append("forecast points upward")
    if row.get("vax_gap_component", 0) >= 0.5:
        reasons.append("immunization gap")
    if row.get("climate_component", 0) >= 0.5:
        reasons.append("unusual climate conditions")
    if row.get("event_component", 0) >= 0.5:
        reasons.append("recent outbreak intelligence signal")
    return "; ".join(reasons) if reasons else "no strong converging signal"

In [ ]:

from pathlib import Path
import ast

path = Path("src/risk_engine.py")
source = path.read_text()

def replace_function(source, function_name, replacement):
    tree = ast.parse(source)

    matches = [
        node for node in tree.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
        and node.name == function_name
    ]

    if len(matches) != 1:
        raise ValueError(
            f"Expected exactly one {function_name}() function; "
            f"found {len(matches)}."
        )

    node = matches[0]
    return (
        source[:node.col_offset + node.lineno * 0
               + sum(len(line) for line in source.splitlines(keepends=True)[:node.lineno - 1])]
        + replacement.rstrip() + "\n\n"
        + source[
            sum(len(line) for line in source.splitlines(keepends=True)[:node.end_lineno]):
        ]
    )

vaccination_function = '''def vaccination_gap(vax_percent):
    """Return a normalized vaccination gap, preserving missing values."""
    if pd.isna(vax_percent):
        return np.nan
    return float(np.clip((95 - vax_percent) / 50, 0, 1))'''

climate_function = '''def climate_signal(temp_anomaly=None, precip_anomaly=None):
    """Summarize available climate anomalies; preserve missing observations."""
    vals = []

    if pd.notna(temp_anomaly):
        vals.append(np.clip(abs(temp_anomaly) / 3, 0, 1))

    if pd.notna(precip_anomaly):
        vals.append(np.clip(abs(precip_anomaly) / 100, 0, 1))

    return float(np.mean(vals)) if vals else np.nan'''

updated = replace_function(source, "vaccination_gap", vaccination_function)
updated = replace_function(updated, "climate_signal", climate_function)

# Verify syntax before writing the file.
ast.parse(updated)

path.write_text(updated)
print("PASS: Updated vaccination_gap() and climate_signal().")
print("PASS: Python syntax is valid.")

PASS: Updated vaccination_gap() and climate_signal().
PASS: Python syntax is valid.

In [ ]:

import ast
import numpy as np
from pathlib import Path
from src.risk_engine import vaccination_gap, climate_signal

# 1. Verify syntax
source = Path("src/risk_engine.py").read_text()
ast.parse(source)
print("PASS: risk_engine.py syntax is valid.")

# 2. Verify vaccination-gap behavior
assert np.isnan(vaccination_gap(np.nan))
assert vaccination_gap(95) == 0.0
assert vaccination_gap(45) == 1.0
print("PASS: Vaccination gap handles missing and observed values.")

# 3. Verify climate-signal behavior
assert np.isnan(climate_signal())
assert np.isnan(climate_signal(np.nan, np.nan))
assert climate_signal(0, 0) == 0.0
assert climate_signal(3, 100) == 1.0
print("PASS: Climate signal handles missing and observed values.")

print("\nStep 6B verification complete.")

PASS: risk_engine.py syntax is valid.
PASS: Vaccination gap handles missing and observed values.
PASS: Climate signal handles missing and observed values.

Step 6B verification complete.

In [ ]:

from pathlib import Path
import ast
import numpy as np

path = Path("src/risk_engine.py")
source = path.read_text()

# Find the existing risk_score() function.
tree = ast.parse(source)

matches = [
    node for node in tree.body
    if isinstance(node, ast.FunctionDef)
    and node.name == "risk_score"
]

if len(matches) != 1:
    raise ValueError(
        f"Expected exactly one risk_score() function; found {len(matches)}."
    )

node = matches[0]

lines = source.splitlines(keepends=True)
start = sum(len(line) for line in lines[:node.lineno - 1])
end = sum(len(line) for line in lines[:node.end_lineno])

replacement = '''def risk_score(anomaly, trend, forecast_up, vax_gap, climate, event_signal):
    """
    Calculate an explainable screening score from available components.

    Missing components are excluded, and the remaining weights are
    renormalized. Weights are exploratory portfolio-demo choices,
    not validated public-health risk weights.
    """
    components = [
        (anomaly, 0.30, lambda value: value / 4),
        (trend, 0.20, lambda value: value),
        (forecast_up, 0.15, lambda value: value),
        (vax_gap, 0.15, lambda value: value),
        (climate, 0.10, lambda value: value),
        (event_signal, 0.10, lambda value: value),
    ]

    weighted_sum = 0.0
    available_weight = 0.0

    for value, weight, transform in components:
        if value is None:
            continue

        try:
            value = float(value)
        except (TypeError, ValueError):
            continue

        if not np.isfinite(value):
            continue

        normalized = float(np.clip(transform(value), 0, 1))

        weighted_sum += weight * normalized
        available_weight += weight

    if available_weight == 0:
        return np.nan

    score = 100 * weighted_sum / available_weight
    return round(float(np.clip(score, 0, 100)), 1)
'''

updated = source[:start] + replacement + source[end:]

# Validate the updated source before saving.
ast.parse(updated)
path.write_text(updated)

print("PASS: risk_score() updated.")
print("PASS: Python syntax is valid.")

PASS: risk_score() updated.
PASS: Python syntax is valid.

In [ ]:

import importlib
import numpy as np
import src.risk_engine as risk_engine

# Reload the module from the updated file.
importlib.reload(risk_engine)

# Test minimum and maximum scores.
assert risk_engine.risk_score(0, 0, 0, 0, 0, 0) == 0.0
assert risk_engine.risk_score(4, 1, 1, 1, 1, 1) == 100.0

# Test a missing climate component.
without_climate = risk_engine.risk_score(
    4, 1, 1, 1, np.nan, 1
)
print("Score with missing climate:", without_climate)

assert np.isfinite(without_climate)
assert 0 <= without_climate <= 100

# Test that all-missing components return NaN.
all_missing = risk_engine.risk_score(
    np.nan, np.nan, np.nan,
    np.nan, np.nan, np.nan
)
assert np.isnan(all_missing)

print("PASS: Minimum and maximum scores are correct.")
print("PASS: Missing climate data does not invalidate the score.")
print("PASS: All-missing components return NaN.")
print("Step 6D verification complete.")

Score with missing climate: 100.0
PASS: Minimum and maximum scores are correct.
PASS: Missing climate data does not invalidate the score.
PASS: All-missing components return NaN.
Step 6D verification complete.

In [ ]:
!python -m pytest -q

...                                                                      [100%]
3 passed in 0.77s

In [ ]:
!python -m src.pipeline

/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
Built 63 country-disease risk records.
                     country iso3 disease  latest_year  latest_value  anomaly_score  trend_component  forecast_value  forecast_component  measles_vax_pct  vax_gap_component climate_observation_date  temp_anomaly  precip_anomaly_pct  climate_component  event_component  risk_score risk_tier                                                                                                   explanation
                       Sudan  SDN Cholera         2024      53001.00       2.653367         1.000000    20635.000000                 1.0              NaN                NaN               2026-10-01           NaN                 NaN                NaN              1.0        86.5  Critical recent surveillance anomaly; rising recent trend; forecast points upward; recent outbreak intelligence signal
                    Ethiopia  ETH Malaria         2024        138.50       3.700050         1.000000      102.543333                 0.0              NaN                NaN               2026-10-01           NaN                 NaN                NaN              1.0        77.0  Critical                         recent surveillance anomaly; rising recent trend; recent outbreak intelligence signal
                        Chad  TCD Measles         2024       6978.00       4.163301         1.000000     6999.333333                 0.0             66.0               0.58               2026-10-01           NaN                 NaN                NaN              1.0        76.3  Critical       recent surveillance anomaly; rising recent trend; immunization gap; recent outbreak intelligence signal
                 South Sudan  SSD Cholera         2024      20132.00       2.759470         0.322883     7342.333333                 1.0              NaN                NaN               2026-10-01           NaN                 NaN                NaN              1.0        69.5      High                      recent surveillance anomaly; forecast points upward; recent outbreak intelligence signal
                      Uganda  UGA Measles         2024       2180.00       2.168354         0.906522      877.000000                 1.0             90.0               0.10               2026-10-01           NaN                 NaN                NaN              1.0        67.7      High recent surveillance anomaly; rising recent trend; forecast points upward; recent outbreak intelligence signal

In [ ]:

import pandas as pd
from pathlib import Path

path = Path("data/processed/climate_anomalies.csv")

if not path.exists():
    raise FileNotFoundError(f"Climate anomalies file not found: {path}")

climate = pd.read_csv(path)

print("SHAPE:", climate.shape)
print("\nCOLUMNS:")
print(climate.columns.tolist())

print("\nLATEST OBSERVATIONS:")
print(
    climate.sort_values("date")
    .groupby("iso3", group_keys=False)
    .tail(1)[
        [
            "country",
            "iso3",
            "date",
            "temp_anomaly_c",
            "precip_anomaly_pct",
            "climate_component",
        ]
    ]
    .head(15)
    .to_string(index=False)
)

print("\nMISSING-VALUE COUNTS:")
print(
    climate[
        [
            "temp_anomaly_c",
            "precip_anomaly_pct",
            "climate_component",
        ]
    ].isna().sum()
)

print("\nCOUNTRIES WITH NON-MISSING CLIMATE COMPONENTS:")
print(
    climate.groupby("iso3")["climate_component"]
    .apply(lambda s: s.notna().sum())
    .sort_values()
    .to_string()
)

SHAPE: (2982, 13)

COLUMNS:
['country', 'iso3', 'date', 'temperature_c', 'precipitation_mm', 'month', 'temp_baseline_c', 'precip_baseline_mm', 'temp_baseline_n', 'precip_baseline_n', 'temp_anomaly_c', 'precip_anomaly_pct', 'climate_component']

LATEST OBSERVATIONS:
                     country iso3       date  temp_anomaly_c  precip_anomaly_pct  climate_component
                     Nigeria  NGA 2026-10-01             NaN                 NaN                NaN
                       Kenya  KEN 2026-10-01             NaN                 NaN                NaN
                     Liberia  LBR 2026-10-01             NaN                 NaN                NaN
                       Niger  NER 2026-10-01             NaN                 NaN                NaN
                      Rwanda  RWA 2026-10-01             NaN                 NaN                NaN
                      Guinea  GIN 2026-10-01             NaN                 NaN                NaN
                    Tanzania  TZA 2026-10-01             NaN                 NaN                NaN
                     Senegal  SEN 2026-10-01             NaN                 NaN                NaN
                       Ghana  GHA 2026-10-01             NaN                 NaN                NaN
                    Ethiopia  ETH 2026-10-01             NaN                 NaN                NaN
                        Mali  MLI 2026-10-01             NaN                 NaN                NaN
                Sierra Leone  SLE 2026-10-01             NaN                 NaN                NaN
Democratic Republic of Congo  COD 2026-10-01             NaN                 NaN                NaN
                     Somalia  SOM 2026-10-01             NaN                 NaN                NaN
                    Cameroon  CMR 2026-10-01             NaN                 NaN                NaN

MISSING-VALUE COUNTS:
temp_anomaly_c         42
precip_anomaly_pct    146
climate_component      42
dtype: int64

COUNTRIES WITH NON-MISSING CLIMATE COMPONENTS:
iso3
BFA    140
CIV    140
CMR    140
COD    140
ETH    140
GHA    140
GIN    140
KEN    140
LBR    140
MLI    140
NER    140
NGA    140
RWA    140
SDN    140
SEN    140
SLE    140
SOM    140
SSD    140
TCD    140
TZA    140
UGA    140

In [ ]:

import pandas as pd

climate = pd.read_csv("data/processed/climate_anomalies.csv")
climate["date"] = pd.to_datetime(climate["date"], errors="coerce")

# Inspect the five most recent observations for Kenya.
kenya = (
    climate.loc[climate["iso3"] == "KEN"]
    .sort_values("date")
    .tail(5)
)

print("KENYA — FIVE MOST RECENT MONTHS")
print(
    kenya[
        [
            "date",
            "temperature_c",
            "precipitation_mm",
            "temp_anomaly_c",
            "precip_anomaly_pct",
            "climate_component",
        ]
    ].to_string(index=False)
)

# Find the latest usable climate-component observation for each country.
usable = climate.loc[
    climate["climate_component"].notna()
    & climate["climate_component"].between(0, 1)
].copy()

latest_usable = (
    usable.sort_values("date")
    .groupby("iso3", as_index=False)
    .tail(1)
    .sort_values("iso3")
)

print("\nLATEST USABLE OBSERVATION PER COUNTRY")
print(
    latest_usable[
        ["country", "iso3", "date", "climate_component"]
    ].head(15).to_string(index=False)
)

print("\nLatest date in source:", climate["date"].max())
print("Latest date with usable climate component:", usable["date"].max())
print("Countries with usable climate data:", latest_usable["iso3"].nunique())

KENYA — FIVE MOST RECENT MONTHS
      date  temperature_c  precipitation_mm  temp_anomaly_c  precip_anomaly_pct  climate_component
2026-06-01          19.75              0.18           0.730          -77.040816           0.506871
2026-07-01          20.13              0.49           1.263            4.477612           0.232888
2026-08-01          20.08              0.37           0.528           -5.852417           0.117262
2026-09-01            NaN               NaN             NaN                 NaN                NaN
2026-10-01            NaN               NaN             NaN                 NaN                NaN

LATEST USABLE OBSERVATION PER COUNTRY
                     country iso3       date  climate_component
                Burkina Faso  BFA 2026-08-01           0.305184
               Cote d'Ivoire  CIV 2026-08-01           0.336526
                    Cameroon  CMR 2026-08-01           0.362607
Democratic Republic of Congo  COD 2026-08-01           0.636105
                    Ethiopia  ETH 2026-08-01           0.174720
                       Ghana  GHA 2026-08-01           0.286459
                      Guinea  GIN 2026-08-01           0.682694
                       Kenya  KEN 2026-08-01           0.117262
                     Liberia  LBR 2026-08-01           0.869087
                        Mali  MLI 2026-08-01           0.398296
                       Niger  NER 2026-08-01           0.343850
                     Nigeria  NGA 2026-08-01           0.205028
                      Rwanda  RWA 2026-08-01           0.856029
                       Sudan  SDN 2026-08-01           0.514478
                     Senegal  SEN 2026-08-01           0.231671

Latest date in source: 2026-10-01 00:00:00
Latest date with usable climate component: 2026-08-01 00:00:00
Countries with usable climate data: 21

In [ ]:

from pathlib import Path
import ast

path = Path("src/pipeline.py")
source = path.read_text()

tree = ast.parse(source)

matches = [
    node for node in tree.body
    if isinstance(node, ast.FunctionDef)
    and node.name == "latest_climate"
]

if len(matches) != 1:
    raise ValueError(
        f"Expected exactly one latest_climate() function; found {len(matches)}."
    )

node = matches[0]
lines = source.splitlines(keepends=True)

start = sum(len(line) for line in lines[:node.lineno - 1])
end = sum(len(line) for line in lines[:node.end_lineno])

replacement = '''def latest_climate():
    """
    Load climate anomalies and select the latest usable observation
    for each country. Preserve missing data when no usable observation
    exists.
    """
    p = OUT / "climate_anomalies.csv"

    columns = [
        "iso3",
        "date",
        "temp_anomaly",
        "precip_anomaly_pct",
        "climate_component",
    ]

    if not p.exists():
        return pd.DataFrame(columns=columns)

    df = pd.read_csv(p)

    required = {
        "iso3",
        "date",
        "temp_anomaly_c",
        "precip_anomaly_pct",
        "climate_component",
    }

    missing = required.difference(df.columns)
    if missing:
        raise ValueError(
            f"Climate anomalies file is missing columns: {sorted(missing)}"
        )

    df["date"] = pd.to_datetime(df["date"], errors="coerce")

    for column in [
        "temp_anomaly_c",
        "precip_anomaly_pct",
        "climate_component",
    ]:
        df[column] = pd.to_numeric(df[column], errors="coerce")

    df = df.dropna(subset=["iso3", "date"]).copy()

    invalid = (
        df["climate_component"].notna()
        & ~df["climate_component"].between(0, 1)
    )

    if invalid.any():
        raise ValueError("Climate component values must be between 0 and 1.")

    duplicates = df.duplicated(["iso3", "date"], keep=False)
    if duplicates.any():
        sample = df.loc[duplicates, ["iso3", "date"]].head(10)
        raise ValueError(
            "Duplicate country-month records found. Investigate them "
            "before continuing:\\\\n" + sample.to_string(index=False)
        )

    # Exclude months with no usable climate component.
    usable = df.loc[df["climate_component"].notna()].copy()

    latest = (
        usable.sort_values("date")
        .groupby("iso3", as_index=False)
        .tail(1)
        .copy()
    )

    latest = latest.rename(
        columns={"temp_anomaly_c": "temp_anomaly"}
    )

    return latest[columns].copy()
'''

updated = source[:start] + replacement + source[end:]

# Verify syntax before writing.
ast.parse(updated)
path.write_text(updated)

print("PASS: latest_climate() now selects the latest usable observation.")
print("PASS: pipeline.py syntax is valid.")

PASS: latest_climate() now selects the latest usable observation.
PASS: pipeline.py syntax is valid.

In [ ]:

from src.pipeline import latest_climate

latest = latest_climate()

print("Selected climate records:", len(latest))
print("Countries represented:", latest["iso3"].nunique())
print("Missing climate components:", latest["climate_component"].isna().sum())
print("Latest selected observation:", latest["date"].max())

print("\nSelected observations:")
print(
    latest[
        ["iso3", "date", "temp_anomaly",
         "precip_anomaly_pct", "climate_component"]
    ]
    .sort_values("iso3")
    .head(15)
    .to_string(index=False)
)

assert latest["iso3"].is_unique
assert latest["climate_component"].notna().all()
assert latest["climate_component"].between(0, 1).all()

print("\nPASS: One usable climate observation per represented country.")

Selected climate records: 21
Countries represented: 21
Missing climate components: 0
Latest selected observation: 2026-08-01 00:00:00

Selected observations:
iso3       date  temp_anomaly  precip_anomaly_pct  climate_component
 BFA 2026-08-01         1.154          -22.570194           0.305184
 CIV 2026-08-01         0.612          -46.905251           0.336526
 CMR 2026-08-01         1.499          -22.554636           0.362607
 COD 2026-08-01         1.741          -69.187675           0.636105
 ETH 2026-08-01         0.911           -4.577429           0.174720
 GHA 2026-08-01         0.140           52.625153           0.286459
 GIN 2026-08-01         1.172          -97.472115           0.682694
 KEN 2026-08-01         0.528           -5.852417           0.117262
 LBR 2026-08-01         2.233          -99.383995           0.869087
 MLI 2026-08-01         1.501          -29.625847           0.398296
 NER 2026-08-01         1.448          -20.503289           0.343850
 NGA 2026-08-01         1.182            1.605652           0.205028
 RWA 2026-08-01         2.281          -95.172414           0.856029
 SDN 2026-08-01         3.722           -2.895584           0.514478
 SEN 2026-08-01         1.292           -3.267598           0.231671

PASS: One usable climate observation per represented country.

In [ ]:
!python -m src.pipeline

/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/base/tsa_model.py:480: ValueWarning: An unsupported index was provided. As a result, forecasts cannot be generated. To use the model for forecasting, use on the supported classes of index.
  self._init_dates(dates, freq)
Built 63 country-disease risk records.
                     country iso3 disease  latest_year  latest_value  anomaly_score  trend_component  forecast_value  forecast_component  measles_vax_pct  vax_gap_component climate_observation_date  temp_anomaly  precip_anomaly_pct  climate_component  event_component  risk_score risk_tier                                                                                                                               explanation
                       Sudan  SDN Cholera         2024      53001.00       2.653367         1.000000    20635.000000                 1.0              NaN                NaN               2026-08-01         3.722           -2.895584           0.514478              1.0        82.4  Critical recent surveillance anomaly; rising recent trend; forecast points upward; unusual climate conditions; recent outbreak intelligence signal
                        Chad  TCD Measles         2024       6978.00       4.163301         1.000000     6999.333333                 0.0             66.0               0.58               2026-08-01         2.793          -57.205104           0.751526              1.0        76.2  Critical       recent surveillance anomaly; rising recent trend; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                    Ethiopia  ETH Malaria         2024        138.50       3.700050         1.000000      102.543333                 0.0              NaN                NaN               2026-08-01         0.911           -4.577429           0.174720              1.0        70.0      High                                                     recent surveillance anomaly; rising recent trend; recent outbreak intelligence signal
                 South Sudan  SSD Cholera         2024      20132.00       2.759470         0.322883     7342.333333                 1.0              NaN                NaN               2026-08-01         3.515          -45.532298           0.727661              1.0        69.9      High                      recent surveillance anomaly; forecast points upward; unusual climate conditions; recent outbreak intelligence signal
                        Chad  TCD Cholera         2019         93.00       0.674491         1.000000     6208.666667                 1.0              NaN                NaN               2026-08-01         2.793          -57.205104           0.751526              1.0        67.7      High                              rising recent trend; forecast points upward; unusual climate conditions; recent outbreak intelligence signal

In [ ]:

from pathlib import Path

path = Path("/content/africa-public-health-intelligence/src/pipeline.py")
source = path.read_text()

start = source.find("def forecast(")
end = source.find("\ndef ", start + 1)

print(source[start:end])

def forecast(series):
    s = pd.Series(series, dtype="float64").dropna()
    if len(s) < 6:
        return np.nan
    try:
        model = ExponentialSmoothing(s, trend="add", damped_trend=True, initialization_method="estimated").fit(optimized=True)
        return float(model.forecast(1).iloc[0])
    except Exception:
        return float(s.tail(3).mean())

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path
import re

# Locate the existing pipeline file.
path = Path("src/pipeline.py")

if not path.exists():
    raise FileNotFoundError(f"Pipeline file not found: {path.resolve()}")

# Read the current code.
source = path.read_text(encoding="utf-8")

# New forecasting function.
new_forecast = '''def forecast(series):
    """Forecast one step ahead from a numeric disease-surveillance series."""
    s = pd.Series(series, dtype="float64").dropna()

    # Require enough observations for a basic trend model.
    if len(s) < 6:
        return np.nan

    # Use a regular index supported by statsmodels.
    # Calendar-year gaps still need to be checked separately.
    s = pd.Series(
        s.to_numpy(),
        index=pd.RangeIndex(start=0, stop=len(s), step=1),
        dtype="float64",
    )

    try:
        model = ExponentialSmoothing(
            s,
            trend="add",
            damped_trend=True,
            initialization_method="estimated",
        ).fit(optimized=True)

        forecast_value = float(model.forecast(1).iloc[0])

        if np.isfinite(forecast_value):
            return forecast_value

    except (ValueError, TypeError, ArithmeticError, np.linalg.LinAlgError):
        pass

    # Fallback: mean of the last three observed values.
    fallback = float(s.tail(3).mean())

    return fallback if np.isfinite(fallback) else np.nan
'''

# Replace exactly one existing forecast function.
pattern = r"(?ms)^def forecast\(series\):\n.*?(?=^def \w+\(|\Z)"

updated_source, replacements = re.subn(
    pattern,
    lambda match: new_forecast + "\n\n",
    source,
)

if replacements != 1:
    raise RuntimeError(
        f"Expected to replace exactly one forecast() function, "
        f"but found {replacements}. No changes were saved."
    )

# Save the updated file.
path.write_text(updated_source, encoding="utf-8")

# Verify that the replacement was saved.
print("Forecast function updated successfully.")
print("\nUpdated function:\n")

saved_source = path.read_text(encoding="utf-8")
start = saved_source.find("def forecast(series):")
end = saved_source.find("\ndef ", start + 1)

print(saved_source[start:end])

/content/africa-public-health-intelligence
Forecast function updated successfully.

Updated function:

def forecast(series):
    """Forecast one step ahead from a numeric disease-surveillance series."""
    s = pd.Series(series, dtype="float64").dropna()

    # Require enough observations for a basic trend model.
    if len(s) < 6:
        return np.nan

    # Use a regular index supported by statsmodels.
    # Calendar-year gaps still need to be checked separately.
    s = pd.Series(
        s.to_numpy(),
        index=pd.RangeIndex(start=0, stop=len(s), step=1),
        dtype="float64",
    )

    try:
        model = ExponentialSmoothing(
            s,
            trend="add",
            damped_trend=True,
            initialization_method="estimated",
        ).fit(optimized=True)

        forecast_value = float(model.forecast(1).iloc[0])

        if np.isfinite(forecast_value):
            return forecast_value

    except (ValueError, TypeError, ArithmeticError, np.linalg.LinAlgError):
        pass

    # Fallback: mean of the last three observed values.
    fallback = float(s.tail(3).mean())

    return fallback if np.isfinite(fallback) else np.nan

In [ ]:
!python -m pytest -q

...                                                                      [100%]
3 passed in 0.49s

In [ ]:
!python -m src.pipeline

Built 63 country-disease risk records.
                     country iso3 disease  latest_year  latest_value  anomaly_score  trend_component  forecast_value  forecast_component  measles_vax_pct  vax_gap_component climate_observation_date  temp_anomaly  precip_anomaly_pct  climate_component  event_component  risk_score risk_tier                                                                                                                               explanation
                    Ethiopia  ETH Malaria         2024        138.50       3.700050         1.000000      137.408211                 1.0              NaN                NaN               2026-08-01         0.911           -4.577429           0.174720              1.0        87.6  Critical                             recent surveillance anomaly; rising recent trend; forecast points upward; recent outbreak intelligence signal
                       Sudan  SDN Cholera         2024      53001.00       2.653367         1.000000    18560.196772                 1.0              NaN                NaN               2026-08-01         3.722           -2.895584           0.514478              1.0        82.4  Critical recent surveillance anomaly; rising recent trend; forecast points upward; unusual climate conditions; recent outbreak intelligence signal
                        Chad  TCD Measles         2024       6978.00       4.163301         1.000000     6608.949290                 0.0             66.0               0.58               2026-08-01         2.793          -57.205104           0.751526              1.0        76.2  Critical       recent surveillance anomaly; rising recent trend; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                       Sudan  SDN Malaria         2024         98.25       2.457207         0.792051      106.491097                 1.0              NaN                NaN               2026-08-01         3.722           -2.895584           0.514478              1.0        75.8  Critical recent surveillance anomaly; rising recent trend; forecast points upward; unusual climate conditions; recent outbreak intelligence signal
                 South Sudan  SSD Cholera         2024      20132.00       2.759470         0.322883     9864.709519                 1.0              NaN                NaN               2026-08-01         3.515          -45.532298           0.727661              1.0        69.9      High                      recent surveillance anomaly; forecast points upward; unusual climate conditions; recent outbreak intelligence signal
                        Chad  TCD Cholera         2019         93.00       0.674491         1.000000     3462.396405                 1.0              NaN                NaN               2026-08-01         2.793          -57.205104           0.751526              1.0        67.7      High                              rising recent trend; forecast points upward; unusual climate conditions; recent outbreak intelligence signal
                      Uganda  UGA Measles         2024       2180.00       2.168354         0.906522     2182.172104                 1.0             90.0               0.10               2026-08-01         1.774          -40.983607           0.500585              1.0        65.9      High recent surveillance anomaly; rising recent trend; forecast points upward; unusual climate conditions; recent outbreak intelligence signal
                     Liberia  LBR Cholera         2024        340.00       0.000000         1.000000     2470.632345                 1.0              NaN                NaN               2026-08-01         2.233          -99.383995           0.869087              1.0        63.2      High                              rising recent trend; forecast points upward; unusual climate conditions; recent outbreak intelligence signal
Democratic Republic of Congo  COD Measles         2024     311500.00       2.367064         0.780642   168461.156972                 0.0             55.0               0.80               2026-08-01         1.741          -69.187675           0.636105              1.0        61.7      High       recent surveillance anomaly; rising recent trend; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                      Guinea  GIN Cholera         2014          1.00       0.054224         1.000000     1413.656519                 1.0              NaN                NaN               2026-08-01         1.172          -97.472115           0.682694              1.0        61.5      High                              rising recent trend; forecast points upward; unusual climate conditions; recent outbreak intelligence signal
                     Somalia  SOM Measles         2024       1529.00       0.000000         1.000000     7781.083562                 1.0             64.0               0.62               2026-08-01         0.650          -98.463312           0.600650              1.0        60.3      High            rising recent trend; forecast points upward; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                       Ghana  GHA Measles         2024       1944.00       3.403212         1.000000     -479.953199                 0.0             90.0               0.10               2026-08-01         0.140           52.625153           0.286459              1.0        59.9      High                                                     recent surveillance anomaly; rising recent trend; recent outbreak intelligence signal
               Cote d'Ivoire  CIV Measles         2024       1872.00       0.674491         1.000000     1663.996058                 1.0             75.0               0.40               2026-08-01         0.612          -46.905251           0.336526              1.0        59.4      High                                                          rising recent trend; forecast points upward; recent outbreak intelligence signal
                Burkina Faso  BFA Cholera         2022          4.00       0.000000         1.000000      156.999431                 1.0              NaN                NaN               2026-08-01         1.154          -22.570194           0.305184              1.0        56.5      High                                                          rising recent trend; forecast points upward; recent outbreak intelligence signal
                 South Sudan  SSD Malaria         2024        254.08       3.246967         0.253493      246.020155                 0.0              NaN                NaN               2026-08-01         3.515          -45.532298           0.727661              1.0        54.9      High                                              recent surveillance anomaly; unusual climate conditions; recent outbreak intelligence signal

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path
import pandas as pd

path = Path("data/processed/disease_surveillance.csv")

if not path.exists():
    raise FileNotFoundError(f"File not found: {path}")

df = pd.read_csv(path)

print("Columns:")
print(df.columns.tolist())

print("\nRelevant observations:")
print(
    df[
        df["country"].isin(["Chad", "Liberia", "Ghana", "Guinea"])
        & df["disease"].isin(["Cholera", "Measles"])
    ]
    .sort_values(["country", "disease", "year"])
    .to_string(index=False)
)

/content/africa-public-health-intelligence
Columns:
['country', 'iso3', 'year', 'value', 'disease', 'measles_vax_pct']

Relevant observations:
country iso3  year    value disease  measles_vax_pct
   Chad  TCD  1971   8230.0 Cholera              NaN
   Chad  TCD  1972      9.0 Cholera              NaN
   Chad  TCD  1974    338.0 Cholera              NaN
   Chad  TCD  1991  13915.0 Cholera             28.0
   Chad  TCD  1994   1094.0 Cholera             24.0
   Chad  TCD  1996   7830.0 Cholera             22.0
   Chad  TCD  1997   8801.0 Cholera             30.0
   Chad  TCD  1998   4095.0 Cholera             20.0
   Chad  TCD  1999    217.0 Cholera             30.0
   Chad  TCD  2001   5244.0 Cholera             26.0
   Chad  TCD  2003     55.0 Cholera             23.0
   Chad  TCD  2004   5531.0 Cholera             16.0
   Chad  TCD  2005     90.0 Cholera             27.0
   Chad  TCD  2006   1668.0 Cholera             39.0
   Chad  TCD  2007      0.0 Cholera             31.0
   Chad  TCD  2009     67.0 Cholera             36.0
   Chad  TCD  2010   6395.0 Cholera             46.0
   Chad  TCD  2011  17267.0 Cholera             54.0
   Chad  TCD  2017   1266.0 Cholera             37.0
   Chad  TCD  2019     93.0 Cholera             40.0
   Chad  TCD  1974   7051.0 Measles              NaN
   Chad  TCD  1975   2243.0 Measles              NaN
   Chad  TCD  1976  15001.0 Measles              NaN
   Chad  TCD  1977  12299.0 Measles              NaN
   Chad  TCD  1978   2033.0 Measles              NaN
   Chad  TCD  1979    306.0 Measles              NaN
   Chad  TCD  1981     36.0 Measles              NaN
   Chad  TCD  1982   1223.0 Measles              NaN
   Chad  TCD  1983   5160.0 Measles              NaN
   Chad  TCD  1984   6921.0 Measles             10.0
   Chad  TCD  1985   6430.0 Measles              7.0
   Chad  TCD  1986   3500.0 Measles             12.0
   Chad  TCD  1987   3623.0 Measles             16.0
   Chad  TCD  1988   3645.0 Measles             17.0
   Chad  TCD  1989   7449.0 Measles             32.0
   Chad  TCD  1990   7226.0 Measles             32.0
   Chad  TCD  1991  21182.0 Measles             28.0
   Chad  TCD  1992  19035.0 Measles             25.0
   Chad  TCD  1993  20894.0 Measles             19.0
   Chad  TCD  1994   9696.0 Measles             24.0
   Chad  TCD  1995  21952.0 Measles             26.0
   Chad  TCD  1996  24162.0 Measles             22.0
   Chad  TCD  1997  10446.0 Measles             30.0
   Chad  TCD  1998  12371.0 Measles             20.0
   Chad  TCD  1999   6868.0 Measles             30.0
   Chad  TCD  2000   3546.0 Measles             28.0
   Chad  TCD  2001  24908.0 Measles             26.0
   Chad  TCD  2002   7277.0 Measles             25.0
   Chad  TCD  2003  15801.0 Measles             23.0
   Chad  TCD  2004  10324.0 Measles             16.0
   Chad  TCD  2005      2.0 Measles             27.0
   Chad  TCD  2006   1594.0 Measles             39.0
   Chad  TCD  2007    441.0 Measles             31.0
   Chad  TCD  2008     63.0 Measles             27.0
   Chad  TCD  2009    165.0 Measles             36.0
   Chad  TCD  2010    194.0 Measles             46.0
   Chad  TCD  2011   8650.0 Measles             54.0
   Chad  TCD  2012    120.0 Measles             63.0
   Chad  TCD  2013    226.0 Measles             57.0
   Chad  TCD  2014   1275.0 Measles             45.0
   Chad  TCD  2015    418.0 Measles             46.0
   Chad  TCD  2016    118.0 Measles             37.0
   Chad  TCD  2017      9.0 Measles             37.0
   Chad  TCD  2018   1457.0 Measles             41.0
   Chad  TCD  2019   1882.0 Measles             40.0
   Chad  TCD  2020   2170.0 Measles             45.0
   Chad  TCD  2021   2577.0 Measles             53.0
   Chad  TCD  2022   2158.0 Measles             54.0
   Chad  TCD  2023  11862.0 Measles             63.0
   Chad  TCD  2024   6978.0 Measles             66.0
  Ghana  GHA  1970   2733.0 Cholera              NaN
  Ghana  GHA  1971  13048.0 Cholera              NaN
  Ghana  GHA  1972    625.0 Cholera              NaN
  Ghana  GHA  1973    677.0 Cholera              NaN
  Ghana  GHA  1974    483.0 Cholera              NaN
  Ghana  GHA  1975    187.0 Cholera              NaN
  Ghana  GHA  1976    102.0 Cholera              NaN
  Ghana  GHA  1977   6565.0 Cholera              NaN
  Ghana  GHA  1978   1853.0 Cholera              NaN
  Ghana  GHA  1979   1783.0 Cholera              NaN
  Ghana  GHA  1980    260.0 Cholera             16.0
  Ghana  GHA  1981    943.0 Cholera             23.0
  Ghana  GHA  1982  11051.0 Cholera             21.0
  Ghana  GHA  1983  14160.0 Cholera             16.0
  Ghana  GHA  1984   1015.0 Cholera             10.0
  Ghana  GHA  1985     60.0 Cholera             21.0
  Ghana  GHA  1990   2937.0 Cholera             61.0
  Ghana  GHA  1991  13172.0 Cholera             63.0
  Ghana  GHA  1992    228.0 Cholera             64.0
  Ghana  GHA  1993   1448.0 Cholera             66.0
  Ghana  GHA  1994   2267.0 Cholera             68.0
  Ghana  GHA  1995   4698.0 Cholera             70.0
  Ghana  GHA  1996   1665.0 Cholera             71.0
  Ghana  GHA  1997    379.0 Cholera             73.0
  Ghana  GHA  1998   3426.0 Cholera             78.0
  Ghana  GHA  1999   9432.0 Cholera             81.0
  Ghana  GHA  2000   3331.0 Cholera             90.0
  Ghana  GHA  2001   5487.0 Cholera             78.0
  Ghana  GHA  2002   3614.0 Cholera             78.0
  Ghana  GHA  2003    204.0 Cholera             80.0
  Ghana  GHA  2004    407.0 Cholera             83.0
  Ghana  GHA  2005   3166.0 Cholera             83.0
  Ghana  GHA  2006   3357.0 Cholera             85.0
  Ghana  GHA  2007    179.0 Cholera             95.0
  Ghana  GHA  2008   1223.0 Cholera             86.0
  Ghana  GHA  2009   1294.0 Cholera             93.0
  Ghana  GHA  2010    438.0 Cholera             93.0
  Ghana  GHA  2011  10628.0 Cholera             91.0
  Ghana  GHA  2012   9548.0 Cholera             89.0
  Ghana  GHA  2013     50.0 Cholera             89.0
  Ghana  GHA  2014  28944.0 Cholera             92.0
  Ghana  GHA  2015    692.0 Cholera             89.0
  Ghana  GHA  2016    175.0 Cholera             89.0
  Ghana  GHA  2019      1.0 Cholera             92.0
  Ghana  GHA  2021      2.0 Cholera             94.0
  Ghana  GHA  2024    423.0 Cholera             90.0
  Ghana  GHA  1974  91315.0 Measles              NaN
  Ghana  GHA  1975 140821.0 Measles              NaN
  Ghana  GHA  1976 131405.0 Measles              NaN
  Ghana  GHA  1977 108440.0 Measles              NaN
  Ghana  GHA  1978 107381.0 Measles              NaN
  Ghana  GHA  1979  88808.0 Measles              NaN
  Ghana  GHA  1980  82684.0 Measles             16.0
  Ghana  GHA  1981  38476.0 Measles             23.0
  Ghana  GHA  1982  79636.0 Measles             21.0
  Ghana  GHA  1983  36561.0 Measles             16.0
  Ghana  GHA  1984  40179.0 Measles             10.0
  Ghana  GHA  1985  64517.0 Measles             21.0
  Ghana  GHA  1986  11099.0 Measles             31.0
  Ghana  GHA  1987  24781.0 Measles             51.0
  Ghana  GHA  1988  40456.0 Measles             59.0
  Ghana  GHA  1989  19997.0 Measles             65.0
  Ghana  GHA  1990  32246.0 Measles             61.0
  Ghana  GHA  1991  17135.0 Measles             63.0
  Ghana  GHA  1992  39933.0 Measles             64.0
  Ghana  GHA  1993  34641.0 Measles             66.0
  Ghana  GHA  1994  34821.0 Measles             68.0
  Ghana  GHA  1995  40276.0 Measles             70.0
  Ghana  GHA  1996  34273.0 Measles             71.0
  Ghana  GHA  1997  37261.0 Measles             73.0
  Ghana  GHA  1998  23335.0 Measles             78.0
  Ghana  GHA  1999  15987.0 Measles             81.0
  Ghana  GHA  2000  23068.0 Measles             90.0
  Ghana  GHA  2001  13476.0 Measles             78.0
  Ghana  GHA  2002  12289.0 Measles             78.0
  Ghana  GHA  2003   1939.0 Measles             80.0
  Ghana  GHA  2004     60.0 Measles             83.0
  Ghana  GHA  2005    435.0 Measles             83.0
  Ghana  GHA  2006    420.0 Measles             85.0
  Ghana  GHA  2007      6.0 Measles             95.0
  Ghana  GHA  2008     82.0 Measles             86.0
  Ghana  GHA  2009    101.0 Measles             93.0
  Ghana  GHA  2010    641.0 Measles             93.0
  Ghana  GHA  2011    120.0 Measles             91.0
  Ghana  GHA  2012   1613.0 Measles             89.0
  Ghana  GHA  2013    319.0 Measles             89.0
  Ghana  GHA  2014    124.0 Measles             92.0
  Ghana  GHA  2015     23.0 Measles             89.0
  Ghana  GHA  2016     32.0 Measles             89.0
  Ghana  GHA  2017     19.0 Measles             95.0
  Ghana  GHA  2018     34.0 Measles             92.0
  Ghana  GHA  2019   1274.0 Measles             92.0
  Ghana  GHA  2020     88.0 Measles             88.0
  Ghana  GHA  2021     52.0 Measles             94.0
  Ghana  GHA  2022    395.0 Measles             95.0
  Ghana  GHA  2023   2282.0 Measles             90.0
  Ghana  GHA  2024   1944.0 Measles             90.0
 Guinea  GIN  1970   2000.0 Cholera              NaN
 Guinea  GIN  1986    286.0 Cholera             28.0
 Guinea  GIN  1994  31415.0 Cholera             58.0
 Guinea  GIN  1995   6506.0 Cholera             61.0
 Guinea  GIN  1996    287.0 Cholera             61.0
 Guinea  GIN  1998    881.0 Cholera             52.0
 Guinea  GIN  1999    599.0 Cholera             40.0
 Guinea  GIN  2000    519.0 Cholera             42.0
 Guinea  GIN  2001    392.0 Cholera             44.0
 Guinea  GIN  2002     61.0 Cholera             46.0
 Guinea  GIN  2003      6.0 Cholera             48.0
 Guinea  GIN  2004   1516.0 Cholera             50.0
 Guinea  GIN  2005   3821.0 Cholera             51.0
 Guinea  GIN  2006   3242.0 Cholera             51.0
 Guinea  GIN  2007   8546.0 Cholera             57.0
 Guinea  GIN  2008    513.0 Cholera             55.0
 Guinea  GIN  2009     42.0 Cholera             53.0
 Guinea  GIN  2011      3.0 Cholera             62.0
 Guinea  GIN  2012   7350.0 Cholera             58.0
 Guinea  GIN  2013    319.0 Cholera             55.0
 Guinea  GIN  2014      1.0 Cholera             51.0
 Guinea  GIN  1974  11798.0 Measles              NaN
 Guinea  GIN  1975   7536.0 Measles              NaN
 Guinea  GIN  1976   5852.0 Measles              NaN
 Guinea  GIN  1977   8045.0 Measles              NaN
 Guinea  GIN  1978   4061.0 Measles              NaN
 Guinea  GIN  1979   6236.0 Measles              NaN
 Guinea  GIN  1980   8552.0 Measles              NaN
 Guinea  GIN  1981  11397.0 Measles             15.0
 Guinea  GIN  1982  15038.0 Measles             34.0
 Guinea  GIN  1983   8856.0 Measles             30.0
 Guinea  GIN  1984   4396.0 Measles             29.0
 Guinea  GIN  1985   2969.0 Measles             29.0
 Guinea  GIN  1986   2592.0 Measles             28.0
 Guinea  GIN  1987   7357.0 Measles             28.0
 Guinea  GIN  1988   3353.0 Measles             27.0
 Guinea  GIN  1989   4152.0 Measles             27.0
 Guinea  GIN  1990  12756.0 Measles             35.0
 Guinea  GIN  1991   6708.0 Measles             42.0
 Guinea  GIN  1992   1617.0 Measles             52.0
 Guinea  GIN  1993   5228.0 Measles             55.0
 Guinea  GIN  1994   2372.0 Measles             58.0
 Guinea  GIN  1995   1085.0 Measles             61.0
 Guinea  GIN  1996  10292.0 Measles             61.0
 Guinea  GIN  1997  10170.0 Measles             56.0
 Guinea  GIN  1998   9170.0 Measles             52.0
 Guinea  GIN  1999  18004.0 Measles             40.0
 Guinea  GIN  2000  11294.0 Measles             42.0
 Guinea  GIN  2001   7408.0 Measles             44.0
 Guinea  GIN  2002   2151.0 Measles             46.0
 Guinea  GIN  2003   2497.0 Measles             48.0
 Guinea  GIN  2004     10.0 Measles             50.0
 Guinea  GIN  2005     99.0 Measles             51.0
 Guinea  GIN  2006      4.0 Measles             51.0
 Guinea  GIN  2007      3.0 Measles             57.0
 Guinea  GIN  2008     89.0 Measles             55.0
 Guinea  GIN  2009    264.0 Measles             53.0
 Guinea  GIN  2010     45.0 Measles             58.0
 Guinea  GIN  2011     11.0 Measles             62.0
 Guinea  GIN  2012      6.0 Measles             58.0
 Guinea  GIN  2013     53.0 Measles             55.0
 Guinea  GIN  2014    175.0 Measles             51.0
 Guinea  GIN  2015    243.0 Measles             47.0
 Guinea  GIN  2016    316.0 Measles             48.0
 Guinea  GIN  2017   2036.0 Measles             48.0
 Guinea  GIN  2018    482.0 Measles             49.0
 Guinea  GIN  2019   4555.0 Measles             50.0
 Guinea  GIN  2020    506.0 Measles             50.0
 Guinea  GIN  2021    505.0 Measles             51.0
 Guinea  GIN  2022    417.0 Measles             51.0
 Guinea  GIN  2023     94.0 Measles             52.0
 Guinea  GIN  2024    577.0 Measles             60.0
Liberia  LBR  1970    168.0 Cholera              NaN
Liberia  LBR  1971    606.0 Cholera              NaN
Liberia  LBR  1972    947.0 Cholera              NaN
Liberia  LBR  1973   1336.0 Cholera              NaN
Liberia  LBR  1974    512.0 Cholera              NaN
Liberia  LBR  1975    704.0 Cholera              NaN
Liberia  LBR  1976    646.0 Cholera              NaN
Liberia  LBR  1977    512.0 Cholera              NaN
Liberia  LBR  1978    422.0 Cholera              NaN
Liberia  LBR  1979    438.0 Cholera              NaN
Liberia  LBR  1980   2690.0 Cholera              NaN
Liberia  LBR  1981   1582.0 Cholera              NaN
Liberia  LBR  1982    670.0 Cholera              NaN
Liberia  LBR  1983    183.0 Cholera              NaN
Liberia  LBR  1984    492.0 Cholera              NaN
Liberia  LBR  1985    355.0 Cholera              NaN
Liberia  LBR  1986     59.0 Cholera              NaN
Liberia  LBR  1987     33.0 Cholera              NaN
Liberia  LBR  1988     68.0 Cholera              NaN
Liberia  LBR  1989     28.0 Cholera              NaN
Liberia  LBR  1991    132.0 Cholera              NaN
Liberia  LBR  1994    764.0 Cholera              NaN
Liberia  LBR  1995   3420.0 Cholera              NaN
Liberia  LBR  1996   8922.0 Cholera              NaN
Liberia  LBR  1997     91.0 Cholera              NaN
Liberia  LBR  1998   2123.0 Cholera              NaN
Liberia  LBR  1999    215.0 Cholera             69.0
Liberia  LBR  2000    365.0 Cholera             63.0
Liberia  LBR  2001   1062.0 Cholera             58.0
Liberia  LBR  2002   1115.0 Cholera             52.0
Liberia  LBR  2003  34740.0 Cholera             47.0
Liberia  LBR  2004   2786.0 Cholera             41.0
Liberia  LBR  2005   3823.0 Cholera             62.0
Liberia  LBR  2006   4929.0 Cholera             63.0
Liberia  LBR  2007   3063.0 Cholera             71.0
Liberia  LBR  2008   1236.0 Cholera             76.0
Liberia  LBR  2009   1070.0 Cholera             83.0
Liberia  LBR  2010   1546.0 Cholera             65.0
Liberia  LBR  2011   1146.0 Cholera             71.0
Liberia  LBR  2012    219.0 Cholera             80.0
Liberia  LBR  2013     92.0 Cholera             74.0
Liberia  LBR  2014     44.0 Cholera             58.0
Liberia  LBR  2018      2.0 Cholera             74.0
Liberia  LBR  2021    167.0 Cholera             58.0
Liberia  LBR  2022    367.0 Cholera             79.0
Liberia  LBR  2023    925.0 Cholera             82.0
Liberia  LBR  2024    340.0 Cholera             82.0
Liberia  LBR  1974    592.0 Measles              NaN
Liberia  LBR  1975    591.0 Measles              NaN
Liberia  LBR  1976   2212.0 Measles              NaN
Liberia  LBR  1977   3588.0 Measles              NaN
Liberia  LBR  1978   3705.0 Measles              NaN
Liberia  LBR  1979   3243.0 Measles              NaN
Liberia  LBR  1980   6567.0 Measles              NaN
Liberia  LBR  1981   7810.0 Measles              NaN
Liberia  LBR  1982   6873.0 Measles              NaN
Liberia  LBR  1983   4835.0 Measles              NaN
Liberia  LBR  1984   6151.0 Measles              NaN
Liberia  LBR  1985   2686.0 Measles              NaN
Liberia  LBR  1986    836.0 Measles              NaN
Liberia  LBR  1987   2178.0 Measles              NaN
Liberia  LBR  1988   2556.0 Measles              NaN
Liberia  LBR  1989   1866.0 Measles              NaN
Liberia  LBR  1992   5776.0 Measles              NaN
Liberia  LBR  1993   6398.0 Measles              NaN
Liberia  LBR  1994    571.0 Measles              NaN
Liberia  LBR  1995     56.0 Measles              NaN
Liberia  LBR  1996   1938.0 Measles              NaN
Liberia  LBR  1997   2961.0 Measles              NaN
Liberia  LBR  1998   1436.0 Measles              NaN
Liberia  LBR  1999   1679.0 Measles             69.0
Liberia  LBR  2000   5977.0 Measles             63.0
Liberia  LBR  2001   1379.0 Measles             58.0
Liberia  LBR  2002    131.0 Measles             52.0
Liberia  LBR  2003    142.0 Measles             47.0
Liberia  LBR  2004      4.0 Measles             41.0
Liberia  LBR  2005      8.0 Measles             62.0
Liberia  LBR  2006     20.0 Measles             63.0
Liberia  LBR  2007      1.0 Measles             71.0
Liberia  LBR  2008      1.0 Measles             76.0
Liberia  LBR  2009      6.0 Measles             83.0
Liberia  LBR  2010   2200.0 Measles             65.0
Liberia  LBR  2011    279.0 Measles             71.0
Liberia  LBR  2012     43.0 Measles             80.0
Liberia  LBR  2013      0.0 Measles             74.0
Liberia  LBR  2014     34.0 Measles             58.0
Liberia  LBR  2015   1060.0 Measles             64.0
Liberia  LBR  2016    789.0 Measles             70.0
Liberia  LBR  2017    960.0 Measles             75.0
Liberia  LBR  2018   3781.0 Measles             74.0
Liberia  LBR  2019   1203.0 Measles             68.0
Liberia  LBR  2020    884.0 Measles             61.0
Liberia  LBR  2021    250.0 Measles             58.0
Liberia  LBR  2022   8300.0 Measles             79.0
Liberia  LBR  2023   4604.0 Measles             82.0
Liberia  LBR  2024   1053.0 Measles             82.0

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path

source = Path("src/pipeline.py").read_text(encoding="utf-8")

# Show the forecasting function and the code that calls it.
for heading, start_marker, end_marker in [
    ("FORECAST FUNCTION", "def forecast(", "\ndef "),
    ("FORECAST CALL SITES", "def build(", "\nif __name__"),
]:
    start = source.find(start_marker)

    print(f"\n{'=' * 20} {heading} {'=' * 20}")

    if start == -1:
        print("Section not found.")
        continue

    if heading == "FORECAST FUNCTION":
        end = source.find(end_marker, start + len(start_marker))
        if end == -1:
            end = len(source)
        print(source[start:end])
    else:
        section = source[start:]
        for line_number, line in enumerate(section.splitlines(), start=1):
            if (
                "forecast(" in line
                or "forecast_value" in line
                or "forecast_component" in line
                or "groupby(" in line
                or "sort_values(" in line
            ):
                print(f"{line_number}: {line}")

/content/africa-public-health-intelligence

==================== FORECAST FUNCTION ====================
def forecast(series):
    """Forecast one step ahead from a numeric disease-surveillance series."""
    s = pd.Series(series, dtype="float64").dropna()

    # Require enough observations for a basic trend model.
    if len(s) < 6:
        return np.nan

    # Use a regular index supported by statsmodels.
    # Calendar-year gaps still need to be checked separately.
    s = pd.Series(
        s.to_numpy(),
        index=pd.RangeIndex(start=0, stop=len(s), step=1),
        dtype="float64",
    )

    try:
        model = ExponentialSmoothing(
            s,
            trend="add",
            damped_trend=True,
            initialization_method="estimated",
        ).fit(optimized=True)

        forecast_value = float(model.forecast(1).iloc[0])

        if np.isfinite(forecast_value):
            return forecast_value

    except (ValueError, TypeError, ArithmeticError, np.linalg.LinAlgError):
        pass

    # Fallback: mean of the last three observed values.
    fallback = float(s.tail(3).mean())

    return fallback if np.isfinite(fallback) else np.nan



==================== FORECAST CALL SITES ====================
17:     for (country, disease), g in disease_df.groupby(["country","disease"]):
18:         g = g.sort_values("year").copy()
21:         fc = forecast(g["value"])
35:             "forecast_value": fc,
36:             "forecast_component": forecast_up,
73:         r["anomaly_score"], r["trend_component"], r["forecast_component"],
79:     risk = risk.sort_values("risk_score", ascending=False)
85:     forecasts = risk[["country","iso3","disease","latest_year","latest_value","forecast_value"]].copy()

In [ ]:
%cd /content/africa-public-health-intelligence

from pathlib import Path

source = Path("src/pipeline.py").read_text(encoding="utf-8")
lines = source.splitlines()

print("\n".join(
    f"{i + 1:03d}: {lines[i]}"
    for i in range(min(55, len(lines)))
))

/content/africa-public-health-intelligence
001: from pathlib import Path
002: import json
003: import re
004: import numpy as np
005: import pandas as pd
006: from statsmodels.tsa.holtwinters import ExponentialSmoothing
007: from .risk_engine import robust_anomaly, trend_score, vaccination_gap, climate_signal, risk_score, risk_tier, explain
008:
009: ROOT = Path(__file__).resolve().parents[1]
010: RAW = ROOT / "data" / "raw"
011: OUT = ROOT / "data" / "processed"
012: OUT.mkdir(parents=True, exist_ok=True)
013:
014: AFRO_COUNTRIES = set(pd.read_csv(ROOT / "config" / "countries.csv")["country"])
015:
016: def read_owid(name):
017:     p = RAW / f"{name}.csv"
018:     if not p.exists():
019:         raise FileNotFoundError(f"{p} missing. Run: python scripts/download_data.py")
020:     df = pd.read_csv(p)
021:     # OWID standard columns are Entity, Code, Year, plus one value column.
022:     value = [c for c in df.columns if c not in {"Entity", "Code", "Year"}][0]
023:     return df.rename(columns={"Entity":"country", "Code":"iso3", "Year":"year", value:"value"})[
024:         ["country","iso3","year","value"]
025:     ]
026:
027: def prepare_disease(name, disease):
028:     df = read_owid(name)
029:     df["disease"] = disease
030:     return df[df["country"].isin(AFRO_COUNTRIES)].copy()
031:
032: def outbreak_signals():
033:     p = RAW / "who_disease_outbreak_news.json"
034:     if not p.exists():
035:         return pd.DataFrame(columns=["title","publication_date","text","event_signal"])
036:     payload = json.loads(p.read_text())
037:     if isinstance(payload, dict):
038:         items = payload.get("value") or payload.get("items") or []
039:     else:
040:         items = payload
041:     rows = []
042:     diseases = r"cholera|measles|malaria|mpox|monkeypox|ebola|marburg|yellow fever|meningitis|polio|lassa|dengue|rift valley"
043:     for x in items:
044:         title = str(x.get("Title") or x.get("title") or "")
045:         summary = str(x.get("Summary") or x.get("summary") or x.get("Overview") or "")
046:         text = f"{title} {summary}"
047:         if not re.search(diseases, text, flags=re.I):
048:             continue
049:         rows.append({
050:             "title": title,
051:             "publication_date": x.get("PublicationDate") or x.get("publicationDate"),
052:             "text": text,
053:             "event_signal": 1.0
054:         })
055:     return pd.DataFrame(rows)

In [ ]:
%cd /content/africa-public-health-intelligence

from pathlib import Path

lines = Path("src/pipeline.py").read_text(encoding="utf-8").splitlines()

print("\n".join(
    f"{i + 1:03d}: {lines[i]}"
    for i in range(50, min(120, len(lines)))
))

/content/africa-public-health-intelligence
051:             "publication_date": x.get("PublicationDate") or x.get("publicationDate"),
052:             "text": text,
053:             "event_signal": 1.0
054:         })
055:     return pd.DataFrame(rows)
056:
057: def latest_climate():
058:     """
059:     Load climate anomalies and select the latest usable observation
060:     for each country. Preserve missing data when no usable observation
061:     exists.
062:     """
063:     p = OUT / "climate_anomalies.csv"
064:
065:     columns = [
066:         "iso3",
067:         "date",
068:         "temp_anomaly",
069:         "precip_anomaly_pct",
070:         "climate_component",
071:     ]
072:
073:     if not p.exists():
074:         return pd.DataFrame(columns=columns)
075:
076:     df = pd.read_csv(p)
077:
078:     required = {
079:         "iso3",
080:         "date",
081:         "temp_anomaly_c",
082:         "precip_anomaly_pct",
083:         "climate_component",
084:     }
085:
086:     missing = required.difference(df.columns)
087:     if missing:
088:         raise ValueError(
089:             f"Climate anomalies file is missing columns: {sorted(missing)}"
090:         )
091:
092:     df["date"] = pd.to_datetime(df["date"], errors="coerce")
093:
094:     for column in [
095:         "temp_anomaly_c",
096:         "precip_anomaly_pct",
097:         "climate_component",
098:     ]:
099:         df[column] = pd.to_numeric(df[column], errors="coerce")
100:
101:     df = df.dropna(subset=["iso3", "date"]).copy()
102:
103:     invalid = (
104:         df["climate_component"].notna()
105:         & ~df["climate_component"].between(0, 1)
106:     )
107:
108:     if invalid.any():
109:         raise ValueError("Climate component values must be between 0 and 1.")
110:
111:     duplicates = df.duplicated(["iso3", "date"], keep=False)
112:     if duplicates.any():
113:         sample = df.loc[duplicates, ["iso3", "date"]].head(10)
114:         raise ValueError(
115:             "Duplicate country-month records found. Investigate them "
116:             "before continuing:\\n" + sample.to_string(index=False)
117:         )
118:
119:     # Exclude months with no usable climate component.
120:     usable = df.loc[df["climate_component"].notna()].copy()

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path

lines = Path("src/pipeline.py").read_text(encoding="utf-8").splitlines()

keywords = [
    "def forecast(",
    "def build(",
    "forecast(g[",
    "forecast_up",
    "latest_year",
    '"risk_score"',
]

matches = [
    i for i, line in enumerate(lines)
    if any(key in line for key in keywords)
]

shown = set()

for i in matches:
    start = max(0, i - 5)
    end = min(len(lines), i + 7)

    for j in range(start, end):
        if j not in shown:
            print(f"{j + 1:03d}: {lines[j]}")
            shown.add(j)

    print("-" * 50)

/content/africa-public-health-intelligence
131:     )
132:
133:     return latest[columns].copy()
134:
135:
136: def forecast(series):
137:     """Forecast one step ahead from a numeric disease-surveillance series."""
138:     s = pd.Series(series, dtype="float64").dropna()
139:
140:     # Require enough observations for a basic trend model.
141:     if len(s) < 6:
142:         return np.nan
--------------------------------------------------
169:     fallback = float(s.tail(3).mean())
170:
171:     return fallback if np.isfinite(fallback) else np.nan
172:
173:
174: def build():
175:     diseases = {
176:         "malaria_incidence": ("malaria_incidence", "Malaria"),
177:         "measles_cases": ("measles_cases", "Measles"),
178:         "cholera_cases": ("cholera_cases", "Cholera"),
179:     }
180:     all_disease = []
--------------------------------------------------
189:     results = []
190:     for (country, disease), g in disease_df.groupby(["country","disease"]):
191:         g = g.sort_values("year").copy()
192:         g["anomaly_score"] = robust_anomaly(g["value"])
193:         latest = g.iloc[-1]
194:         fc = forecast(g["value"])
195:         prev = float(g["value"].iloc[-2]) if len(g) >= 2 else np.nan
196:         forecast_up = 1.0 if pd.notna(fc) and pd.notna(prev) and fc > prev * 1.05 else 0.0
197:         tr = trend_score(g["value"])
198:         vax = float(latest["measles_vax_pct"]) if disease == "Measles" and pd.notna(latest["measles_vax_pct"]) else np.nan
199:
200:         results.append({
--------------------------------------------------
201:             "country": country,
202:             "iso3": latest["iso3"],
--------------------------------------------------
203:             "disease": disease,
204:             "latest_year": int(latest["year"]),
205:             "latest_value": float(latest["value"]),
206:             "anomaly_score": float(latest["anomaly_score"]),
207:             "trend_component": tr,
208:             "forecast_value": fc,
209:             "forecast_component": forecast_up,
210:             "measles_vax_pct": vax,
--------------------------------------------------
211:             "vax_gap_component": vaccination_gap(vax),
212:         })
213:
214:     risk = pd.DataFrame(results)
215:     climate = latest_climate()
--------------------------------------------------
240:     event_count = len(events)
241:     # For MVP, event intelligence is a region-level signal. A future version should
242:     # extract country/disease entities using NER and join them at country-disease level.
243:     risk["event_component"] = 1.0 if event_count else 0.0
244:
245:     risk["risk_score"] = risk.apply(lambda r: risk_score(
246:         r["anomaly_score"], r["trend_component"], r["forecast_component"],
247:         r["vax_gap_component"], r["climate_component"], r["event_component"]
248:     ), axis=1)
249:     risk["risk_tier"] = risk["risk_score"].map(risk_tier)
250:     risk["explanation"] = risk.apply(explain, axis=1)
251:
--------------------------------------------------
252:     risk = risk.sort_values("risk_score", ascending=False)
253:     risk.to_csv(OUT / "risk_register.csv", index=False)
254:     disease_df.to_csv(OUT / "disease_surveillance.csv", index=False)
255:     events.to_csv(OUT / "event_signals.csv", index=False)
--------------------------------------------------
256:
257:     # Forecast table
258:     forecasts = risk[["country","iso3","disease","latest_year","latest_value","forecast_value"]].copy()
--------------------------------------------------
259:     forecasts.to_csv(OUT / "forecasts.csv", index=False)
260:
261:     print(f"Built {len(risk):,} country-disease risk records.")
262:     print(risk.head(15).to_string(index=False))
263:     return risk
264:
--------------------------------------------------

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path

lines = Path("src/pipeline.py").read_text(encoding="utf-8").splitlines()

print("\n".join(
    f"{i + 1:03d}: {lines[i]}"
    for i in range(135, min(175, len(lines)))
))

/content/africa-public-health-intelligence
136: def forecast(series):
137:     """Forecast one step ahead from a numeric disease-surveillance series."""
138:     s = pd.Series(series, dtype="float64").dropna()
139:
140:     # Require enough observations for a basic trend model.
141:     if len(s) < 6:
142:         return np.nan
143:
144:     # Use a regular index supported by statsmodels.
145:     # Calendar-year gaps still need to be checked separately.
146:     s = pd.Series(
147:         s.to_numpy(),
148:         index=pd.RangeIndex(start=0, stop=len(s), step=1),
149:         dtype="float64",
150:     )
151:
152:     try:
153:         model = ExponentialSmoothing(
154:             s,
155:             trend="add",
156:             damped_trend=True,
157:             initialization_method="estimated",
158:         ).fit(optimized=True)
159:
160:         forecast_value = float(model.forecast(1).iloc[0])
161:
162:         if np.isfinite(forecast_value):
163:             return forecast_value
164:
165:     except (ValueError, TypeError, ArithmeticError, np.linalg.LinAlgError):
166:         pass
167:
168:     # Fallback: mean of the last three observed values.
169:     fallback = float(s.tail(3).mean())
170:
171:     return fallback if np.isfinite(fallback) else np.nan
172:
173:
174: def build():
175:     diseases = {

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path
import re

path = Path("src/pipeline.py")
source = path.read_text(encoding="utf-8")

new_function = '''def forecast(years, values, current_year=2026):
    """
    Forecast the next annual disease value conservatively.

    A forecast is returned only when:
    - the latest observation is no more than two years old;
    - at least six observations are available;
    - the six most recent observations cover consecutive calendar years.

    Missing years are not treated as zero.
    """
    data = pd.DataFrame({
        "year": pd.to_numeric(pd.Series(years), errors="coerce"),
        "value": pd.to_numeric(pd.Series(values), errors="coerce"),
    })

    data = data.dropna(subset=["year", "value"]).copy()
    data = data.sort_values("year")

    if data.empty:
        return np.nan

    # Annual surveillance records should have integer calendar years.
    data = data[data["year"] % 1 == 0].copy()
    data["year"] = data["year"].astype(int)

    # Multiple observations for one country-disease-year are ambiguous.
    if data["year"].duplicated().any():
        return np.nan

    latest_year = int(data["year"].iloc[-1])

    # Do not present old surveillance data as a current forecast.
    if current_year - latest_year > 2 or latest_year > current_year:
        return np.nan

    recent = data.tail(6).copy()

    if len(recent) < 6:
        return np.nan

    # Require consecutive calendar years in the six observations.
    year_differences = recent["year"].diff().dropna()

    if not year_differences.eq(1).all():
        return np.nan

    s = recent["value"].astype("float64")

    if not np.isfinite(s).all() or (s < 0).any():
        return np.nan

    try:
        model = ExponentialSmoothing(
            s.reset_index(drop=True),
            trend="add",
            damped_trend=True,
            initialization_method="estimated",
        ).fit(optimized=True)

        forecast_value = float(model.forecast(1).iloc[0])

        if np.isfinite(forecast_value):
            return max(0.0, forecast_value)

    except (
        ValueError,
        TypeError,
        ArithmeticError,
        np.linalg.LinAlgError,
    ):
        pass

    # Conservative fallback for a valid recent annual series.
    fallback = float(s.tail(3).median())

    return max(0.0, fallback) if np.isfinite(fallback) else np.nan
'''

pattern = r"def forecast\(series\):.*?(?=\ndef build\(\):)"

updated_source, replacements = re.subn(
    pattern,
    new_function.rstrip() + "\n\n",
    source,
    count=1,
    flags=re.DOTALL,
)

if replacements != 1:
    raise RuntimeError(
        f"Expected to replace one forecast function; replaced {replacements}. "
        "The file has not been changed."
    )

# Write only after the expected function has been found.
path.write_text(updated_source, encoding="utf-8")

print("Forecast function replaced successfully.")
print("\n".join(
    f"{i + 1:03d}: {line}"
    for i, line in enumerate(updated_source.splitlines()[135:205], start=135)
))

/content/africa-public-health-intelligence
Forecast function replaced successfully.
136: def forecast(years, values, current_year=2026):
137:     """
138:     Forecast the next annual disease value conservatively.
139:
140:     A forecast is returned only when:
141:     - the latest observation is no more than two years old;
142:     - at least six observations are available;
143:     - the six most recent observations cover consecutive calendar years.
144:
145:     Missing years are not treated as zero.
146:     """
147:     data = pd.DataFrame({
148:         "year": pd.to_numeric(pd.Series(years), errors="coerce"),
149:         "value": pd.to_numeric(pd.Series(values), errors="coerce"),
150:     })
151:
152:     data = data.dropna(subset=["year", "value"]).copy()
153:     data = data.sort_values("year")
154:
155:     if data.empty:
156:         return np.nan
157:
158:     # Annual surveillance records should have integer calendar years.
159:     data = data[data["year"] % 1 == 0].copy()
160:     data["year"] = data["year"].astype(int)
161:
162:     # Multiple observations for one country-disease-year are ambiguous.
163:     if data["year"].duplicated().any():
164:         return np.nan
165:
166:     latest_year = int(data["year"].iloc[-1])
167:
168:     # Do not present old surveillance data as a current forecast.
169:     if current_year - latest_year > 2 or latest_year > current_year:
170:         return np.nan
171:
172:     recent = data.tail(6).copy()
173:
174:     if len(recent) < 6:
175:         return np.nan
176:
177:     # Require consecutive calendar years in the six observations.
178:     year_differences = recent["year"].diff().dropna()
179:
180:     if not year_differences.eq(1).all():
181:         return np.nan
182:
183:     s = recent["value"].astype("float64")
184:
185:     if not np.isfinite(s).all() or (s < 0).any():
186:         return np.nan
187:
188:     try:
189:         model = ExponentialSmoothing(
190:             s.reset_index(drop=True),
191:             trend="add",
192:             damped_trend=True,
193:             initialization_method="estimated",
194:         ).fit(optimized=True)
195:
196:         forecast_value = float(model.forecast(1).iloc[0])
197:
198:         if np.isfinite(forecast_value):
199:             return max(0.0, forecast_value)
200:
201:     except (
202:         ValueError,
203:         TypeError,
204:         ArithmeticError,
205:         np.linalg.LinAlgError,

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path

path = Path("src/risk_engine.py")
lines = path.read_text(encoding="utf-8").splitlines()

for i, line in enumerate(lines):
    if "def risk_score(" in line:
        start = max(0, i - 2)
        end = min(len(lines), i + 45)

        print("\n".join(
            f"{j + 1:03d}: {lines[j]}"
            for j in range(start, end)
        ))
        break
else:
    print("Could not find def risk_score() in src/risk_engine.py")

/content/africa-public-health-intelligence
049:
050:
051: def risk_score(anomaly, trend, forecast_up, vax_gap, climate, event_signal):
052:     """
053:     Calculate an explainable screening score from available components.
054:
055:     Missing components are excluded, and the remaining weights are
056:     renormalized. Weights are exploratory portfolio-demo choices,
057:     not validated public-health risk weights.
058:     """
059:     components = [
060:         (anomaly, 0.30, lambda value: value / 4),
061:         (trend, 0.20, lambda value: value),
062:         (forecast_up, 0.15, lambda value: value),
063:         (vax_gap, 0.15, lambda value: value),
064:         (climate, 0.10, lambda value: value),
065:         (event_signal, 0.10, lambda value: value),
066:     ]
067:
068:     weighted_sum = 0.0
069:     available_weight = 0.0
070:
071:     for value, weight, transform in components:
072:         if value is None:
073:             continue
074:
075:         try:
076:             value = float(value)
077:         except (TypeError, ValueError):
078:             continue
079:
080:         if not np.isfinite(value):
081:             continue
082:
083:         normalized = float(np.clip(transform(value), 0, 1))
084:
085:         weighted_sum += weight * normalized
086:         available_weight += weight
087:
088:     if available_weight == 0:
089:         return np.nan
090:
091:     score = 100 * weighted_sum / available_weight
092:     return round(float(np.clip(score, 0, 100)), 1)
093:
094: def risk_tier(score):
095:     for lo, hi, label in RISK_BANDS:

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path

path = Path("src/pipeline.py")
source = path.read_text(encoding="utf-8")

old_call = '        fc = forecast(g["value"])'
new_call = '        fc = forecast(g["year"], g["value"])'

old_signal = (
    '        forecast_up = 1.0 if pd.notna(fc) and pd.notna(prev) '
    'and fc > prev * 1.05 else 0.0'
)
new_signal = (
    '        forecast_up = ('
    'np.nan if pd.isna(fc) else '
    'float(fc > float(latest["value"]) * 1.05)'
    ')'
)

# Verify both expected lines before changing anything.
if source.count(old_call) != 1:
    raise RuntimeError(
        f"Expected exactly one old forecast call; found {source.count(old_call)}. "
        "No changes made."
    )

if source.count(old_signal) != 1:
    raise RuntimeError(
        f"Expected exactly one old forecast signal; found {source.count(old_signal)}. "
        "No changes made."
    )

updated = source.replace(old_call, new_call).replace(old_signal, new_signal)

# Validate Python syntax before saving.
compile(updated, str(path), "exec")

path.write_text(updated, encoding="utf-8")

print("Updated forecast call and forecast signal.")
print("\nRelevant code:\n")

lines = updated.splitlines()
for i in range(185, min(215, len(lines))):
    print(f"{i + 1:03d}: {lines[i]}")

/content/africa-public-health-intelligence
Updated forecast call and forecast signal.

Relevant code:

186:         return np.nan
187:
188:     try:
189:         model = ExponentialSmoothing(
190:             s.reset_index(drop=True),
191:             trend="add",
192:             damped_trend=True,
193:             initialization_method="estimated",
194:         ).fit(optimized=True)
195:
196:         forecast_value = float(model.forecast(1).iloc[0])
197:
198:         if np.isfinite(forecast_value):
199:             return max(0.0, forecast_value)
200:
201:     except (
202:         ValueError,
203:         TypeError,
204:         ArithmeticError,
205:         np.linalg.LinAlgError,
206:     ):
207:         pass
208:
209:     # Conservative fallback for a valid recent annual series.
210:     fallback = float(s.tail(3).median())
211:
212:     return max(0.0, fallback) if np.isfinite(fallback) else np.nan
213:
214:
215: def build():

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path

lines = Path("src/pipeline.py").read_text(encoding="utf-8").splitlines()

for i, line in enumerate(lines):
    if "fc = forecast(" in line or "forecast_up =" in line:
        start = max(0, i - 3)
        end = min(len(lines), i + 4)

        print("\n".join(
            f"{j + 1:03d}: {lines[j]}"
            for j in range(start, end)
        ))
        print("-" * 40)

/content/africa-public-health-intelligence
232:         g = g.sort_values("year").copy()
233:         g["anomaly_score"] = robust_anomaly(g["value"])
234:         latest = g.iloc[-1]
235:         fc = forecast(g["year"], g["value"])
236:         prev = float(g["value"].iloc[-2]) if len(g) >= 2 else np.nan
237:         forecast_up = (np.nan if pd.isna(fc) else float(fc > float(latest["value"]) * 1.05))
238:         tr = trend_score(g["value"])
----------------------------------------
234:         latest = g.iloc[-1]
235:         fc = forecast(g["year"], g["value"])
236:         prev = float(g["value"].iloc[-2]) if len(g) >= 2 else np.nan
237:         forecast_up = (np.nan if pd.isna(fc) else float(fc > float(latest["value"]) * 1.05))
238:         tr = trend_score(g["value"])
239:         vax = float(latest["measles_vax_pct"]) if disease == "Measles" and pd.notna(latest["measles_vax_pct"]) else np.nan
240:
----------------------------------------

In [ ]:

%cd /content/africa-public-health-intelligence

import importlib
import numpy as np
import pandas as pd
import src.pipeline as pipeline

# Reload the module from the updated source file.
importlib.reload(pipeline)

# Confirm the function now accepts the updated arguments.
import inspect
print("Forecast signature:", inspect.signature(pipeline.forecast))

tests = {
    "Recent consecutive years": (
        [2019, 2020, 2021, 2022, 2023, 2024],
        [100, 110, 120, 130, 140, 150],
    ),
    "Missing calendar years": (
        [2017, 2018, 2019, 2021, 2023, 2024],
        [100, 110, 120, 130, 140, 150],
    ),
    "Stale surveillance": (
        [2009, 2010, 2011, 2012, 2013, 2014],
        [100, 110, 120, 130, 140, 150],
    ),
    "Declining counts": (
        [2019, 2020, 2021, 2022, 2023, 2024],
        [600, 500, 400, 300, 200, 100],
    ),
}

for name, (years, values) in tests.items():
    result = pipeline.forecast(years, values)
    print(f"{name}: {result}")

    if name == "Recent consecutive years":
        assert np.isfinite(result)
        assert result >= 0
    elif name in ("Missing calendar years", "Stale surveillance"):
        assert pd.isna(result)
    elif name == "Declining counts":
        assert np.isfinite(result)
        assert result >= 0

print("\nAll forecasting behavior checks passed.")

/content/africa-public-health-intelligence
Forecast signature: (years, values, current_year=2026)
Recent consecutive years: 159.8500065744805
Missing calendar years: nan
Stale surveillance: nan
Declining counts: 1.4999371028711295

All forecasting behavior checks passed.

In [ ]:

%cd /content/africa-public-health-intelligence

!python -m pytest -q

/content/africa-public-health-intelligence
...                                                                      [100%]
3 passed in 0.47s

In [ ]:

%cd /content/africa-public-health-intelligence

import importlib
import src.pipeline as pipeline

# Ensure the pipeline uses the latest saved source code.
importlib.reload(pipeline)

# Rebuild the processed outputs.
risk = pipeline.build()

print("\nForecast availability:")
print(
    risk.groupby("disease")["forecast_value"]
    .agg(
        total_records="size",
        available_forecasts="count",
        missing_forecasts=lambda s: s.isna().sum(),
    )
)

print("\nLatest surveillance year by disease:")
print(
    risk.groupby("disease")["latest_year"]
    .agg(["min", "max", "count"])
)

print("\nSaved files:")
from pathlib import Path

for filename in [
    "risk_register.csv",
    "forecasts.csv",
    "disease_surveillance.csv",
]:
    path = Path("data/processed") / filename
    print(f"{filename}: {'exists' if path.exists() else 'MISSING'}")

/content/africa-public-health-intelligence
Built 63 country-disease risk records.
                     country iso3 disease  latest_year  latest_value  anomaly_score  trend_component  forecast_value  forecast_component  measles_vax_pct  vax_gap_component climate_observation_date  temp_anomaly  precip_anomaly_pct  climate_component  event_component  risk_score risk_tier                                                                                                                                                 explanation
                        Chad  TCD Measles         2024       6978.00       4.163301         1.000000     9978.360829                 1.0             66.0               0.58               2026-08-01         2.793          -57.205104           0.751526              1.0        91.2  Critical recent surveillance anomaly; rising recent trend; forecast points upward; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                    Ethiopia  ETH Malaria         2024        138.50       3.700050         1.000000      159.087123                 1.0              NaN                NaN               2026-08-01         0.911           -4.577429           0.174720              1.0        87.6  Critical                                               recent surveillance anomaly; rising recent trend; forecast points upward; recent outbreak intelligence signal
                       Sudan  SDN Cholera         2024      53001.00       2.653367         1.000000             NaN                 NaN              NaN                NaN               2026-08-01         3.722           -2.895584           0.514478              1.0        78.6  Critical                                           recent surveillance anomaly; rising recent trend; unusual climate conditions; recent outbreak intelligence signal
                       Sudan  SDN Malaria         2024         98.25       2.457207         0.792051      104.900985                 1.0              NaN                NaN               2026-08-01         3.722           -2.895584           0.514478              1.0        75.8  Critical                   recent surveillance anomaly; rising recent trend; forecast points upward; unusual climate conditions; recent outbreak intelligence signal
                    Ethiopia  ETH Measles         2024      31044.00       1.999117         1.000000    36648.800291                 1.0             72.0               0.46               2026-08-01         0.911           -4.577429           0.174720              1.0        68.6      High                                                                            rising recent trend; forecast points upward; recent outbreak intelligence signal
                      Uganda  UGA Measles         2024       2180.00       2.168354         0.906522     3099.550112                 1.0             90.0               0.10               2026-08-01         1.774          -40.983607           0.500585              1.0        65.9      High                   recent surveillance anomaly; rising recent trend; forecast points upward; unusual climate conditions; recent outbreak intelligence signal
                 South Sudan  SSD Cholera         2024      20132.00       2.759470         0.322883             NaN                 NaN              NaN                NaN               2026-08-01         3.515          -45.532298           0.727661              1.0        63.5      High                                                                recent surveillance anomaly; unusual climate conditions; recent outbreak intelligence signal
                    Cameroon  CMR Cholera         2024        199.00       0.674491         1.000000     5688.065106                 1.0              NaN                NaN               2026-08-01         1.499          -22.554636           0.362607              1.0        63.2      High                                                                            rising recent trend; forecast points upward; recent outbreak intelligence signal
                Sierra Leone  SLE Cholera         2013        377.00       0.732123         1.000000             NaN                 NaN              NaN                NaN               2026-08-01         1.877          -98.885774           0.807262              1.0        62.2      High                                                                        rising recent trend; unusual climate conditions; recent outbreak intelligence signal
Democratic Republic of Congo  COD Measles         2024     311500.00       2.367064         0.780642   291790.439768                 0.0             55.0               0.80               2026-08-01         1.741          -69.187675           0.636105              1.0        61.7      High                         recent surveillance anomaly; rising recent trend; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                        Chad  TCD Cholera         2019         93.00       0.674491         1.000000             NaN                 NaN              NaN                NaN               2026-08-01         2.793          -57.205104           0.751526              1.0        60.8      High                                                                        rising recent trend; unusual climate conditions; recent outbreak intelligence signal
                    Cameroon  CMR Measles         2024        863.00       0.626937         1.000000     3101.825602                 1.0             71.0               0.48               2026-08-01         1.499          -22.554636           0.362607              1.0        60.5      High                                                                            rising recent trend; forecast points upward; recent outbreak intelligence signal
                     Somalia  SOM Measles         2024       1529.00       0.000000         1.000000     8000.850842                 1.0             64.0               0.62               2026-08-01         0.650          -98.463312           0.600650              1.0        60.3      High                              rising recent trend; forecast points upward; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                       Ghana  GHA Measles         2024       1944.00       3.403212         1.000000     1921.844405                 0.0             90.0               0.10               2026-08-01         0.140           52.625153           0.286459              1.0        59.9      High                                                                       recent surveillance anomaly; rising recent trend; recent outbreak intelligence signal
               Cote d'Ivoire  CIV Measles         2024       1872.00       0.674491         1.000000     2027.085162                 1.0             75.0               0.40               2026-08-01         0.612          -46.905251           0.336526              1.0        59.4      High                                                                            rising recent trend; forecast points upward; recent outbreak intelligence signal

Forecast availability:
         total_records  available_forecasts  missing_forecasts
disease
Cholera             21                    6                 15
Malaria             21                   21                  0
Measles             21                   18                  3

Latest surveillance year by disease:
          min   max  count
disease
Cholera  2012  2024     21
Malaria  2024  2024     21
Measles  2024  2024     21

Saved files:
risk_register.csv: exists
forecasts.csv: exists
disease_surveillance.csv: exists

In [ ]:

%cd /content/africa-public-health-intelligence

import pandas as pd
import numpy as np

path = "data/processed/risk_register.csv"
risk = pd.read_csv(path)

# Select records with valid, positive latest values and forecasts.
audit = risk.loc[
    risk["latest_value"].notna()
    & risk["forecast_value"].notna()
    & (risk["latest_value"] > 0)
].copy()

audit["forecast_ratio"] = (
    audit["forecast_value"] / audit["latest_value"]
)

audit["absolute_change"] = (
    audit["forecast_value"] - audit["latest_value"]
)

audit["forecast_year"] = audit["latest_year"] + 1

print("Forecast audit")
print("=" * 80)
print(f"Records with forecasts and positive latest values: {len(audit)}")
print(
    "Forecasts more than 3x the latest value:",
    int((audit["forecast_ratio"] > 3).sum()),
)

columns = [
    "country",
    "disease",
    "latest_year",
    "forecast_year",
    "latest_value",
    "forecast_value",
    "forecast_ratio",
    "forecast_component",
]

print("\nLargest forecast-to-observation ratios:")
print(
    audit.sort_values("forecast_ratio", ascending=False)[columns]
    .head(15)
    .to_string(index=False)
)

print("\nForecast ratio summary:")
print(
    audit.groupby("disease")["forecast_ratio"]
    .agg(["count", "median", "max"])
    .round(2)
    .to_string()
)

/content/africa-public-health-intelligence
Forecast audit
================================================================================
Records with forecasts and positive latest values: 45
Forecasts more than 3x the latest value: 5

Largest forecast-to-observation ratios:
     country disease  latest_year  forecast_year  latest_value  forecast_value  forecast_ratio  forecast_component
    Cameroon Cholera         2024           2025        199.00     5688.065106       28.583242                 1.0
       Kenya Cholera         2024           2025        302.00     1795.763824        5.946238                 1.0
     Somalia Measles         2024           2025       1529.00     8000.850842        5.232734                 1.0
     Liberia Measles         2024           2025       1053.00     3864.626699        3.670111                 1.0
    Cameroon Measles         2024           2025        863.00     3101.825602        3.594236                 1.0
    Tanzania Measles         2024           2025        992.00     2105.984902        2.122969                 1.0
       Kenya Measles         2024           2025        525.00     1005.334455        1.914923                 1.0
     Nigeria Cholera         2024           2025      24841.00    38399.289429        1.545803                 1.0
        Mali Measles         2024           2025        366.00      542.531392        1.482326                 1.0
        Chad Measles         2024           2025       6978.00     9978.360829        1.429974                 1.0
      Uganda Measles         2024           2025       2180.00     3099.550112        1.421812                 1.0
     Senegal Measles         2024           2025        496.00      622.764655        1.255574                 1.0
      Rwanda Malaria         2024           2025         77.14       95.939998        1.243713                 1.0
Sierra Leone Measles         2024           2025        129.00      155.834059        1.208016                 1.0
    Ethiopia Measles         2024           2025      31044.00    36648.800291        1.180544                 1.0

Forecast ratio summary:
         count  median    max
disease
Cholera      6    1.28  28.58
Malaria     21    1.00   1.24
Measles     18    1.23   5.23

In [ ]:

%cd /content/africa-public-health-intelligence

import pandas as pd

surveillance = pd.read_csv(
    "data/processed/disease_surveillance.csv"
)

risk = pd.read_csv(
    "data/processed/risk_register.csv"
)

extremes = risk.loc[
    risk["forecast_value"].notna()
    & risk["latest_value"].gt(0)
    & (risk["forecast_value"] / risk["latest_value"] > 3),
    ["country", "disease", "latest_year", "latest_value", "forecast_value"],
].copy()

for _, record in extremes.iterrows():
    country = record["country"]
    disease = record["disease"]
    latest_year = int(record["latest_year"])

    history = surveillance.loc[
        surveillance["country"].eq(country)
        & surveillance["disease"].eq(disease)
        & surveillance["year"].between(latest_year - 7, latest_year)
    ].sort_values("year")

    print(
        f"\n{'=' * 70}\n"
        f"{country} — {disease}\n"
        f"Latest observation: {record['latest_value']:,.2f}\n"
        f"Forecast for {latest_year + 1}: {record['forecast_value']:,.2f}\n"
    )

    print(
        history[["year", "value"]].to_string(index=False)
    )

/content/africa-public-health-intelligence

======================================================================
Cameroon — Cholera
Latest observation: 199.00
Forecast for 2025: 5,688.07

 year   value
 2018  1052.0
 2019  1840.0
 2020  1890.0
 2021   728.0
 2022 14431.0
 2023  6470.0
 2024   199.0

======================================================================
Cameroon — Measles
Latest observation: 863.00
Forecast for 2025: 3,101.83

 year  value
 2017  712.0
 2018  814.0
 2019 2809.0
 2020 1509.0
 2021  771.0
 2022 3217.0
 2023 6105.0
 2024  863.0

======================================================================
Somalia — Measles
Latest observation: 1,529.00
Forecast for 2025: 8,000.85

 year   value
 2017 23039.0
 2018  9126.0
 2019   283.0
 2020  2531.0
 2021  7191.0
 2022 17361.0
 2023  3167.0
 2024  1529.0

======================================================================
Liberia — Measles
Latest observation: 1,053.00
Forecast for 2025: 3,864.63

 year  value
 2017  960.0
 2018 3781.0
 2019 1203.0
 2020  884.0
 2021  250.0
 2022 8300.0
 2023 4604.0
 2024 1053.0

======================================================================
Kenya — Cholera
Latest observation: 302.00
Forecast for 2025: 1,795.76

 year  value
 2017 4288.0
 2018 5719.0
 2019 5208.0
 2020  447.0
 2021   38.0
 2022 3525.0
 2023 8809.0
 2024  302.0

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path
import re

path = Path("src/pipeline.py")
source = path.read_text(encoding="utf-8")

new_function = '''def forecast(years, values, current_year=2026):
    """
    Produce a robust one-year-ahead baseline for annual disease data.

    Requires six consecutive annual observations and a latest observation
    no more than two years old. Uses the median of the last three values.
    This is a screening baseline, not a validated epidemiological model.
    """
    data = pd.DataFrame({
        "year": pd.to_numeric(pd.Series(years), errors="coerce"),
        "value": pd.to_numeric(pd.Series(values), errors="coerce"),
    })

    data = data.dropna(subset=["year", "value"]).copy()
    data = data.sort_values("year")

    if data.empty:
        return np.nan

    data = data[data["year"] % 1 == 0].copy()
    data["year"] = data["year"].astype(int)

    if data["year"].duplicated().any():
        return np.nan

    latest_year = int(data["year"].iloc[-1])

    if current_year - latest_year > 2 or latest_year > current_year:
        return np.nan

    recent = data.tail(6).copy()

    if len(recent) < 6:
        return np.nan

    if not recent["year"].diff().dropna().eq(1).all():
        return np.nan

    recent_values = recent["value"].astype("float64")

    if not np.isfinite(recent_values).all() or (recent_values < 0).any():
        return np.nan

    baseline = float(recent_values.tail(3).median())

    return max(0.0, baseline) if np.isfinite(baseline) else np.nan
'''

pattern = r"def forecast\(years, values, current_year=2026\):.*?(?=\ndef build\(\):)"

updated_source, replacements = re.subn(
    pattern,
    new_function.rstrip() + "\n\n",
    source,
    count=1,
    flags=re.DOTALL,
)

if replacements != 1:
    raise RuntimeError(
        "Expected to replace exactly one forecast function. "
        "No changes were saved."
    )

# Check syntax before saving.
compile(updated_source, str(path), "exec")

path.write_text(updated_source, encoding="utf-8")

print("SUCCESS: Forecast function updated.")
print("Method: median of the three most recent values.")
print("Validation: six consecutive annual observations required.")

/content/africa-public-health-intelligence
SUCCESS: Forecast function updated.
Method: median of the three most recent values.
Validation: six consecutive annual observations required.

In [ ]:

%cd /content/africa-public-health-intelligence

import importlib
import numpy as np
import pandas as pd
import src.pipeline as pipeline

importlib.reload(pipeline)

print("Loaded function:", pipeline.forecast.__doc__.splitlines()[1].strip())

tests = {
    "Recent consecutive years": (
        [2019, 2020, 2021, 2022, 2023, 2024],
        [100, 110, 120, 130, 140, 150],
    ),
    "Missing calendar years": (
        [2017, 2018, 2019, 2021, 2023, 2024],
        [100, 110, 120, 130, 140, 150],
    ),
    "Stale surveillance": (
        [2009, 2010, 2011, 2012, 2013, 2014],
        [100, 110, 120, 130, 140, 150],
    ),
    "Volatile annual counts": (
        [2019, 2020, 2021, 2022, 2023, 2024],
        [1000, 1800, 900, 8000, 4000, 500],
    ),
}

for name, (years, values) in tests.items():
    result = pipeline.forecast(years, values)
    print(f"{name}: {result}")

    if name == "Recent consecutive years":
        assert result == 140.0
    elif name in ("Missing calendar years", "Stale surveillance"):
        assert pd.isna(result)
    elif name == "Volatile annual counts":
        assert result == 4000.0

print("\nAll forecasting checks passed.")

/content/africa-public-health-intelligence
Loaded function: Produce a robust one-year-ahead baseline for annual disease data.
Recent consecutive years: 140.0
Missing calendar years: nan
Stale surveillance: nan
Volatile annual counts: 4000.0

All forecasting checks passed.

In [ ]:

%cd /content/africa-public-health-intelligence

import importlib
import pandas as pd
import src.pipeline as pipeline

importlib.reload(pipeline)

tests = {
    "Recent consecutive years": (
        [2019, 2020, 2021, 2022, 2023, 2024],
        [100, 110, 120, 130, 140, 150],
        140.0,
    ),
    "Missing calendar years": (
        [2017, 2018, 2019, 2021, 2023, 2024],
        [100, 110, 120, 130, 140, 150],
        None,
    ),
    "Stale surveillance": (
        [2009, 2010, 2011, 2012, 2013, 2014],
        [100, 110, 120, 130, 140, 150],
        None,
    ),
    "Volatile annual counts": (
        [2019, 2020, 2021, 2022, 2023, 2024],
        [1000, 1800, 900, 8000, 4000, 500],
        4000.0,
    ),
}

for name, (years, values, expected) in tests.items():
    result = pipeline.forecast(years, values)
    print(f"{name}: {result}")

    if expected is None:
        assert pd.isna(result), f"{name}: expected NaN, got {result}"
    else:
        assert result == expected, (
            f"{name}: expected {expected}, got {result}"
        )

print("\nAll forecasting checks passed.")

/content/africa-public-health-intelligence
Recent consecutive years: 140.0
Missing calendar years: nan
Stale surveillance: nan
Volatile annual counts: 4000.0

All forecasting checks passed.

In [ ]:

%cd /content/africa-public-health-intelligence

!python -m pytest -q

/content/africa-public-health-intelligence
...                                                                      [100%]
3 passed in 0.76s

In [ ]:

%cd /content/africa-public-health-intelligence

import importlib
import src.pipeline as pipeline

importlib.reload(pipeline)
pipeline.build()

print("\nPipeline rebuild completed.")

/content/africa-public-health-intelligence
Built 63 country-disease risk records.
                     country iso3 disease  latest_year  latest_value  anomaly_score  trend_component  forecast_value  forecast_component  measles_vax_pct  vax_gap_component climate_observation_date  temp_anomaly  precip_anomaly_pct  climate_component  event_component  risk_score risk_tier                                                                                                                         explanation
                       Sudan  SDN Cholera         2024      53001.00       2.653367         1.000000             NaN                 NaN              NaN                NaN               2026-08-01         3.722           -2.895584           0.514478              1.0        78.6  Critical                   recent surveillance anomaly; rising recent trend; unusual climate conditions; recent outbreak intelligence signal
                        Chad  TCD Measles         2024       6978.00       4.163301         1.000000         6978.00                 0.0             66.0               0.58               2026-08-01         2.793          -57.205104           0.751526              1.0        76.2  Critical recent surveillance anomaly; rising recent trend; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                    Ethiopia  ETH Malaria         2024        138.50       3.700050         1.000000          109.24                 0.0              NaN                NaN               2026-08-01         0.911           -4.577429           0.174720              1.0        70.0      High                                               recent surveillance anomaly; rising recent trend; recent outbreak intelligence signal
                 South Sudan  SSD Cholera         2024      20132.00       2.759470         0.322883             NaN                 NaN              NaN                NaN               2026-08-01         3.515          -45.532298           0.727661              1.0        63.5      High                                        recent surveillance anomaly; unusual climate conditions; recent outbreak intelligence signal
                    Cameroon  CMR Cholera         2024        199.00       0.674491         1.000000         6470.00                 1.0              NaN                NaN               2026-08-01         1.499          -22.554636           0.362607              1.0        63.2      High                                                    rising recent trend; forecast points upward; recent outbreak intelligence signal
                Sierra Leone  SLE Cholera         2013        377.00       0.732123         1.000000             NaN                 NaN              NaN                NaN               2026-08-01         1.877          -98.885774           0.807262              1.0        62.2      High                                                rising recent trend; unusual climate conditions; recent outbreak intelligence signal
Democratic Republic of Congo  COD Measles         2024     311500.00       2.367064         0.780642       311500.00                 0.0             55.0               0.80               2026-08-01         1.741          -69.187675           0.636105              1.0        61.7      High recent surveillance anomaly; rising recent trend; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                        Chad  TCD Cholera         2019         93.00       0.674491         1.000000             NaN                 NaN              NaN                NaN               2026-08-01         2.793          -57.205104           0.751526              1.0        60.8      High                                                rising recent trend; unusual climate conditions; recent outbreak intelligence signal
                    Cameroon  CMR Measles         2024        863.00       0.626937         1.000000         3217.00                 1.0             71.0               0.48               2026-08-01         1.499          -22.554636           0.362607              1.0        60.5      High                                                    rising recent trend; forecast points upward; recent outbreak intelligence signal
                     Somalia  SOM Measles         2024       1529.00       0.000000         1.000000         3167.00                 1.0             64.0               0.62               2026-08-01         0.650          -98.463312           0.600650              1.0        60.3      High      rising recent trend; forecast points upward; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                       Ghana  GHA Measles         2024       1944.00       3.403212         1.000000         1944.00                 0.0             90.0               0.10               2026-08-01         0.140           52.625153           0.286459              1.0        59.9      High                                               recent surveillance anomaly; rising recent trend; recent outbreak intelligence signal
                       Sudan  SDN Malaria         2024         98.25       2.457207         0.792051           97.57                 0.0              NaN                NaN               2026-08-01         3.722           -2.895584           0.514478              1.0        58.1      High                   recent surveillance anomaly; rising recent trend; unusual climate conditions; recent outbreak intelligence signal
                     Liberia  LBR Measles         2024       1053.00       0.000000         1.000000         4604.00                 1.0             82.0               0.26               2026-08-01         2.233          -99.383995           0.869087              1.0        57.6      High                        rising recent trend; forecast points upward; unusual climate conditions; recent outbreak intelligence signal
               Cote d'Ivoire  CIV Cholera         2021         12.00       3.503605         0.000000             NaN                 NaN              NaN                NaN               2026-08-01         0.612          -46.905251           0.336526              1.0        56.6      High                                                                    recent surveillance anomaly; recent outbreak intelligence signal
                     Liberia  LBR Cholera         2024        340.00       0.000000         1.000000             NaN                 NaN              NaN                NaN               2026-08-01         2.233          -99.383995           0.869087              1.0        55.3      High                                                rising recent trend; unusual climate conditions; recent outbreak intelligence signal

Pipeline rebuild completed.

In [ ]:

%cd /content/africa-public-health-intelligence

import pandas as pd
import numpy as np

risk = pd.read_csv("data/processed/risk_register.csv")

# 1. Audit forecast values relative to the latest reported counts.
risk["forecast_ratio"] = (
    risk["forecast_value"] / risk["latest_value"].replace(0, np.nan)
)

forecast_audit = risk[
    risk["forecast_value"].notna()
].sort_values("forecast_ratio", ascending=False)

print("=== FORECASTS MORE THAN 3 TIMES THE LATEST VALUE ===")

cols = [
    "country", "disease", "latest_year",
    "latest_value", "forecast_value", "forecast_ratio",
    "forecast_component", "risk_tier"
]

print(
    forecast_audit.loc[
        forecast_audit["forecast_ratio"] > 3, cols
    ].to_string(index=False)
)

# 2. Identify records with older surveillance observations.
print("\n=== SURVEILLANCE FRESHNESS AUDIT ===")

stale = risk[risk["latest_year"] < 2024].sort_values("latest_year")

print(
    stale[
        [
            "country", "disease", "latest_year",
            "latest_value", "forecast_value",
            "risk_score", "risk_tier"
        ]
    ].to_string(index=False)
)

print("\n=== AUDIT SUMMARY ===")
print("Total risk records:", len(risk))
print("Records with forecasts:", risk["forecast_value"].notna().sum())
print("Forecasts more than 3x latest value:",
      (risk["forecast_ratio"] > 3).sum())
print("Records with surveillance before 2024:", len(stale))

/content/africa-public-health-intelligence
=== FORECASTS MORE THAN 3 TIMES THE LATEST VALUE ===
     country disease  latest_year  latest_value  forecast_value  forecast_ratio  forecast_component risk_tier
    Cameroon Cholera         2024         199.0          6470.0       32.512563                 1.0      High
       Kenya Cholera         2024         302.0          3525.0       11.672185                 1.0      High
Sierra Leone Measles         2024         129.0           645.0        5.000000                 1.0      High
     Liberia Measles         2024        1053.0          4604.0        4.372270                 1.0      High
    Cameroon Measles         2024         863.0          3217.0        3.727694                 1.0      High

=== SURVEILLANCE FRESHNESS AUDIT ===
      country disease  latest_year  latest_value  forecast_value  risk_score risk_tier
      Senegal Cholera         2012           1.0             NaN        24.8       Low
 Sierra Leone Cholera         2013         377.0             NaN        62.2      High
       Guinea Cholera         2014           1.0             NaN        53.2      High
         Chad Cholera         2019          93.0             NaN        60.8      High
Cote d'Ivoire Cholera         2021          12.0             NaN        56.6      High
         Mali Cholera         2021          12.0             NaN        27.2  Moderate
 Burkina Faso Cholera         2022           4.0             NaN        47.2  Moderate
       Rwanda Cholera         2023         207.0             NaN        43.1  Moderate

=== AUDIT SUMMARY ===
Total risk records: 63
Records with forecasts: 45
Forecasts more than 3x latest value: 5
Records with surveillance before 2024: 8

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path

path = Path("src/risk_engine.py")
source = path.read_text(encoding="utf-8")

print(source)

/content/africa-public-health-intelligence
import numpy as np
import pandas as pd

RISK_BANDS = [
    (0, 25, "Low"),
    (25, 50, "Moderate"),
    (50, 75, "High"),
    (75, 101, "Critical"),
]

def robust_anomaly(series, window=5):
    """Robust rolling anomaly using median absolute deviation."""
    s = pd.Series(series, dtype="float64")
    med = s.rolling(window, min_periods=3).median()
    mad = (s - med).abs().rolling(window, min_periods=3).median()
    score = (s - med).abs() / (1.4826 * mad.replace(0, np.nan))
    return score.replace([np.inf, -np.inf], np.nan).fillna(0)

def trend_score(series, periods=3):
    """Score recent upward movement relative to a recent baseline."""
    s = pd.Series(series, dtype="float64").dropna()
    if len(s) < periods + 2:
        return 0.0
    recent = s.tail(periods).mean()
    baseline = s.iloc[-periods-3:-periods].mean() if len(s) >= periods + 3 else s.iloc[:-periods].mean()
    if baseline <= 0 or pd.isna(baseline):
        return 0.0
    pct = (recent - baseline) / baseline
    return float(np.clip((pct + 0.25) / 0.75, 0, 1))

def vaccination_gap(vax_percent):
    """Return a normalized vaccination gap, preserving missing values."""
    if pd.isna(vax_percent):
        return np.nan
    return float(np.clip((95 - vax_percent) / 50, 0, 1))


def climate_signal(temp_anomaly=None, precip_anomaly=None):
    """Summarize available climate anomalies; preserve missing observations."""
    vals = []

    if pd.notna(temp_anomaly):
        vals.append(np.clip(abs(temp_anomaly) / 3, 0, 1))

    if pd.notna(precip_anomaly):
        vals.append(np.clip(abs(precip_anomaly) / 100, 0, 1))

    return float(np.mean(vals)) if vals else np.nan


def risk_score(anomaly, trend, forecast_up, vax_gap, climate, event_signal):
    """
    Calculate an explainable screening score from available components.

    Missing components are excluded, and the remaining weights are
    renormalized. Weights are exploratory portfolio-demo choices,
    not validated public-health risk weights.
    """
    components = [
        (anomaly, 0.30, lambda value: value / 4),
        (trend, 0.20, lambda value: value),
        (forecast_up, 0.15, lambda value: value),
        (vax_gap, 0.15, lambda value: value),
        (climate, 0.10, lambda value: value),
        (event_signal, 0.10, lambda value: value),
    ]

    weighted_sum = 0.0
    available_weight = 0.0

    for value, weight, transform in components:
        if value is None:
            continue

        try:
            value = float(value)
        except (TypeError, ValueError):
            continue

        if not np.isfinite(value):
            continue

        normalized = float(np.clip(transform(value), 0, 1))

        weighted_sum += weight * normalized
        available_weight += weight

    if available_weight == 0:
        return np.nan

    score = 100 * weighted_sum / available_weight
    return round(float(np.clip(score, 0, 100)), 1)

def risk_tier(score):
    for lo, hi, label in RISK_BANDS:
        if lo <= score < hi:
            return label
    return "Critical"

def explain(row):
    reasons = []
    if row.get("anomaly_score", 0) >= 2:
        reasons.append("recent surveillance anomaly")
    if row.get("trend_component", 0) >= 0.6:
        reasons.append("rising recent trend")
    if row.get("forecast_component", 0) >= 0.6:
        reasons.append("forecast points upward")
    if row.get("vax_gap_component", 0) >= 0.5:
        reasons.append("immunization gap")
    if row.get("climate_component", 0) >= 0.5:
        reasons.append("unusual climate conditions")
    if row.get("event_component", 0) >= 0.5:
        reasons.append("recent outbreak intelligence signal")
    return "; ".join(reasons) if reasons else "no strong converging signal"

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path

risk_source = Path("src/risk_engine.py").read_text(encoding="utf-8")
pipeline_source = Path("src/pipeline.py").read_text(encoding="utf-8")

print("=== RISK ENGINE: BEGINNING ===")
print("\n".join(risk_source.splitlines()[:100]))

print("\n=== PIPELINE: RISK SCORING CALL ===")
lines = pipeline_source.splitlines()

for i, line in enumerate(lines):
    if "risk_score(" in line or '"risk_score"' in line or "'risk_score'" in line:
        start = max(0, i - 8)
        end = min(len(lines), i + 12)
        print(f"\nLines {start + 1}-{end}:")
        print("\n".join(
            f"{j + 1}: {lines[j]}"
            for j in range(start, end)
        ))

/content/africa-public-health-intelligence
=== RISK ENGINE: BEGINNING ===
import numpy as np
import pandas as pd

RISK_BANDS = [
    (0, 25, "Low"),
    (25, 50, "Moderate"),
    (50, 75, "High"),
    (75, 101, "Critical"),
]

def robust_anomaly(series, window=5):
    """Robust rolling anomaly using median absolute deviation."""
    s = pd.Series(series, dtype="float64")
    med = s.rolling(window, min_periods=3).median()
    mad = (s - med).abs().rolling(window, min_periods=3).median()
    score = (s - med).abs() / (1.4826 * mad.replace(0, np.nan))
    return score.replace([np.inf, -np.inf], np.nan).fillna(0)

def trend_score(series, periods=3):
    """Score recent upward movement relative to a recent baseline."""
    s = pd.Series(series, dtype="float64").dropna()
    if len(s) < periods + 2:
        return 0.0
    recent = s.tail(periods).mean()
    baseline = s.iloc[-periods-3:-periods].mean() if len(s) >= periods + 3 else s.iloc[:-periods].mean()
    if baseline <= 0 or pd.isna(baseline):
        return 0.0
    pct = (recent - baseline) / baseline
    return float(np.clip((pct + 0.25) / 0.75, 0, 1))

def vaccination_gap(vax_percent):
    """Return a normalized vaccination gap, preserving missing values."""
    if pd.isna(vax_percent):
        return np.nan
    return float(np.clip((95 - vax_percent) / 50, 0, 1))


def climate_signal(temp_anomaly=None, precip_anomaly=None):
    """Summarize available climate anomalies; preserve missing observations."""
    vals = []

    if pd.notna(temp_anomaly):
        vals.append(np.clip(abs(temp_anomaly) / 3, 0, 1))

    if pd.notna(precip_anomaly):
        vals.append(np.clip(abs(precip_anomaly) / 100, 0, 1))

    return float(np.mean(vals)) if vals else np.nan


def risk_score(anomaly, trend, forecast_up, vax_gap, climate, event_signal):
    """
    Calculate an explainable screening score from available components.

    Missing components are excluded, and the remaining weights are
    renormalized. Weights are exploratory portfolio-demo choices,
    not validated public-health risk weights.
    """
    components = [
        (anomaly, 0.30, lambda value: value / 4),
        (trend, 0.20, lambda value: value),
        (forecast_up, 0.15, lambda value: value),
        (vax_gap, 0.15, lambda value: value),
        (climate, 0.10, lambda value: value),
        (event_signal, 0.10, lambda value: value),
    ]

    weighted_sum = 0.0
    available_weight = 0.0

    for value, weight, transform in components:
        if value is None:
            continue

        try:
            value = float(value)
        except (TypeError, ValueError):
            continue

        if not np.isfinite(value):
            continue

        normalized = float(np.clip(transform(value), 0, 1))

        weighted_sum += weight * normalized
        available_weight += weight

    if available_weight == 0:
        return np.nan

    score = 100 * weighted_sum / available_weight
    return round(float(np.clip(score, 0, 100)), 1)

def risk_tier(score):
    for lo, hi, label in RISK_BANDS:
        if lo <= score < hi:
            return label
    return "Critical"

def explain(row):

=== PIPELINE: RISK SCORING CALL ===

Lines 247-266:
247:         risk["climate_component"] = np.nan
248:
249:     events = outbreak_signals()
250:     event_count = len(events)
251:     # For MVP, event intelligence is a region-level signal. A future version should
252:     # extract country/disease entities using NER and join them at country-disease level.
253:     risk["event_component"] = 1.0 if event_count else 0.0
254:
255:     risk["risk_score"] = risk.apply(lambda r: risk_score(
256:         r["anomaly_score"], r["trend_component"], r["forecast_component"],
257:         r["vax_gap_component"], r["climate_component"], r["event_component"]
258:     ), axis=1)
259:     risk["risk_tier"] = risk["risk_score"].map(risk_tier)
260:     risk["explanation"] = risk.apply(explain, axis=1)
261:
262:     risk = risk.sort_values("risk_score", ascending=False)
263:     risk.to_csv(OUT / "risk_register.csv", index=False)
264:     disease_df.to_csv(OUT / "disease_surveillance.csv", index=False)
265:     events.to_csv(OUT / "event_signals.csv", index=False)
266:

Lines 251-270:
251:     # For MVP, event intelligence is a region-level signal. A future version should
252:     # extract country/disease entities using NER and join them at country-disease level.
253:     risk["event_component"] = 1.0 if event_count else 0.0
254:
255:     risk["risk_score"] = risk.apply(lambda r: risk_score(
256:         r["anomaly_score"], r["trend_component"], r["forecast_component"],
257:         r["vax_gap_component"], r["climate_component"], r["event_component"]
258:     ), axis=1)
259:     risk["risk_tier"] = risk["risk_score"].map(risk_tier)
260:     risk["explanation"] = risk.apply(explain, axis=1)
261:
262:     risk = risk.sort_values("risk_score", ascending=False)
263:     risk.to_csv(OUT / "risk_register.csv", index=False)
264:     disease_df.to_csv(OUT / "disease_surveillance.csv", index=False)
265:     events.to_csv(OUT / "event_signals.csv", index=False)
266:
267:     # Forecast table
268:     forecasts = risk[["country","iso3","disease","latest_year","latest_value","forecast_value"]].copy()
269:     forecasts.to_csv(OUT / "forecasts.csv", index=False)
270:

Lines 254-273:
254:
255:     risk["risk_score"] = risk.apply(lambda r: risk_score(
256:         r["anomaly_score"], r["trend_component"], r["forecast_component"],
257:         r["vax_gap_component"], r["climate_component"], r["event_component"]
258:     ), axis=1)
259:     risk["risk_tier"] = risk["risk_score"].map(risk_tier)
260:     risk["explanation"] = risk.apply(explain, axis=1)
261:
262:     risk = risk.sort_values("risk_score", ascending=False)
263:     risk.to_csv(OUT / "risk_register.csv", index=False)
264:     disease_df.to_csv(OUT / "disease_surveillance.csv", index=False)
265:     events.to_csv(OUT / "event_signals.csv", index=False)
266:
267:     # Forecast table
268:     forecasts = risk[["country","iso3","disease","latest_year","latest_value","forecast_value"]].copy()
269:     forecasts.to_csv(OUT / "forecasts.csv", index=False)
270:
271:     print(f"Built {len(risk):,} country-disease risk records.")
272:     print(risk.head(15).to_string(index=False))
273:     return risk

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path

path = Path("src/risk_engine.py")
source = path.read_text(encoding="utf-8")

function_to_add = '''

def surveillance_freshness(latest_year, current_year=2026):
    """Classify the age of the latest annual surveillance observation."""
    try:
        year = float(latest_year)
    except (TypeError, ValueError):
        return "Unknown"

    if not np.isfinite(year) or year % 1 != 0:
        return "Unknown"

    year = int(year)

    if year > current_year or year < 1900:
        return "Unknown"

    age = current_year - year

    if age <= 2:
        return "Recent"
    if age <= 4:
        return "Aging"
    return "Stale"

'''

marker = "\ndef risk_tier(score):"

if source.count(marker) != 1:
    raise RuntimeError(
        "Expected exactly one risk_tier function definition. "
        "No changes were saved."
    )

if "def surveillance_freshness(" in source:
    print("Freshness function already exists; no changes made.")
else:
    updated = source.replace(
        marker,
        function_to_add + marker,
        1
    )

    compile(updated, str(path), "exec")
    path.write_text(updated, encoding="utf-8")
    print("SUCCESS: Surveillance-freshness function added.")

/content/africa-public-health-intelligence
SUCCESS: Surveillance-freshness function added.

In [ ]:

import importlib
import src.risk_engine as risk_engine

importlib.reload(risk_engine)

for year in [2026, 2024, 2023, 2022, 2021, 2019, 2013, None]:
    print(year, "->", risk_engine.surveillance_freshness(year))

2026 -> Recent
2024 -> Recent
2023 -> Aging
2022 -> Aging
2021 -> Stale
2019 -> Stale
2013 -> Stale
None -> Unknown

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path

path = Path("src/pipeline.py")
source = path.read_text(encoding="utf-8")

# Add the helper to the existing risk_engine import.
old_import = (
    "from .risk_engine import robust_anomaly, trend_score, "
    "vaccination_gap, climate_signal, risk_score, risk_tier, explain"
)

new_import = (
    "from .risk_engine import robust_anomaly, trend_score, "
    "vaccination_gap, climate_signal, risk_score, risk_tier, "
    "explain, surveillance_freshness"
)

if source.count(old_import) != 1:
    raise RuntimeError(
        "Expected exactly one matching risk_engine import. "
        "No changes were saved."
    )

updated = source.replace(old_import, new_import, 1)

# Add the freshness field immediately before the risk score is

/content/africa-public-health-intelligence

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path

lines = Path("src/pipeline.py").read_text(encoding="utf-8").splitlines()

for i, line in enumerate(lines):
    if "surveillance_freshness" in line or "risk_score" in line:
        start = max(0, i - 3)
        end = min(len(lines), i + 5)

        print(f"\n--- Lines {start + 1}-{end} ---")
        for j in range(start, end):
            print(f"{j + 1}: {lines[j]}")

print("\n=== RISK ENGINE IMPORT ===")
for line in lines:
    if "from .risk_engine import" in line:
        print(line)

/content/africa-public-health-intelligence

--- Lines 4-11 ---
4: import numpy as np
5: import pandas as pd
6: from statsmodels.tsa.holtwinters import ExponentialSmoothing
7: from .risk_engine import robust_anomaly, trend_score, vaccination_gap, climate_signal, risk_score, risk_tier, explain
8:
9: ROOT = Path(__file__).resolve().parents[1]
10: RAW = ROOT / "data" / "raw"
11: OUT = ROOT / "data" / "processed"

--- Lines 252-259 ---
252:     # extract country/disease entities using NER and join them at country-disease level.
253:     risk["event_component"] = 1.0 if event_count else 0.0
254:
255:     risk["risk_score"] = risk.apply(lambda r: risk_score(
256:         r["anomaly_score"], r["trend_component"], r["forecast_component"],
257:         r["vax_gap_component"], r["climate_component"], r["event_component"]
258:     ), axis=1)
259:     risk["risk_tier"] = risk["risk_score"].map(risk_tier)

--- Lines 256-263 ---
256:         r["anomaly_score"], r["trend_component"], r["forecast_component"],
257:         r["vax_gap_component"], r["climate_component"], r["event_component"]
258:     ), axis=1)
259:     risk["risk_tier"] = risk["risk_score"].map(risk_tier)
260:     risk["explanation"] = risk.apply(explain, axis=1)
261:
262:     risk = risk.sort_values("risk_score", ascending=False)
263:     risk.to_csv(OUT / "risk_register.csv", index=False)

--- Lines 259-266 ---
259:     risk["risk_tier"] = risk["risk_score"].map(risk_tier)
260:     risk["explanation"] = risk.apply(explain, axis=1)
261:
262:     risk = risk.sort_values("risk_score", ascending=False)
263:     risk.to_csv(OUT / "risk_register.csv", index=False)
264:     disease_df.to_csv(OUT / "disease_surveillance.csv", index=False)
265:     events.to_csv(OUT / "event_signals.csv", index=False)
266:

=== RISK ENGINE IMPORT ===
from .risk_engine import robust_anomaly, trend_score, vaccination_gap, climate_signal, risk_score, risk_tier, explain

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path

p = Path("src/pipeline.py")
s = p.read_text(encoding="utf-8")

old = "from .risk_engine import robust_anomaly, trend_score, vaccination_gap, climate_signal, risk_score, risk_tier, explain"
new = "from .risk_engine import robust_anomaly, trend_score, vaccination_gap, climate_signal, risk_score, risk_tier, explain, surveillance_freshness"

if "surveillance_freshness" not in s.splitlines()[6]:
    if old not in s:
        raise RuntimeError("Original import not found; file unchanged.")
    s = s.replace(old, new, 1)

if 'risk["surveillance_freshness"]' not in s:
    marker = '    risk["risk_score"] = risk.apply(lambda r: risk_score('
    if s.count(marker) != 1:
        raise RuntimeError("Risk-score insertion point not found; file unchanged.")

    addition = '    risk["surveillance_freshness"] = risk["latest_year"].apply(surveillance_freshness)\n\n'
    s = s.replace(marker, addition + marker, 1)

compile(s, str(p), "exec")
p.write_text(s, encoding="utf-8")

print("SUCCESS: Pipeline freshness integration saved.")

/content/africa-public-health-intelligence
SUCCESS: Pipeline freshness integration saved.

In [ ]:

%cd /content/africa-public-health-intelligence

import importlib
import src.pipeline as pipeline

importlib.reload(pipeline)
risk = pipeline.build()

print("\nFRESHNESS COUNTS")
print(risk["surveillance_freshness"].value_counts())

print("\nRECORD COUNT:", len(risk))
print("FRESHNESS COLUMN EXISTS:", "surveillance_freshness" in risk.columns)
print("MISSING LABELS:", risk["surveillance_freshness"].isna().sum())

/content/africa-public-health-intelligence
Built 63 country-disease risk records.
                     country iso3 disease  latest_year  latest_value  anomaly_score  trend_component  forecast_value  forecast_component  measles_vax_pct  vax_gap_component climate_observation_date  temp_anomaly  precip_anomaly_pct  climate_component  event_component surveillance_freshness  risk_score risk_tier                                                                                                                         explanation
                       Sudan  SDN Cholera         2024      53001.00       2.653367         1.000000             NaN                 NaN              NaN                NaN               2026-08-01         3.722           -2.895584           0.514478              1.0                 Recent        78.6  Critical                   recent surveillance anomaly; rising recent trend; unusual climate conditions; recent outbreak intelligence signal
                        Chad  TCD Measles         2024       6978.00       4.163301         1.000000         6978.00                 0.0             66.0               0.58               2026-08-01         2.793          -57.205104           0.751526              1.0                 Recent        76.2  Critical recent surveillance anomaly; rising recent trend; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                    Ethiopia  ETH Malaria         2024        138.50       3.700050         1.000000          109.24                 0.0              NaN                NaN               2026-08-01         0.911           -4.577429           0.174720              1.0                 Recent        70.0      High                                               recent surveillance anomaly; rising recent trend; recent outbreak intelligence signal
                 South Sudan  SSD Cholera         2024      20132.00       2.759470         0.322883             NaN                 NaN              NaN                NaN               2026-08-01         3.515          -45.532298           0.727661              1.0                 Recent        63.5      High                                        recent surveillance anomaly; unusual climate conditions; recent outbreak intelligence signal
                    Cameroon  CMR Cholera         2024        199.00       0.674491         1.000000         6470.00                 1.0              NaN                NaN               2026-08-01         1.499          -22.554636           0.362607              1.0                 Recent        63.2      High                                                    rising recent trend; forecast points upward; recent outbreak intelligence signal
                Sierra Leone  SLE Cholera         2013        377.00       0.732123         1.000000             NaN                 NaN              NaN                NaN               2026-08-01         1.877          -98.885774           0.807262              1.0                  Stale        62.2      High                                                rising recent trend; unusual climate conditions; recent outbreak intelligence signal
Democratic Republic of Congo  COD Measles         2024     311500.00       2.367064         0.780642       311500.00                 0.0             55.0               0.80               2026-08-01         1.741          -69.187675           0.636105              1.0                 Recent        61.7      High recent surveillance anomaly; rising recent trend; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                        Chad  TCD Cholera         2019         93.00       0.674491         1.000000             NaN                 NaN              NaN                NaN               2026-08-01         2.793          -57.205104           0.751526              1.0                  Stale        60.8      High                                                rising recent trend; unusual climate conditions; recent outbreak intelligence signal
                    Cameroon  CMR Measles         2024        863.00       0.626937         1.000000         3217.00                 1.0             71.0               0.48               2026-08-01         1.499          -22.554636           0.362607              1.0                 Recent        60.5      High                                                    rising recent trend; forecast points upward; recent outbreak intelligence signal
                     Somalia  SOM Measles         2024       1529.00       0.000000         1.000000         3167.00                 1.0             64.0               0.62               2026-08-01         0.650          -98.463312           0.600650              1.0                 Recent        60.3      High      rising recent trend; forecast points upward; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                       Ghana  GHA Measles         2024       1944.00       3.403212         1.000000         1944.00                 0.0             90.0               0.10               2026-08-01         0.140           52.625153           0.286459              1.0                 Recent        59.9      High                                               recent surveillance anomaly; rising recent trend; recent outbreak intelligence signal
                       Sudan  SDN Malaria         2024         98.25       2.457207         0.792051           97.57                 0.0              NaN                NaN               2026-08-01         3.722           -2.895584           0.514478              1.0                 Recent        58.1      High                   recent surveillance anomaly; rising recent trend; unusual climate conditions; recent outbreak intelligence signal
                     Liberia  LBR Measles         2024       1053.00       0.000000         1.000000         4604.00                 1.0             82.0               0.26               2026-08-01         2.233          -99.383995           0.869087              1.0                 Recent        57.6      High                        rising recent trend; forecast points upward; unusual climate conditions; recent outbreak intelligence signal
               Cote d'Ivoire  CIV Cholera         2021         12.00       3.503605         0.000000             NaN                 NaN              NaN                NaN               2026-08-01         0.612          -46.905251           0.336526              1.0                  Stale        56.6      High                                                                    recent surveillance anomaly; recent outbreak intelligence signal
                     Liberia  LBR Cholera         2024        340.00       0.000000         1.000000             NaN                 NaN              NaN                NaN               2026-08-01         2.233          -99.383995           0.869087              1.0                 Recent        55.3      High                                                rising recent trend; unusual climate conditions; recent outbreak intelligence signal

FRESHNESS COUNTS
surveillance_freshness
Recent    55
Stale      6
Aging      2
Name: count, dtype: int64

RECORD COUNT: 63
FRESHNESS COLUMN EXISTS: True
MISSING LABELS: 0

In [ ]:

%cd /content/africa-public-health-intelligence

import pandas as pd

df = pd.read_csv("data/processed/risk_register.csv")

print("Rows:", len(df))
print("Freshness column exists:", "surveillance_freshness" in df.columns)
print("\nFreshness counts:")
print(df["surveillance_freshness"].value_counts(dropna=False))

print("\nStale high-risk records:")
print(
    df[
        (df["surveillance_freshness"] == "Stale")
        & (df["risk_score"] >= 50)
    ][["country", "disease", "latest_year", "risk_score", "risk_tier"]]
    .to_string(index=False)
)

/content/africa-public-health-intelligence
Rows: 63
Freshness column exists: True

Freshness counts:
surveillance_freshness
Recent    55
Stale      6
Aging      2
Name: count, dtype: int64

Stale high-risk records:
      country disease  latest_year  risk_score risk_tier
 Sierra Leone Cholera         2013        62.2      High
         Chad Cholera         2019        60.8      High
Cote d'Ivoire Cholera         2021        56.6      High
       Guinea Cholera         2014        53.2      High

In [ ]:

%cd /content/africa-public-health-intelligence

import pandas as pd

path = "data/processed/risk_register.csv"
df = pd.read_csv(path)

labels = {
    "Recent": "Recent surveillance",
    "Aging": "Review required",
    "Stale": "Review required",
    "Unknown": "Unknown freshness",
}

df["evidence_freshness_status"] = (
    df["surveillance_freshness"].map(labels)
    .fillna("Unknown freshness")
)

df.to_csv(path, index=False)

print("Evidence freshness status:")
print(df["evidence_freshness_status"].value_counts())

print("\nHigh-risk records requiring review:")
print(
    df[
        (df["risk_score"] >= 50)
        & (df["evidence_freshness_status"] == "Review required")
    ][
        ["country", "disease", "latest_year", "risk_score",
         "risk_tier", "evidence_freshness_status"]
    ].to_string(index=False)
)

/content/africa-public-health-intelligence
Evidence freshness status:
evidence_freshness_status
Recent surveillance    55
Review required         8
Name: count, dtype: int64

High-risk records requiring review:
      country disease  latest_year  risk_score risk_tier evidence_freshness_status
 Sierra Leone Cholera         2013        62.2      High           Review required
         Chad Cholera         2019        60.8      High           Review required
Cote d'Ivoire Cholera         2021        56.6      High           Review required
       Guinea Cholera         2014        53.2      High           Review required

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path

p = Path("src/pipeline.py")
s = p.read_text(encoding="utf-8")

marker = '    risk["risk_score"] = risk.apply(lambda r: risk_score('

addition = '''    risk["evidence_freshness_status"] = (
        risk["surveillance_freshness"]
        .map({
            "Recent": "Recent surveillance",
            "Aging": "Review required",
            "Stale": "Review required",
            "Unknown": "Unknown freshness",
        })
        .fillna("Unknown freshness")
    )

'''

if 'risk["evidence_freshness_status"]' not in s:
    if s.count(marker) != 1:
        raise RuntimeError("Insertion point not found. File unchanged.")
    updated = s.replace(marker, addition + marker, 1)
else:
    updated = s

compile(updated, str(p), "exec")
p.write_text(updated, encoding="utf-8")

print("SUCCESS: Evidence freshness status integrated into the pipeline.")

/content/africa-public-health-intelligence
SUCCESS: Evidence freshness status integrated into the pipeline.

In [ ]:

%cd /content/africa-public-health-intelligence

import importlib
import pandas as pd
import src.pipeline as pipeline

importlib.reload(pipeline)
risk = pipeline.build()

df = pd.read_csv("data/processed/risk_register.csv")

print("\n=== RECORD VALIDATION ===")
print("Total records:", len(df))
print("Freshness column:", "surveillance_freshness" in df.columns)
print("Evidence status column:", "evidence_freshness_status" in df.columns)

print("\n=== EVIDENCE STATUS COUNTS ===")
print(df["evidence_freshness_status"].value_counts(dropna=False))

print("\n=== HIGH-RISK RECORDS REQUIRING REVIEW ===")
cols = [
    "country", "disease", "latest_year",
    "surveillance_freshness", "risk_score", "risk_tier"
]

print(
    df[
        (df["risk_score"] >= 50)
        & (df["evidence_freshness_status"] == "Review required")
    ][cols].to_string(index=False)
)

/content/africa-public-health-intelligence
Built 63 country-disease risk records.
                     country iso3 disease  latest_year  latest_value  anomaly_score  trend_component  forecast_value  forecast_component  measles_vax_pct  vax_gap_component climate_observation_date  temp_anomaly  precip_anomaly_pct  climate_component  event_component surveillance_freshness evidence_freshness_status  risk_score risk_tier                                                                                                                         explanation
                       Sudan  SDN Cholera         2024      53001.00       2.653367         1.000000             NaN                 NaN              NaN                NaN               2026-08-01         3.722           -2.895584           0.514478              1.0                 Recent       Recent surveillance        78.6  Critical                   recent surveillance anomaly; rising recent trend; unusual climate conditions; recent outbreak intelligence signal
                        Chad  TCD Measles         2024       6978.00       4.163301         1.000000         6978.00                 0.0             66.0               0.58               2026-08-01         2.793          -57.205104           0.751526              1.0                 Recent       Recent surveillance        76.2  Critical recent surveillance anomaly; rising recent trend; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                    Ethiopia  ETH Malaria         2024        138.50       3.700050         1.000000          109.24                 0.0              NaN                NaN               2026-08-01         0.911           -4.577429           0.174720              1.0                 Recent       Recent surveillance        70.0      High                                               recent surveillance anomaly; rising recent trend; recent outbreak intelligence signal
                 South Sudan  SSD Cholera         2024      20132.00       2.759470         0.322883             NaN                 NaN              NaN                NaN               2026-08-01         3.515          -45.532298           0.727661              1.0                 Recent       Recent surveillance        63.5      High                                        recent surveillance anomaly; unusual climate conditions; recent outbreak intelligence signal
                    Cameroon  CMR Cholera         2024        199.00       0.674491         1.000000         6470.00                 1.0              NaN                NaN               2026-08-01         1.499          -22.554636           0.362607              1.0                 Recent       Recent surveillance        63.2      High                                                    rising recent trend; forecast points upward; recent outbreak intelligence signal
                Sierra Leone  SLE Cholera         2013        377.00       0.732123         1.000000             NaN                 NaN              NaN                NaN               2026-08-01         1.877          -98.885774           0.807262              1.0                  Stale           Review required        62.2      High                                                rising recent trend; unusual climate conditions; recent outbreak intelligence signal
Democratic Republic of Congo  COD Measles         2024     311500.00       2.367064         0.780642       311500.00                 0.0             55.0               0.80               2026-08-01         1.741          -69.187675           0.636105              1.0                 Recent       Recent surveillance        61.7      High recent surveillance anomaly; rising recent trend; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                        Chad  TCD Cholera         2019         93.00       0.674491         1.000000             NaN                 NaN              NaN                NaN               2026-08-01         2.793          -57.205104           0.751526              1.0                  Stale           Review required        60.8      High                                                rising recent trend; unusual climate conditions; recent outbreak intelligence signal
                    Cameroon  CMR Measles         2024        863.00       0.626937         1.000000         3217.00                 1.0             71.0               0.48               2026-08-01         1.499          -22.554636           0.362607              1.0                 Recent       Recent surveillance        60.5      High                                                    rising recent trend; forecast points upward; recent outbreak intelligence signal
                     Somalia  SOM Measles         2024       1529.00       0.000000         1.000000         3167.00                 1.0             64.0               0.62               2026-08-01         0.650          -98.463312           0.600650              1.0                 Recent       Recent surveillance        60.3      High      rising recent trend; forecast points upward; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                       Ghana  GHA Measles         2024       1944.00       3.403212         1.000000         1944.00                 0.0             90.0               0.10               2026-08-01         0.140           52.625153           0.286459              1.0                 Recent       Recent surveillance        59.9      High                                               recent surveillance anomaly; rising recent trend; recent outbreak intelligence signal
                       Sudan  SDN Malaria         2024         98.25       2.457207         0.792051           97.57                 0.0              NaN                NaN               2026-08-01         3.722           -2.895584           0.514478              1.0                 Recent       Recent surveillance        58.1      High                   recent surveillance anomaly; rising recent trend; unusual climate conditions; recent outbreak intelligence signal
                     Liberia  LBR Measles         2024       1053.00       0.000000         1.000000         4604.00                 1.0             82.0               0.26               2026-08-01         2.233          -99.383995           0.869087              1.0                 Recent       Recent surveillance        57.6      High                        rising recent trend; forecast points upward; unusual climate conditions; recent outbreak intelligence signal
               Cote d'Ivoire  CIV Cholera         2021         12.00       3.503605         0.000000             NaN                 NaN              NaN                NaN               2026-08-01         0.612          -46.905251           0.336526              1.0                  Stale           Review required        56.6      High                                                                    recent surveillance anomaly; recent outbreak intelligence signal
                     Liberia  LBR Cholera         2024        340.00       0.000000         1.000000             NaN                 NaN              NaN                NaN               2026-08-01         2.233          -99.383995           0.869087              1.0                 Recent       Recent surveillance        55.3      High                                                rising recent trend; unusual climate conditions; recent outbreak intelligence signal

=== RECORD VALIDATION ===
Total records: 63
Freshness column: True
Evidence status column: True

=== EVIDENCE STATUS COUNTS ===
evidence_freshness_status
Recent surveillance    55
Review required         8
Name: count, dtype: int64

=== HIGH-RISK RECORDS REQUIRING REVIEW ===
      country disease  latest_year surveillance_freshness  risk_score risk_tier
 Sierra Leone Cholera         2013                  Stale        62.2      High
         Chad Cholera         2019                  Stale        60.8      High
Cote d'Ivoire Cholera         2021                  Stale        56.6      High
       Guinea Cholera         2014                  Stale        53.2      High

In [ ]:

%cd /content/africa-public-health-intelligence

!python -m pytest -q

/content/africa-public-health-intelligence
...                                                                      [100%]
3 passed in 0.53s

In [ ]:

%cd /content/africa-public-health-intelligence

import pandas as pd
import numpy as np

df = pd.read_csv("data/processed/risk_register.csv")

print("=== DATA QUALITY AUDIT ===")
print("Total records:", len(df))
print("Duplicate country-disease pairs:", df.duplicated(["country", "disease"]).sum())
print("Missing risk scores:", df["risk_score"].isna().sum())
print("Missing risk tiers:", df["risk_tier"].isna().sum())
print("Missing freshness labels:", df["surveillance_freshness"].isna().sum())

valid = df["forecast_value"].notna() & df["latest_value"].notna()
ratio = (
    df.loc[valid, "forecast_value"]
    / df.loc[valid, "latest_value"].replace(0, np.nan)
)

print("\nForecasts more than 3x the latest value:", (ratio > 3).sum())

print("\nRecords by risk tier:")
print(df["risk_tier"].value_counts(dropna=False))

print("\nRecords by evidence status:")
print(df["evidence_freshness_status"].value_counts(dropna=False))

/content/africa-public-health-intelligence
=== DATA QUALITY AUDIT ===
Total records: 63
Duplicate country-disease pairs: 0
Missing risk scores: 0
Missing risk tiers: 0
Missing freshness labels: 0

Forecasts more than 3x the latest value: 5

Records by risk tier:
risk_tier
Moderate    27
High        24
Low         10
Critical     2
Name: count, dtype: int64

Records by evidence status:
evidence_freshness_status
Recent surveillance    55
Review required         8
Name: count, dtype: int64

In [ ]:

%cd /content/africa-public-health-intelligence

import pandas as pd

df = pd.read_csv("data/processed/risk_register.csv")

valid = df[
    df["forecast_value"].notna()
    & df["latest_value"].notna()
    & (df["latest_value"] > 0)
].copy()

valid["forecast_ratio"] = (
    valid["forecast_value"] / valid["latest_value"]
)

extreme = valid[valid["forecast_ratio"] > 3].sort_values(
    "forecast_ratio", ascending=False
)

print("=== EXTREME FORECAST REVIEW ===")

print(
    extreme[
        [
            "country",
            "disease",
            "latest_year",
            "latest_value",
            "forecast_value",
            "forecast_ratio",
            "forecast_component",
            "risk_score",
            "risk_tier",
        ]
    ].to_string(index=False)
)

/content/africa-public-health-intelligence
=== EXTREME FORECAST REVIEW ===
     country disease  latest_year  latest_value  forecast_value  forecast_ratio  forecast_component  risk_score risk_tier
    Cameroon Cholera         2024         199.0          6470.0       32.512563                 1.0        63.2      High
       Kenya Cholera         2024         302.0          3525.0       11.672185                 1.0        54.5      High
Sierra Leone Measles         2024         129.0           645.0        5.000000                 1.0        55.2      High
     Liberia Measles         2024        1053.0          4604.0        4.372270                 1.0        57.6      High
    Cameroon Measles         2024         863.0          3217.0        3.727694                 1.0        60.5      High

In [ ]:

%cd /content/africa-public-health-intelligence

import pandas as pd

df = pd.read_csv("data/processed/disease_surveillance.csv")

targets = [
    ("Cameroon", "Cholera"),
    ("Kenya", "Cholera"),
    ("Sierra Leone", "Measles"),
    ("Liberia", "Measles"),
    ("Cameroon", "Measles"),
]

for country, disease in targets:
    rows = df[
        (df["country"] == country) &
        (df["disease"] == disease)
    ].sort_values("year").tail(8)

    print(f"\n{country} — {disease}")
    print(rows[["year", "value"]].to_string(index=False))

/content/africa-public-health-intelligence

Cameroon — Cholera
 year   value
 2015   124.0
 2018  1052.0
 2019  1840.0
 2020  1890.0
 2021   728.0
 2022 14431.0
 2023  6470.0
 2024   199.0

Kenya — Cholera
 year  value
 2017 4288.0
 2018 5719.0
 2019 5208.0
 2020  447.0
 2021   38.0
 2022 3525.0
 2023 8809.0
 2024  302.0

Sierra Leone — Measles
 year  value
 2017 1873.0
 2018  344.0
 2019   40.0
 2020   17.0
 2021  170.0
 2022  731.0
 2023  645.0
 2024  129.0

Liberia — Measles
 year  value
 2017  960.0
 2018 3781.0
 2019 1203.0
 2020  884.0
 2021  250.0
 2022 8300.0
 2023 4604.0
 2024 1053.0

Cameroon — Measles
 year  value
 2017  712.0
 2018  814.0
 2019 2809.0
 2020 1509.0
 2021  771.0
 2022 3217.0
 2023 6105.0
 2024  863.0

In [ ]:

%cd /content/africa-public-health-intelligence

import pandas as pd

df = pd.read_csv("data/processed/disease_surveillance.csv")

targets = [
    ("Cameroon", "Cholera"),
    ("Kenya", "Cholera"),
    ("Sierra Leone", "Measles"),
    ("Liberia", "Measles"),
    ("Cameroon", "Measles"),
]

for country, disease in targets:
    rows = df[
        (df["country"] == country) &
        (df["disease"] == disease)
    ].sort_values("year")

    last = rows.iloc[-1]
    previous = rows.iloc[-2]

    change = (last["value"] / previous["value"] - 1) * 100

    print(
        country, "|", disease,
        "| previous year:", int(previous["year"]),
        "| latest year:", int(last["year"]),
        "| percentage change:", round(change, 1), "%"
    )

/content/africa-public-health-intelligence
Cameroon | Cholera | previous year: 2023 | latest year: 2024 | percentage change: -96.9 %
Kenya | Cholera | previous year: 2023 | latest year: 2024 | percentage change: -96.6 %
Sierra Leone | Measles | previous year: 2023 | latest year: 2024 | percentage change: -80.0 %
Liberia | Measles | previous year: 2023 | latest year: 2024 | percentage change: -77.1 %
Cameroon | Measles | previous year: 2023 | latest year: 2024 | percentage change: -85.9 %

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path

lines = Path("src/pipeline.py").read_text().splitlines()

for i, line in enumerate(lines):
    if "forecast_component" in line or "forecast_value" in line:
        start = max(0, i - 3)
        end = min(len(lines), i + 5)

        print(f"\n--- Lines {start + 1}–{end} ---")
        for j in range(start, end):
            print(f"{j + 1}: {lines[j]}")

/content/africa-public-health-intelligence

--- Lines 215–222 ---
215:             "latest_value": float(latest["value"]),
216:             "anomaly_score": float(latest["anomaly_score"]),
217:             "trend_component": tr,
218:             "forecast_value": fc,
219:             "forecast_component": forecast_up,
220:             "measles_vax_pct": vax,
221:             "vax_gap_component": vaccination_gap(vax),
222:         })

--- Lines 216–223 ---
216:             "anomaly_score": float(latest["anomaly_score"]),
217:             "trend_component": tr,
218:             "forecast_value": fc,
219:             "forecast_component": forecast_up,
220:             "measles_vax_pct": vax,
221:             "vax_gap_component": vaccination_gap(vax),
222:         })
223:

--- Lines 266–273 ---
266:     )
267:
268:     risk["risk_score"] = risk.apply(lambda r: risk_score(
269:         r["anomaly_score"], r["trend_component"], r["forecast_component"],
270:         r["vax_gap_component"], r["climate_component"], r["event_component"]
271:     ), axis=1)
272:     risk["risk_tier"] = risk["risk_score"].map(risk_tier)
273:     risk["explanation"] = risk.apply(explain, axis=1)

--- Lines 278–285 ---
278:     events.to_csv(OUT / "event_signals.csv", index=False)
279:
280:     # Forecast table
281:     forecasts = risk[["country","iso3","disease","latest_year","latest_value","forecast_value"]].copy()
282:     forecasts.to_csv(OUT / "forecasts.csv", index=False)
283:
284:     print(f"Built {len(risk):,} country-disease risk records.")
285:     print(risk.head(15).to_string(index=False))

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path

p = Path("src/pipeline.py")
s = p.read_text(encoding="utf-8")

marker = '    risk["risk_score"] = risk.apply'

addition = '''    def forecast_warning(row):
        forecast = row["forecast_value"]
        latest = row["latest_value"]

        if pd.isna(forecast):
            return "No forecast available"
        if pd.isna(latest) or latest <= 0:
            return "Check baseline"
        if forecast / latest > 3:
            return "Review forecast"
        return "No large increase flagged"

    risk["forecast_warning"] = risk.apply(forecast_warning, axis=1)

'''

if 'risk["forecast_warning"]' not in s:
    if s.count(marker) != 1:
        raise RuntimeError("Insertion point not found; file unchanged.")
    updated = s.replace(marker, addition + marker, 1)
    compile(updated, str(p), "exec")
    p.write_text(updated, encoding="utf-8")

print("SUCCESS: Forecast warning integration saved.")

/content/africa-public-health-intelligence
SUCCESS: Forecast warning integration saved.

In [ ]:

%cd /content/africa-public-health-intelligence

!python -m pytest -q

/content/africa-public-health-intelligence
...                                                                      [100%]
3 passed in 0.55s

In [ ]:

%cd /content/africa-public-health-intelligence

import pandas as pd
from pathlib import Path

p = Path("data/processed/risk_register.csv")
df = pd.read_csv(p)

print("FINAL BUILD CHECK")
print("Risk records:", len(df))
print("Duplicate country-disease pairs:",
      df.duplicated(["country", "disease"]).sum())
print("Missing risk scores:", df["risk_score"].isna().sum())
print("Missing risk tiers:", df["risk_tier"].isna().sum())
print("Forecast warning column present:",
      "forecast_warning" in df.columns)

print("\nRisk tier distribution:")
print(df["risk_tier"].value_counts().to_string())

/content/africa-public-health-intelligence
FINAL BUILD CHECK
Risk records: 63
Duplicate country-disease pairs: 0
Missing risk scores: 0
Missing risk tiers: 0
Forecast warning column present: False

Risk tier distribution:
risk_tier
Moderate    27
High        24
Low         10
Critical     2

In [ ]:

%cd /content/africa-public-health-intelligence

import importlib
import pandas as pd
import src.pipeline as pipeline

importlib.reload(pipeline)
pipeline.build()

df = pd.read_csv("data/processed/risk_register.csv")

print("\nFINAL VERIFICATION")
print("Risk records:", len(df))
print("Forecast warning present:", "forecast_warning" in df.columns)

if "forecast_warning" in df.columns:
    print("\nForecast warning counts:")
    print(df["forecast_warning"].value_counts().to_string())
else:
    print("WARNING: Forecast warning was not saved.")

/content/africa-public-health-intelligence
Built 63 country-disease risk records.
                     country iso3 disease  latest_year  latest_value  anomaly_score  trend_component  forecast_value  forecast_component  measles_vax_pct  vax_gap_component climate_observation_date  temp_anomaly  precip_anomaly_pct  climate_component  event_component surveillance_freshness evidence_freshness_status          forecast_warning  risk_score risk_tier                                                                                                                         explanation
                       Sudan  SDN Cholera         2024      53001.00       2.653367         1.000000             NaN                 NaN              NaN                NaN               2026-08-01         3.722           -2.895584           0.514478              1.0                 Recent       Recent surveillance     No forecast available        78.6  Critical                   recent surveillance anomaly; rising recent trend; unusual climate conditions; recent outbreak intelligence signal
                        Chad  TCD Measles         2024       6978.00       4.163301         1.000000         6978.00                 0.0             66.0               0.58               2026-08-01         2.793          -57.205104           0.751526              1.0                 Recent       Recent surveillance No large increase flagged        76.2  Critical recent surveillance anomaly; rising recent trend; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                    Ethiopia  ETH Malaria         2024        138.50       3.700050         1.000000          109.24                 0.0              NaN                NaN               2026-08-01         0.911           -4.577429           0.174720              1.0                 Recent       Recent surveillance No large increase flagged        70.0      High                                               recent surveillance anomaly; rising recent trend; recent outbreak intelligence signal
                 South Sudan  SSD Cholera         2024      20132.00       2.759470         0.322883             NaN                 NaN              NaN                NaN               2026-08-01         3.515          -45.532298           0.727661              1.0                 Recent       Recent surveillance     No forecast available        63.5      High                                        recent surveillance anomaly; unusual climate conditions; recent outbreak intelligence signal
                    Cameroon  CMR Cholera         2024        199.00       0.674491         1.000000         6470.00                 1.0              NaN                NaN               2026-08-01         1.499          -22.554636           0.362607              1.0                 Recent       Recent surveillance           Review forecast        63.2      High                                                    rising recent trend; forecast points upward; recent outbreak intelligence signal
                Sierra Leone  SLE Cholera         2013        377.00       0.732123         1.000000             NaN                 NaN              NaN                NaN               2026-08-01         1.877          -98.885774           0.807262              1.0                  Stale           Review required     No forecast available        62.2      High                                                rising recent trend; unusual climate conditions; recent outbreak intelligence signal
Democratic Republic of Congo  COD Measles         2024     311500.00       2.367064         0.780642       311500.00                 0.0             55.0               0.80               2026-08-01         1.741          -69.187675           0.636105              1.0                 Recent       Recent surveillance No large increase flagged        61.7      High recent surveillance anomaly; rising recent trend; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                        Chad  TCD Cholera         2019         93.00       0.674491         1.000000             NaN                 NaN              NaN                NaN               2026-08-01         2.793          -57.205104           0.751526              1.0                  Stale           Review required     No forecast available        60.8      High                                                rising recent trend; unusual climate conditions; recent outbreak intelligence signal
                    Cameroon  CMR Measles         2024        863.00       0.626937         1.000000         3217.00                 1.0             71.0               0.48               2026-08-01         1.499          -22.554636           0.362607              1.0                 Recent       Recent surveillance           Review forecast        60.5      High                                                    rising recent trend; forecast points upward; recent outbreak intelligence signal
                     Somalia  SOM Measles         2024       1529.00       0.000000         1.000000         3167.00                 1.0             64.0               0.62               2026-08-01         0.650          -98.463312           0.600650              1.0                 Recent       Recent surveillance No large increase flagged        60.3      High      rising recent trend; forecast points upward; immunization gap; unusual climate conditions; recent outbreak intelligence signal
                       Ghana  GHA Measles         2024       1944.00       3.403212         1.000000         1944.00                 0.0             90.0               0.10               2026-08-01         0.140           52.625153           0.286459              1.0                 Recent       Recent surveillance No large increase flagged        59.9      High                                               recent surveillance anomaly; rising recent trend; recent outbreak intelligence signal
                       Sudan  SDN Malaria         2024         98.25       2.457207         0.792051           97.57                 0.0              NaN                NaN               2026-08-01         3.722           -2.895584           0.514478              1.0                 Recent       Recent surveillance No large increase flagged        58.1      High                   recent surveillance anomaly; rising recent trend; unusual climate conditions; recent outbreak intelligence signal
                     Liberia  LBR Measles         2024       1053.00       0.000000         1.000000         4604.00                 1.0             82.0               0.26               2026-08-01         2.233          -99.383995           0.869087              1.0                 Recent       Recent surveillance           Review forecast        57.6      High                        rising recent trend; forecast points upward; unusual climate conditions; recent outbreak intelligence signal
               Cote d'Ivoire  CIV Cholera         2021         12.00       3.503605         0.000000             NaN                 NaN              NaN                NaN               2026-08-01         0.612          -46.905251           0.336526              1.0                  Stale           Review required     No forecast available        56.6      High                                                                    recent surveillance anomaly; recent outbreak intelligence signal
                     Liberia  LBR Cholera         2024        340.00       0.000000         1.000000             NaN                 NaN              NaN                NaN               2026-08-01         2.233          -99.383995           0.869087              1.0                 Recent       Recent surveillance     No forecast available        55.3      High                                                rising recent trend; unusual climate conditions; recent outbreak intelligence signal

FINAL VERIFICATION
Risk records: 63
Forecast warning present: True

Forecast warning counts:
forecast_warning
No large increase flagged    40
No forecast available        18
Review forecast               5

In [ ]:

from pathlib import Path

found = list(Path("/content").glob("*/.git"))

print("Git repositories found:")
for p in found:
    print(p.parent)

if not found:
    print("No Git repository found under /content.")

Git repositories found:
No Git repository found under /content.

In [ ]:

%cd /content/africa-public-health-intelligence

!git init
!git branch -M main
!git remote add origin https://github.com/evanskips2727-del/Africa-Public-Health-Intelligence-.git
!git status --short

/content/africa-public-health-intelligence
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /content/africa-public-health-intelligence/.git/
?? .github/
?? .gitignore
?? README.md
?? app.py
?? config/
?? data/
?? docs/
?? requirements.txt
?? scripts/
?? src/
?? tests/

In [ ]:

%cd /content/africa-public-health-intelligence

print("=== .gitignore ===")
!cat .gitignore

print("\n=== LARGE FILES (over 5 MB) ===")
!find . -type f -not -path './.git/*' -size +5M -print

print("\n=== POSSIBLE SECRET FILES ===")
!find . -type f -not -path './.git/*' \( -name '.env' -o -name '*credentials*' -o -name '*secret*' \) -print

/content/africa-public-health-intelligence
=== .gitignore ===
__pycache__/
*.pyc
.venv/
.env
data/raw/*
data/processed/*
!data/raw/.gitkeep
!data/processed/.gitkeep
.streamlit/

=== LARGE FILES (over 5 MB) ===

=== POSSIBLE SECRET FILES ===

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path

print("PROCESSED DATA FILES")
for p in sorted(Path("data/processed").glob("*")):
    if p.is_file():
        print(f"{p.name}: {p.stat().st_size:,} bytes")

print("\nDASHBOARD DATA REFERENCES")
for i, line in enumerate(Path("app.py").read_text().splitlines(), 1):
    if "data/processed" in line or "read_csv" in line:
        print(f"{i}: {line.strip()}")

/content/africa-public-health-intelligence
PROCESSED DATA FILES
.gitkeep: 0 bytes
climate_anomalies.csv: 337,388 bytes
climate_monthly_clean.csv: 104,186 bytes
disease_surveillance.csv: 81,549 bytes
event_signals.csv: 25,126 bytes
forecasts.csv: 2,457 bytes
risk_register.csv: 17,556 bytes

DASHBOARD DATA REFERENCES
20: risk = pd.read_csv(RISK)
21: surv = pd.read_csv(SURV)
22: events = pd.read_csv(EVENTS) if EVENTS.exists() else pd.DataFrame()

In [ ]:

%cd /content/africa-public-health-intelligence

from pathlib import Path

p = Path(".gitignore")
s = p.read_text(encoding="utf-8")

s = s.replace(
    "data/processed/*\n!data/processed/.gitkeep",
    "data/processed/*\n!data/processed/.gitkeep\n!data/processed/*.csv"
)

p.write_text(s, encoding="utf-8")

print("Updated .gitignore.")
print("\nProcessed CSV files will be eligible for Git.")
print("Raw data remains excluded.")

/content/africa-public-health-intelligence
Updated .gitignore.

Processed CSV files will be eligible for Git.
Raw data remains excluded.

In [ ]:

%cd /content/africa-public-health-intelligence

!git add .
!git status --short

/content/africa-public-health-intelligence
A  .github/workflows/ci.yml
A  .gitignore
A  README.md
A  app.py
A  config/countries.csv
A  data/SOURCES.md
A  data/processed/.gitkeep
A  data/raw/.gitkeep
A  docs/PORTFOLIO_CASE_STUDY.md
A  requirements.txt
A  scripts/download_data.py
A  src/__init__.py
A  src/pipeline.py
A  src/risk_engine.py
A  tests/test_risk.py

In [ ]:

%cd /content/africa-public-health-intelligence

print("=== CHECK IGNORE RULES ===")
!git check-ignore -v data/processed/*.csv

print("\n=== ADD PROCESSED DATASETS ===")
!git add -f data/processed/*.csv

print("\n=== VERIFY STAGED FILES ===")
!git status --short

/content/africa-public-health-intelligence
=== CHECK IGNORE RULES ===
.gitignore:6:data/processed/*	data/processed/climate_anomalies.csv
.gitignore:6:data/processed/*	data/processed/climate_monthly_clean.csv
.gitignore:6:data/processed/*	data/processed/disease_surveillance.csv
.gitignore:6:data/processed/*	data/processed/event_signals.csv
.gitignore:6:data/processed/*	data/processed/forecasts.csv
.gitignore:6:data/processed/*	data/processed/risk_register.csv

=== ADD PROCESSED DATASETS ===

=== VERIFY STAGED FILES ===
A  .github/workflows/ci.yml
A  .gitignore
A  README.md
A  app.py
A  config/countries.csv
A  data/SOURCES.md
A  data/processed/.gitkeep
A  data/processed/climate_anomalies.csv
A  data/processed/climate_monthly_clean.csv
A  data/processed/disease_surveillance.csv
A  data/processed/event_signals.csv
A  data/processed/forecasts.csv
A  data/processed/risk_register.csv
A  data/raw/.gitkeep
A  docs/PORTFOLIO_CASE_STUDY.md
A  requirements.txt
A  scripts/download_data.py
A  src/__init__.py
A  src/pipeline.py
A  src/risk_engine.py
A  tests/test_risk.py

In [ ]:

%cd /content/africa-public-health-intelligence

print("=== REMOTE ===")
!git remote -v

print("\n=== CURRENT BRANCH ===")
!git branch --show-current

print("\n=== COMMIT ===")
!git log -1 --oneline

/content/africa-public-health-intelligence
=== REMOTE ===
origin	https://github.com/evanskips2727-del/Africa-Public-Health-Intelligence-.git (fetch)
origin	https://github.com/evanskips2727-del/Africa-Public-Health-Intelligence-.git (push)

=== CURRENT BRANCH ===
main

=== COMMIT ===
f188890 (HEAD -> main) Publish Africa Public Health Intelligence prototype

In [ ]:

%cd /content/africa-public-health-intelligence

!git remote get-url origin
!git log -1 --oneline
!git status --short

/content/africa-public-health-intelligence
https://github.com/evanskips2727-del/Africa-Public-Health-Intelligence-.git
f188890 (HEAD -> main) Publish Africa Public Health Intelligence prototype

In [ ]:

git remote add origin https://github.com/evanskips2727-del/Africa-Public-Health-Intelligence-.git
git branch -M main
git push -u origin main

SyntaxError: invalid syntax (1034060585.py, line 1)

In [ ]:

from getpass import getpass
import os
import subprocess
import tempfile

token = getpass("Enter your NEW GitHub token (hidden): ")

askpass_script = """#!/bin/sh
case "$1" in
  *Username*) echo "$GH_USERNAME" ;;
  *Password*) echo "$GH_TOKEN" ;;
  *) exit 1 ;;
esac
"""

fd, askpass_path = tempfile.mkstemp()
with os.fdopen(fd, "w") as f:
    f.write(askpass_script)
os.chmod(askpass_path, 0o700)

env = os.environ.copy()
env["GH_USERNAME"] = "evanskips2727-del"
env["GH_TOKEN"] = token
env["GIT_ASKPASS"] = askpass_path
env["GIT_TERMINAL_PROMPT"] = "0"

try:
    result = subprocess.run(
        ["git", "push", "-u", "origin", "main"],
        cwd="/content/africa-public-health-intelligence",
        env=env,
        capture_output=True,
        text=True
    )
    print(result.stdout)
    print(result.stderr)
    print("SUCCESS" if result.returncode == 0 else "PUSH FAILED")
finally:
    token = None
    env.pop("GH_TOKEN", None)
    os.remove(askpass_path)

Enter your NEW GitHub token (hidden): ··········
branch 'main' set up to track 'origin/main'.

To https://github.com/evanskips2727-del/Africa-Public-Health-Intelligence-.git
 * [new branch]      main -> main

SUCCESS

In [ ]:

%cd /content/africa-public-health-intelligence

print("=== CURRENT CI WORKFLOW ===")
!cat .github/workflows/ci.yml

print("\n=== REQUIREMENTS ===")
!cat requirements.txt

/content/africa-public-health-intelligence
=== CURRENT CI WORKFLOW ===
name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: pytest -q

=== REQUIREMENTS ===
pandas>=2.2
numpy>=1.26
requests>=2.31
scikit-learn>=1.5
statsmodels>=0.14
plotly>=5.24
streamlit>=1.39
pyarrow>=17.0

In [ ]:

%cd /content/africa-public-health-intelligence
!python -m pytest -q

/content/africa-public-health-intelligence
...                                                                      [100%]
3 passed in 1.01s

In [ ]:
!gh auth login